Repository ezsystems/ezpublish-kernel, pull requests merged in 2018-06, with the labels that each got.

#2332 EZP-29201: Additional indexes/foreign keys on the ezcontentbrowsebookmark table
  data/mysql/schema.sql
  data/update/mysql/dbupdate-7.1.0-to-7.2.0.sql
  data/update/postgres/dbupdate-7.1.0-to-7.2.0.sql
  eZ/Publish/API/Repository/Tests/LocationServiceTest.php
  eZ/Publish/API/Repository/Tests/SetupFactory/Legacy.php
  eZ/Publish/API/Repository/Tests/UserServiceTest.php
  eZ/Publish/Core/Persistence/Cache/BookmarkHandler.php
  eZ/Publish/Core/Persistence/Cache/Tests/BookmarkHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Bookmark/_fixtures/bookmarks.php
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.mysql.sql
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.pgsql.sql
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.sqlite.sql
  eZ/Publish/Core/Repository/Tests/Service/Integration/Legacy/_fixtures/clean_ezdemo_47_dump.php
Labels: QA approved

#2340 EZP-29147: As a developer, I want a REST API to manage bookmarks
  doc/specifications/rest/REST-API-V2.rst
  eZ/Bundle/EzPublishRestBundle/Resources/config/routing.yml
  eZ/Bundle/EzPublishRestBundle/Resources/config/services.yml
  eZ/Bundle/EzPublishRestBundle/Resources/config/value_object_visitors.yml
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/BookmarkTest.php
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/TestCase.php
  eZ/Publish/Core/REST/Server/Controller/Bookmark.php
  eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/BookmarkList.php
  eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/BookmarkListTest.php
  eZ/Publish/Core/REST/Server/Values/BookmarkList.php
Labels: QA approved

#2325 EZP-25487: Stored Image Variation in Image Variation Cache
  eZ/Bundle/EzPublishCoreBundle/Imagine/AliasGenerator.php
  eZ/Bundle/EzPublishCoreBundle/Imagine/Cache/AliasGeneratorDecorator.php
  eZ/Bundle/EzPublishCoreBundle/Imagine/Variation/ImagineAwareAliasGenerator.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/AliasGeneratorTest.php
Labels: Ready for QA

#2346 EZP-29167: Logged a warning about using default URL alias transformation
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/SlugConverterConfigurationPass.php
Labels: QA approved

#2307 EZP-29093: Add state limitations to versionRead and VersionRemove
  eZ/Publish/Core/settings/policies.yml
Labels: Ready for QA

#2361 EZP-29322: As an editor I want to use translated Admin panel
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/TranslationCollectorPass.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/TranslationCollectorPassTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Fixtures/vendor/ezplatform-i18n/ezplatform-i18n-hi_in/ezpublish-kernel/messages.hi_IN.xlf
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Fixtures/vendor/ezplatform-i18n/ezplatform-i18n-nb_no/ezpublish-kernel/messages.nb_NO.xlf
Labels: Ready for review

#2064 EZP-27429: Optional SiteAccessAware Repository layer
  .travis.yml
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/helpers.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
  eZ/Publish/API/Repository/Tests/SetupFactory/Legacy.php
  eZ/Publish/API/Repository/Values/Content/Language.php
  eZ/Publish/Core/REST/Server/Controller/Content.php
  eZ/Publish/Core/REST/Server/Controller/ContentType.php
  eZ/Publish/Core/REST/Server/Controller/ObjectState.php
  eZ/Publish/Core/REST/Server/Controller/User.php
  eZ/Publish/Core/REST/Server/Controller/Views.php
  eZ/Publish/Core/Repository/Permission/CachedPermissionService.php
  eZ/Publish/Core/Repository/Permission/PermissionResolver.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
  eZ/Publish/Core/Repository/SiteAccessAware/ContentTypeService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Language/LanguageResolver.php
  eZ/Publish/Core/Repository/SiteAccessAware/LanguageService.php
  eZ/Publish/Core/Repository/SiteAccessAware/LocationService.php
  eZ/Publish/Core/Repository/SiteAccessAware/ObjectStateService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Repository.php
  eZ/Publish/Core/Repository/SiteAccessAware/SearchService.php
  eZ/Publish/Core/Repository/SiteAccessAware/SectionService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/AbstractServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentTypeServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/LanguageServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/LocationServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/ObjectStateServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/SearchServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/TrashServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/UrlAliasServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/UserServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/TrashService.php
  eZ/Publish/Core/Repository/SiteAccessAware/URLAliasService.php
  eZ/Publish/Core/Repository/SiteAccessAware/UserService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/UrlAliasTest.php
  eZ/Publish/Core/Repository/URLAliasService.php
  eZ/Publish/Core/SignalSlot/Repository.php
  eZ/Publish/Core/SignalSlot/URLAliasService.php
  eZ/Publish/Core/settings/containerBuilder.php
  eZ/Publish/Core/settings/repository/siteaccessaware.yml
  eZ/Publish/SPI/Tests/FieldType/BaseIntegrationTest.php
  eZ/Publish/SPI/Tests/FieldType/FileBaseIntegrationTest.php
  phpunit.xml
Labels: Ready for QA

#2357 EZP-29238: As an Administrator I want to resize original images
  eZ/Bundle/EzPublishCoreBundle/Command/ResizeOriginalImagesCommand.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
Labels: Ready for QA

#2362 EZEE-2145: [Router] Fixed generating Req. Context to include URI scheme
  eZ/Bundle/EzPublishCoreBundle/Routing/DefaultRouter.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Routing/DefaultRouterTest.php
  eZ/Publish/Core/MVC/Symfony/Routing/Generator.php
Labels: Ready for QA, Ready for review

#2355 EZP-28942: As a REST consumer, I want to sort a view using a Field
  eZ/Bundle/EzPublishRestBundle/Resources/config/input_parsers.yml
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/SortClauseTest.php
  eZ/Publish/Core/REST/Server/Input/Parser/Query.php
  eZ/Publish/Core/REST/Server/Input/Parser/SortClause/Field.php
  eZ/Publish/Core/REST/Server/Tests/Input/Parser/SortClause/FieldTest.php
Labels: QA approved

#2366 [7.2] EZP-29206: Added missing upgrade scripts
  data/update/mysql/dbupdate-7.1.0-to-7.2.0.sql
  data/update/postgres/dbupdate-7.1.0-to-7.2.0.sql
Labels: Ready for QA

#2365 [6.13] EZP-29206: Added missing upgrade scripts
  data/update/mysql/dbupdate-6.13.3-to-6.13.4.sql
  data/update/postgres/dbupdate-6.13.3-to-6.13.4.sql
Labels: Ready for QA
