Repository ezsystems/ezpublish-kernel, pull requests merged in 2018-12, with the labels that each got.

#2444 EZP-29613: As a developer I want access to ContentType on Content to avoid re-loading it
  eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
  eZ/Bundle/EzPublishRestBundle/Resources/config/value_object_visitors.yml
  eZ/Publish/API/Repository/ContentTypeService.php
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
  eZ/Publish/API/Repository/Values/Content/Content.php
  eZ/Publish/Core/Helper/FieldHelper.php
  eZ/Publish/Core/Helper/Tests/FieldHelperTest.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/FieldRenderingExtensionIntegrationTest.php
  eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/ContentExtension.php
  eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/FieldRenderingExtension.php
  eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php
  eZ/Publish/Core/Persistence/Cache/Tests/ContentTypeHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Mapper.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/MemoryCachingHandler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/ContentTypeHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/TestCase.php
  eZ/Publish/Core/REST/Client/ContentTypeService.php
  eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/RestExecutedView.php
  eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/RestExecutedViewTest.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/ContentTypeService.php
  eZ/Publish/Core/Repository/Helper/DomainMapper.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/SiteAccessAware/ContentTypeService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/DomainMapperTest.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/NameSchemaTest.php
  eZ/Publish/Core/Repository/Values/Content/Content.php
  eZ/Publish/Core/Repository/Values/Content/ContentProxy.php
  eZ/Publish/Core/Repository/Values/User/User.php
  eZ/Publish/Core/Repository/Values/User/UserGroup.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/AbstractTestCase.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerContentSortTest.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerContentTest.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerLocationSortTest.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerLocationTest.php
  eZ/Publish/Core/SignalSlot/ContentTypeService.php
  eZ/Publish/SPI/Persistence/Content/Type.php
  eZ/Publish/SPI/Persistence/Content/Type/Handler.php
Labels: QA approved

#2471 EZP-29751: Wrong first URL generation in exotic languages
  eZ/Publish/API/Repository/Tests/URLAliasServiceTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Handler.php
Labels: QA approved

#2480 EZP-29823: Allow to filter Location on translations to not throw when lazy loading Content
  eZ/Publish/API/Repository/LocationService.php
  eZ/Publish/API/Repository/Tests/BaseTest.php
  eZ/Publish/API/Repository/Tests/LanguageServiceTest.php
  eZ/Publish/API/Repository/Tests/LocationServiceTest.php
  eZ/Publish/Core/Persistence/Cache/LocationHandler.php
  eZ/Publish/Core/Persistence/Cache/Tests/LocationHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/Language/MaskGenerator.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Content/TreeHandler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/Gateway/DoctrineDatabaseTrashTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
  eZ/Publish/Core/Repository/LocationService.php
  eZ/Publish/Core/Repository/SiteAccessAware/LocationService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/AbstractServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/LocationServiceTest.php
  eZ/Publish/Core/SignalSlot/LocationService.php
  eZ/Publish/Core/SignalSlot/Tests/LocationServiceTest.php
  eZ/Publish/Core/settings/storage_engines/legacy/location.yml
  eZ/Publish/SPI/Persistence/Content/Location/Handler.php
Labels: Ready for QA

#2498 EZP-29864: Spelling mistake in Content Type alert warnings
  eZ/Publish/Core/FieldType/Tests/StringLengthValidatorTest.php
  eZ/Publish/Core/FieldType/Tests/TextLineTest.php
  eZ/Publish/Core/FieldType/TextLine/Type.php
  eZ/Publish/Core/FieldType/Validator/StringLengthValidator.php
Labels: Bug, Ready for QA

#2083 Fix EZP-28099: Wrong Urls at equal beginning path prefixes
  eZ/Publish/Core/MVC/Symfony/Routing/Generator/UrlAliasGenerator.php
  eZ/Publish/Core/MVC/Symfony/Routing/Tests/UrlAliasGeneratorTest.php
Labels: QA approved

#2482 EZP-29122: As a developer, I want to configure password policies in ezuser
  eZ/Publish/API/Repository/Tests/FieldType/UserIntegrationTest.php
  eZ/Publish/API/Repository/Tests/UserServiceTest.php
  eZ/Publish/API/Repository/UserService.php
  eZ/Publish/API/Repository/Values/Translation/Message.php
  eZ/Publish/API/Repository/Values/Translation/Plural.php
  eZ/Publish/API/Repository/Values/User/PasswordValidationContext.php
  eZ/Publish/Core/Base/Exceptions/UserPasswordValidationException.php
  eZ/Publish/Core/FieldType/Tests/UserTest.php
  eZ/Publish/Core/FieldType/User/Type.php
  eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/UserConverter.php
  eZ/Publish/Core/REST/Client/UserService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/AbstractServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/UserServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/UserService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/UserPasswordValidatorTest.php
  eZ/Publish/Core/Repository/UserService.php
  eZ/Publish/Core/Repository/Validator/UserPasswordValidator.php
  eZ/Publish/Core/SignalSlot/Tests/UserServiceTest.php
  eZ/Publish/Core/SignalSlot/UserService.php
  eZ/Publish/Core/settings/storage_engines/legacy/field_value_converters.yml
Labels: Feature, QA approved

#2484 EZP-29764: As a Developer I want to update single Content Type translation
  doc/bc/changes-7.4.md
  doc/upgrade/7.4.md
  eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
  eZ/Publish/API/Repository/Values/ContentType/ContentType.php
  eZ/Publish/Core/Persistence/Legacy/Content/Language/MaskGenerator.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Mapper.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Language/MaskGeneratorTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/ContentTypeHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/MapperTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/TestCase.php
  eZ/Publish/Core/Repository/ContentTypeService.php
  eZ/Publish/Core/Repository/Helper/ContentTypeDomainMapper.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/AbstractTestCase.php
  eZ/Publish/Core/settings/storage_engines/legacy/content_type.yml
  eZ/Publish/SPI/Persistence/Content/Type.php
Labels: QA approved, Ready for MERGE

#2494 EZP-29788: As a developer, I want to delete content type translation
  doc/bc/changes-7.4.md
  eZ/Publish/API/Repository/ContentTypeService.php
  eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
  eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php
  eZ/Publish/Core/Persistence/Cache/Tests/ContentTypeHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/MemoryCachingHandler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/ContentTypeHandlerTest.php
  eZ/Publish/Core/REST/Client/ContentTypeService.php
  eZ/Publish/Core/Repository/ContentTypeService.php
  eZ/Publish/Core/Repository/SiteAccessAware/ContentTypeService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/AbstractServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentTypeServiceTest.php
  eZ/Publish/Core/SignalSlot/ContentTypeService.php
  eZ/Publish/Core/SignalSlot/Signal/ContentTypeService/RemoveContentTypeDraftTranslationSignal.php
  eZ/Publish/Core/SignalSlot/Tests/ContentTypeServiceTest.php
  eZ/Publish/SPI/Persistence/Content/Type/Handler.php
Labels: Ready for QA

#2503 EZP-29887: Added default view template for embed-inline View type
  eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/embed_inline.html.twig
Labels: Bug, Ready for review

#2431 EZP-29451: As an Administrator I want to have a CLI command for database cleanup
  eZ/Bundle/EzPublishCoreBundle/Command/CleanupVersionsCommand.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
Labels: QA approved

#2507 EZP-29932: As a Developer I want list of Languages based on User's browser settings
  eZ/Bundle/EzPublishCoreBundle/Resources/config/locale.yml
  eZ/Publish/Core/MVC/Symfony/Locale/Tests/UserLanguagePreferenceProviderTest.php
  eZ/Publish/Core/MVC/Symfony/Locale/UserLanguagePreferenceProvider.php
  eZ/Publish/Core/MVC/Symfony/Locale/UserLanguagePreferenceProviderInterface.php
  eZ/Publish/Core/Repository/Values/MultiLanguageDescriptionTrait.php
  eZ/Publish/Core/Repository/Values/MultiLanguageNameTrait.php
Labels: QA approved, Ready for MERGE, Ready for QA
