Repository ezsystems/ezpublish-kernel, pull requests merged in 2018-10, with the labels that each got.

#2205 EZP-29531: Do not render layout when rendering selection and relation items
  eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/fielddefinition_settings.html.twig
Labels: Needs JIRA issue

#2461 EZP-29684: Remove the hyphen from the "E-mail" in whole application
  eZ/Bundle/EzPublishCoreBundle/Resources/translations/fieldtypes.en.xlf
Labels: QA approved, Ready for review

#2462 EZP-29695: Option "Default content availability" on content types not working
  eZ/Publish/Core/Repository/ContentService.php
Labels: QA approved

#2447 EZP-29586: Content copied by another user is still owned by original creator
  eZ/Publish/API/Repository/Tests/BaseContentServiceTest.php
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/Core/Persistence/Cache/ContentHandler.php
  eZ/Publish/Core/Persistence/Cache/LocationHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Handler.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/LocationService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
Labels: Ready for QA

#2459 EZP-29721: Broken URL alias history is not restored after regenerating aliases
  eZ/Bundle/EzPublishCoreBundle/Command/RegenerateUrlAliasesCommand.php
  eZ/Publish/API/Repository/Tests/BaseTest.php
  eZ/Publish/API/Repository/Tests/URLAliasServiceTest.php
  eZ/Publish/Core/Persistence/Cache/UrlAliasHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Mapper.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasMapperTest.php
  eZ/Publish/Core/Repository/URLAliasService.php
  eZ/Publish/SPI/Persistence/Content/UrlAlias/Handler.php
Labels: QA approved
