Repository ezsystems/ezpublish-kernel, pull requests merged in 2018-07, with the labels that each got.

#2389 EZEE-2176: Fixed fail of the db schema update script when the eznotification table already exists
  data/update/mysql/dbupdate-7.1.0-to-7.2.0.sql
  data/update/postgres/dbupdate-7.1.0-to-7.2.0.sql
Labels: QA approved

#2393 [PHPUnit] Fixed configuration files to conform to XSD schema
  phpunit-integration-legacy-elasticsearch.xml
  phpunit-integration-legacy-solr.xml
  phpunit-integration-legacy.xml
  phpunit-integration-rest-json.xml
  phpunit-integration-rest-xml.xml
Labels: Ready for review

#2387 EZP-29396: Cache size blows up when using Redis, which is what we recommend now
  .travis.yml
  eZ/Bundle/EzPublishCoreBundle/Cache/Driver/DriverFactory.php
  eZ/Bundle/EzPublishCoreBundle/Cache/Driver/Redis/RedisIgbinary.php
  eZ/Bundle/EzPublishCoreBundle/Cache/Driver/Redis/RedisIgbinaryLzf.php
  eZ/Bundle/EzPublishCoreBundle/Cache/Driver/Redis/RedisSerializeLzf.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/StashPass.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/cache.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/StashPassTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
  eZ/Publish/API/Repository/Tests/Regression/EZP22958SearchSubtreePathstringFormatTest.php
  eZ/Publish/API/Repository/Tests/SetupFactory/Legacy.php
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/ObjectStateLimitationTest.php
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/OwnerLimitationTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/Helpers/IntegrationTestCacheServiceDecorator.php
  eZ/Publish/Core/settings/containerBuilder.php
  eZ/Publish/Core/settings/tests/integration_legacy.yml
  eZ/Publish/Core/settings/tests/integration_legacy_core.yml
  eZ/Publish/Core/settings/tests/integration_legacy_elasticsearch.yml
Labels: Ready for QA

#2400 EZP-29447: Fix number of pending notifications for current user
  eZ/Publish/Core/Persistence/Legacy/Notification/Gateway/DoctrineDatabase.php
Labels: QA approved, Ready for review

#2405 EZP-29421: Contents of file field are lost if object is saved before publishing
  eZ/Publish/Core/FieldType/BinaryBase/BinaryBaseStorage.php
Labels: QA approved, Ready for review
