Repository ezsystems/ezpublish-kernel, pull requests merged in 2018-05, with the labels that each got.

#2313 EZP-29113: UserHandler::assignRole should invalidate `location-path-` tags
  eZ/Publish/API/Repository/Tests/RoleServiceTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/UserHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/UserHandler.php
Labels: Ready for QA

#2309 EZP-29062: Implemented ezplatform:copy-subtree command
  eZ/Bundle/EzPublishCoreBundle/Command/CopySubtreeCommand.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
Labels: QA approved, Ready for review

#2306 EZP-28811: As an Administrator I want to decide which pattern should be used in URL generation
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/SlugConverterConfigurationPass.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/SlugConverterConfigurationPassTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/SlugConverter.php
  eZ/Publish/Core/settings/storage_engines/common.yml
Labels: Ready for review

#2324 EZP-29146: As a developer, I want a API to manage bookmarks
  eZ/Publish/API/Repository/BookmarkService.php
  eZ/Publish/API/Repository/Repository.php
  eZ/Publish/API/Repository/Tests/BookmarkServiceTest.php
  eZ/Publish/API/Repository/Values/Bookmark/BookmarkList.php
  eZ/Publish/Core/Persistence/Cache/BookmarkHandler.php
  eZ/Publish/Core/Persistence/Cache/Handler.php
  eZ/Publish/Core/Persistence/Cache/Tests/AbstractBaseHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/AbstractCacheHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/BookmarkHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Bookmark/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Bookmark/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Bookmark/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Bookmark/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Bookmark/Mapper.php
  eZ/Publish/Core/Persistence/Legacy/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Bookmark/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Bookmark/HandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Bookmark/MapperTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Bookmark/_fixtures/bookmarks.php
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.mysql.sql
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.pgsql.sql
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.sqlite.sql
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/setval.pgsql.sql
  eZ/Publish/Core/REST/Client/Repository.php
  eZ/Publish/Core/Repository/BookmarkService.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/Tests/Service/Integration/Legacy/_fixtures/clean_ezdemo_47_dump.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/BookmarkTest.php
  eZ/Publish/Core/SignalSlot/BookmarkService.php
  eZ/Publish/Core/SignalSlot/Repository.php
  eZ/Publish/Core/SignalSlot/Signal/BookmarkService/CreateBookmarkSignal.php
  eZ/Publish/Core/SignalSlot/Signal/BookmarkService/DeleteBookmarkSignal.php
  eZ/Publish/Core/SignalSlot/Tests/BookmarkServiceTest.php
  eZ/Publish/Core/SignalSlot/Tests/RepositoryTest.php
  eZ/Publish/Core/settings/repository.yml
  eZ/Publish/Core/settings/repository/inner.yml
  eZ/Publish/Core/settings/repository/signalslot.yml
  eZ/Publish/Core/settings/storage_engines/cache.yml
  eZ/Publish/Core/settings/storage_engines/legacy.yml
  eZ/Publish/Core/settings/storage_engines/legacy/bookmark.yml
  eZ/Publish/Core/settings/storage_engines/shortcuts.yml
  eZ/Publish/SPI/Persistence/Bookmark/Bookmark.php
  eZ/Publish/SPI/Persistence/Bookmark/CreateStruct.php
  eZ/Publish/SPI/Persistence/Bookmark/Handler.php
  eZ/Publish/SPI/Persistence/Handler.php
  phpunit-integration-legacy.xml
Labels: Ready for review

#2326 EZP-29110: Changing tables charset to utf8mb4 result in "Specified key is too long" errors
  data/mysql/dfs_schema.sql
  data/mysql/schema.sql
  data/update/mysql/dbupdate-7.1.0-to-7.2.0-dfs.sql
  data/update/mysql/dbupdate-7.1.0-to-7.2.0.sql
  doc/upgrade/7.2.md
Labels: QA approved

#2311 EZP-29137: As a developer, I want to replace missing images with placeholders
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/PlaceholderProviderPass.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php
  eZ/Bundle/EzPublishCoreBundle/Imagine/PlaceholderAliasGenerator.php
  eZ/Bundle/EzPublishCoreBundle/Imagine/PlaceholderAliasGeneratorConfigurator.php
  eZ/Bundle/EzPublishCoreBundle/Imagine/PlaceholderProvider.php
  eZ/Bundle/EzPublishCoreBundle/Imagine/PlaceholderProvider/GenericProvider.php
  eZ/Bundle/EzPublishCoreBundle/Imagine/PlaceholderProvider/RemoteProvider.php
  eZ/Bundle/EzPublishCoreBundle/Imagine/PlaceholderProviderRegistry.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/PlaceholderProviderPassTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/PlaceholderAliasGeneratorConfiguratorTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/PlaceholderAliasGeneratorTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/PlaceholderProvider/GenericProviderTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/PlaceholderProviderRegistryTest.php
Labels: QA approved

#2339 EZP-29206: MySQL deadlock errors happen when concurrently moving subtree
  data/mysql/schema.sql
  data/update/mysql/dbupdate-6.7.7-to-6.7.8.sql
  data/update/postgres/dbupdate-6.7.7-to-6.7.8.sql
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.mysql.sql
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.pgsql.sql
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.sqlite.sql
Labels: QA approved
