Repository ezsystems/ezpublish-kernel, pull requests merged in 2018-03, with the labels that each got.

#2257 EZP-28860: Limit building views with view builders to string controllers
  eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/ViewControllerListenerTest.php
  eZ/Publish/Core/MVC/Symfony/View/Builder/Registry/ControllerMatch.php
Labels: Ready for merge

#2254 EZP-28853: Add VersionInfo to persistence cache
  eZ/Publish/Core/Persistence/Cache/ContentHandler.php
  eZ/Publish/Core/Persistence/Cache/Tests/ContentHandlerTest.php
Labels: Ready for merge

#2262 EZP-28883: Removing Translation from Draft corrupts all Url Aliases for the removed Translation
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php
Labels: QA approved

#2258 EZP-28585: SPI cache purge for related content when URL is updated
  eZ/Publish/Core/Persistence/Cache/Tests/URLHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/URLHandler.php
Labels: Ready for merge

#2263 EZP-28848: Add relation cache tags to default relation fields
  eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/content.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/content_denied.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/content_inline.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/content_inline_denied.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/location.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/location_denied.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/location_inline.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/embed/location_inline_denied.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
Labels: Ready for QA

#2260 EZP-28070: Cleaning up temporary files created by BinaryInputProcessor::preProcessValueHash
  eZ/Publish/Core/REST/Common/FieldTypeProcessor/BinaryInputProcessor.php
Labels: Ready for QA

#2270 EZP-28917: As a Developer I want API to manipulate User Tokens
  eZ/Publish/API/Repository/Tests/UserServiceTest.php
  eZ/Publish/API/Repository/UserService.php
  eZ/Publish/API/Repository/Values/User/UserTokenUpdateStruct.php
  eZ/Publish/Core/Persistence/Cache/Tests/UserHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/UserHandler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/User/UserHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/User/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/User/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/User/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/User/Handler.php
  eZ/Publish/Core/Repository/UserService.php
  eZ/Publish/Core/SignalSlot/Signal/UserService/UpdateUserTokenSignal.php
  eZ/Publish/Core/SignalSlot/UserService.php
  eZ/Publish/SPI/Persistence/User/Handler.php
  eZ/Publish/SPI/Persistence/User/UserTokenUpdateStruct.php
Labels: Ready for review

#2253 EZP-28836: Skipping validation of non-modified fields when content is updated
  eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php
  eZ/Publish/API/Repository/Tests/BaseTest.php
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/API/Repository/Tests/FieldType/BaseIntegrationTest.php
  eZ/Publish/API/Repository/Tests/FieldType/RichTextIntegrationTest.php
  eZ/Publish/API/Repository/Tests/PHPUnitConstraint/ValidationErrorOccurs.php
  eZ/Publish/Core/Base/Container/ApiLoader/RepositoryFactory.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/Helper/RelationProcessor.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/RelationProcessorTest.php
  eZ/Publish/Core/settings/repository.yml
Labels: Ready for QA

#2279 EZP-28902: Creating a user with existing username results in Internal Server Error.
  eZ/Publish/Core/FieldType/Tests/UserTest.php
  eZ/Publish/Core/FieldType/User/Type.php
  eZ/Publish/Core/settings/fieldtypes.yml
  eZ/Publish/SPI/Tests/FieldType/UserIntegrationTest.php
Labels: Ready for QA, Ready for review

#2282 EZP-28962: Fixed REST OPTIONS Controller name
  eZ/Bundle/EzPublishRestBundle/Routing/OptionsLoader/Mapper.php
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/HttpOptionsTest.php
  eZ/Bundle/EzPublishRestBundle/Tests/Routing/OptionsLoader/MapperTest.php
  eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/Options.php
Labels: QA approved

#2283 EZP-28934: Incorrect variable in policy check context
  eZ/Publish/Core/Repository/LocationService.php
Labels: QA approved

#2259 EZP-28585: Added flag to URLService\UpdateUrlSignal indicating that URL address was changed
  eZ/Publish/Core/SignalSlot/Signal/URLService/UpdateUrlSignal.php
  eZ/Publish/Core/SignalSlot/Tests/URLServiceTest.php
  eZ/Publish/Core/SignalSlot/URLService.php
Labels: Needs Tests

#2291 EZP-28959: Prevent publishing errors on pre-existing, undefined Custom Tags
  eZ/Publish/API/Repository/Tests/FieldType/RichTextIntegrationTest.php
  eZ/Publish/Core/FieldType/RichText/CustomTagsValidator.php
  eZ/Publish/Core/FieldType/Tests/RichText/CustomTagsValidatorTest.php
Labels: QA approved

#2288 EZP-28680: Error 500 after restoring related item in another location
  eZ/Publish/Core/Persistence/Cache/Tests/TrashHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/TrashHandler.php
Labels: QA approved

#2278 EZP-28554: Error 400 after filling Text field in URL field type
  eZ/Publish/Core/FieldType/Url/Type.php
Labels: QA approved
