Repository ezsystems/ezpublish-kernel, pull requests merged in 2018-09, with the labels that each got.

#2433 EZP-29577: As a developer, I want a API to count user preferences
  eZ/Publish/API/Repository/Tests/UserPreferenceServiceTest.php
  eZ/Publish/API/Repository/UserPreferenceService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/UserPreferenceTest.php
  eZ/Publish/Core/SignalSlot/Tests/UserPreferenceServiceTest.php
  eZ/Publish/Core/SignalSlot/UserPreferenceService.php
Labels: Ready for review

#2432 DEMO-201: User is unable to create Article from COTF
  eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/AuthorConverter.php
Labels: Ready for merge

#2440 [REST Tests] Aligned code with Buzz v0.17.2
  composer.json
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/SessionTest.php
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/TestCase.php
Labels: Ready for merge

#2418 EZP-29504 : add siteaccess parameter to ezplatform:reindex
  eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php
Labels: Ready for QA

#2413 EZP-29474: Fix wrong usage of hasAccess in repository
  eZ/Publish/API/Repository/PermissionResolver.php
  eZ/Publish/Core/Limitation/SubtreeLimitationType.php
  eZ/Publish/Core/Limitation/Tests/SubtreeLimitationTypeTest.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/ContentTypeService.php
  eZ/Publish/Core/Repository/LanguageService.php
  eZ/Publish/Core/Repository/ObjectStateService.php
  eZ/Publish/Core/Repository/SectionService.php
  eZ/Publish/Core/Repository/Tests/Service/Integration/TrashBase.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/UrlWildcardTest.php
  eZ/Publish/Core/Repository/TrashService.php
  eZ/Publish/Core/Repository/URLWildcardService.php
Labels: Ready for QA

#2427 EZP-29554: As an editor, I want to be able to apply custom styles to part of my text
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/FieldType/RichText.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/style/default.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/style/default_inline.html.twig
  eZ/Publish/Core/FieldType/RichText/Converter/Render/Style.php
  eZ/Publish/Core/FieldType/RichText/RendererInterface.php
  eZ/Publish/Core/FieldType/RichText/Resources/schemas/docbook/ezpublish.rng
  eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
  eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
  eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
  eZ/Publish/Core/FieldType/Tests/RichText/Converter/Render/EmbedTest.php
  eZ/Publish/Core/FieldType/Tests/RichText/Converter/Render/StyleTest.php
  eZ/Publish/Core/FieldType/Tests/RichText/Converter/Render/TemplateTest.php
  eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/docbook/031-ezstyle.xml
  eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/docbook/032-ezstyleinline.xml
  eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/031-ezstyle.xml
  eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/032-ezstyleinline.xml
  eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/output/031-ezstyle.xml
  eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/output/032-ezstyleinline.xml
  eZ/Publish/Core/MVC/Symfony/FieldType/RichText/Renderer.php
  eZ/Publish/Core/MVC/Symfony/FieldType/Tests/RichText/RendererTest.php
Labels: QA approved

#2423 [6.7] EZP-29139: RegenerateUrlAliasesCommand should keep historized Url Aliases
  data/cleandata.sql
  eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php
  eZ/Bundle/EzPublishCoreBundle/Command/RegenerateUrlAliasesCommand.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/commands.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/papi.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
  eZ/Bundle/EzPublishMigrationBundle/Command/LegacyStorage/RegenerateUrlAliasesCommand.php
  eZ/Publish/API/Repository/ContentService.php
  eZ/Publish/API/Repository/LocationService.php
  eZ/Publish/API/Repository/Tests/BaseTest.php
  eZ/Publish/API/Repository/Tests/Common/SlugConverter.php
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/API/Repository/Tests/SetupFactory/Legacy.php
  eZ/Publish/API/Repository/Tests/SetupFactory/LegacyElasticsearch.php
  eZ/Publish/API/Repository/Tests/URLAliasServiceTest.php
  eZ/Publish/API/Repository/URLAliasService.php
  eZ/Publish/API/Repository/Values/Content/Language.php
  eZ/Publish/Core/Persistence/Cache/ContentHandler.php
  eZ/Publish/Core/Persistence/Cache/LocationHandler.php
  eZ/Publish/Core/Persistence/Cache/UrlAliasHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Language/MaskGenerator.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Mapper.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/TestCase.php
  eZ/Publish/Core/REST/Client/ContentService.php
  eZ/Publish/Core/REST/Client/LocationService.php
  eZ/Publish/Core/REST/Client/URLAliasService.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/Helper/DomainMapper.php
  eZ/Publish/Core/Repository/LocationService.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/UrlAliasTest.php
  eZ/Publish/Core/Repository/URLAliasService.php
  eZ/Publish/Core/SignalSlot/ContentService.php
  eZ/Publish/Core/SignalSlot/LocationService.php
  eZ/Publish/Core/SignalSlot/URLAliasService.php
  eZ/Publish/Core/settings/storage_engines/legacy/content.yml
  eZ/Publish/Core/settings/storage_engines/legacy/url_alias.yml
  eZ/Publish/Core/settings/tests/common.yml
  eZ/Publish/Core/settings/tests/override.yml
  eZ/Publish/SPI/Persistence/Content/Handler.php
  eZ/Publish/SPI/Persistence/Content/Location/Handler.php
  eZ/Publish/SPI/Persistence/Content/UrlAlias/Handler.php
Labels: Ready for QA

#2434 EZP-29234: As a developer, I want to read about customizing REST API response
  eZ/Publish/Core/REST/Common/Output/Generator.php
  eZ/Publish/Core/REST/Common/Output/Generator/Json.php
  eZ/Publish/Core/REST/Common/Output/Generator/Xml.php
Labels: Ready for review

#2451 EZP-29508: As an editor I want to manage ALT field with an image asset field type
  eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
  eZ/Publish/Core/FieldType/ImageAsset/Type.php
  eZ/Publish/Core/FieldType/ImageAsset/Value.php
  eZ/Publish/Core/FieldType/Tests/ImageAssetTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/ImageAssetConverter.php
  eZ/Publish/SPI/Tests/FieldType/ImageAssetIntegrationTest.php
Labels: Ready for QA

#2428 EZP-29518: ContentType option "Default field for sorting children" has no effect on new created objects
  eZ/Publish/Core/REST/Client/LocationService.php
  eZ/Publish/Core/REST/Server/Controller/Content.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/LocationService.php
  eZ/Publish/Core/SignalSlot/LocationService.php
  eZ/Publish/Core/SignalSlot/Tests/LocationServiceTest.php
Labels: QA approved

#2409 EZP-29408: Implemented Asset Relation type
  eZ/Publish/API/Repository/Values/Content/Relation.php
  eZ/Publish/Core/FieldType/ImageAsset/Type.php
  eZ/Publish/Core/FieldType/Tests/ImageAssetTest.php
  eZ/Publish/Core/Persistence/Cache/ContentHandler.php
  eZ/Publish/Core/Persistence/Cache/Tests/ContentHandlerTest.php
  eZ/Publish/Core/REST/Client/Input/Parser/Relation.php
  eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/RestRelation.php
  eZ/Publish/Core/Repository/Helper/RelationProcessor.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/RelationProcessorTest.php
  eZ/Publish/SPI/Persistence/Content/Relation.php
Labels: Ready for QA
