Repository ezsystems/ezpublish-kernel, pull requests merged in 2018-08, with the labels that each got.

#2377 EZP-29083: Error after trying to delete role assignment
  eZ/Publish/API/Repository/Tests/RoleServiceTest.php
  eZ/Publish/Core/Persistence/Cache/UserHandler.php
Labels: QA approved

#2406 EZP-29462: Improve docblock and return type hint for ContentView::getLocation method
  eZ/Publish/Core/MVC/Symfony/View/ContentView.php
Labels: QA approved, Ready for review

#2392 EZP-29290: As an Editor, I want to have preconfigured "Author" section while creating the content
  eZ/Bundle/EzPublishCoreBundle/Resources/views/fielddefinition_settings.html.twig
  eZ/Bundle/EzPublishRestBundle/Resources/config/services.yml
  eZ/Publish/API/Repository/Tests/FieldType/AuthorIntegrationTest.php
  eZ/Publish/Core/FieldType/Author/Type.php
  eZ/Publish/Core/FieldType/Tests/AuthorTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/AuthorConverter.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/FieldValue/Converter/AuthorTest.php
  eZ/Publish/Core/REST/Common/FieldTypeProcessor/AuthorProcessor.php
  eZ/Publish/Core/REST/Common/Tests/FieldTypeProcessor/AuthorProcessorTest.php
  eZ/Publish/SPI/Tests/FieldType/AuthorIntegrationTest.php
Labels: Ready for QA, Ready for review

#2420 EZP-28888: Custom cache_service_name can not be set from siteaccess group
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/Common.php
Labels: Ready for QA

#2417 EZP-29290: Author Field Type prefilled with empty value by default
  data/mysql/cleandata.sql
  eZ/Publish/API/Repository/Tests/FieldType/AuthorIntegrationTest.php
  eZ/Publish/Core/FieldType/Author/Type.php
  eZ/Publish/Core/FieldType/Tests/AuthorTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/AuthorConverter.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/FieldValue/Converter/AuthorTest.php
  eZ/Publish/Core/REST/Common/FieldTypeProcessor/AuthorProcessor.php
  eZ/Publish/Core/REST/Common/Tests/FieldTypeProcessor/AuthorProcessorTest.php
  eZ/Publish/SPI/Tests/FieldType/AuthorIntegrationTest.php
Labels: QA approved, Ready for merge

#2426 EZP-29541: As a developer, I want a API to manage user preference
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Publish/API/Repository/Repository.php
  eZ/Publish/API/Repository/Tests/UserPreferenceServiceTest.php
  eZ/Publish/API/Repository/UserPreferenceService.php
  eZ/Publish/API/Repository/Values/UserPreference/UserPreference.php
  eZ/Publish/API/Repository/Values/UserPreference/UserPreferenceList.php
  eZ/Publish/API/Repository/Values/UserPreference/UserPreferenceSetStruct.php
  eZ/Publish/Core/Persistence/Cache/Handler.php
  eZ/Publish/Core/Persistence/Cache/Tests/AbstractBaseHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/UserPreferenceHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/UserPreferenceHandler.php
  eZ/Publish/Core/Persistence/Legacy/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/UserPreference/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/UserPreference/HandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/UserPreference/MapperTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/UserPreference/_fixtures/user_preferences.php
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.mysql.sql
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.pgsql.sql
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.sqlite.sql
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/setval.pgsql.sql
  eZ/Publish/Core/Persistence/Legacy/UserPreference/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/UserPreference/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/UserPreference/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/UserPreference/Handler.php
  eZ/Publish/Core/Persistence/Legacy/UserPreference/Mapper.php
  eZ/Publish/Core/REST/Client/Repository.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/SiteAccessAware/Repository.php
  eZ/Publish/Core/Repository/Tests/Service/Integration/Legacy/_fixtures/clean_ezdemo_47_dump.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/UserPreferenceTest.php
  eZ/Publish/Core/Repository/UserPreferenceService.php
  eZ/Publish/Core/SignalSlot/Repository.php
  eZ/Publish/Core/SignalSlot/Signal/UserPreferenceService/UserPreferenceSetSignal.php
  eZ/Publish/Core/SignalSlot/Tests/RepositoryTest.php
  eZ/Publish/Core/SignalSlot/Tests/UserPreferenceServiceTest.php
  eZ/Publish/Core/SignalSlot/UserPreferenceService.php
  eZ/Publish/Core/settings/repository.yml
  eZ/Publish/Core/settings/repository/inner.yml
  eZ/Publish/Core/settings/repository/signalslot.yml
  eZ/Publish/Core/settings/storage_engines/cache.yml
  eZ/Publish/Core/settings/storage_engines/legacy.yml
  eZ/Publish/Core/settings/storage_engines/legacy/user_preference.yml
  eZ/Publish/Core/settings/storage_engines/shortcuts.yml
  eZ/Publish/Core/settings/user_preference.yml
  eZ/Publish/SPI/Persistence/Handler.php
  eZ/Publish/SPI/Persistence/UserPreference/Handler.php
  eZ/Publish/SPI/Persistence/UserPreference/UserPreference.php
  eZ/Publish/SPI/Persistence/UserPreference/UserPreferenceSetStruct.php
  phpunit-integration-legacy.xml
Labels: Ready for QA, Ready for review
