Repository ezsystems/ezpublish-kernel, pull requests merged in 2018-04, with the labels that each got.

#2298 Fixed EZP-28882: Added newly created Version no. to CreateContentDraft Signal
  eZ/Publish/Core/SignalSlot/ContentService.php
  eZ/Publish/Core/SignalSlot/Signal/ContentService/CreateContentDraftSignal.php
  eZ/Publish/Core/SignalSlot/Tests/ContentServiceTest.php
Labels: Ready for review

#2295 Fixed EZP-29048: Aligned Behat BuzzDriver and Functional REST tests with PSR-7
  composer.json
  eZ/Bundle/EzPublishRestBundle/Features/Context/RestClient/BuzzDriver.php
  eZ/Bundle/EzPublishRestBundle/Features/Context/RestClient/DriverHelper.php
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/ContentTest.php
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/ContentTypeTest.php
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/LocationTest.php
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/ObjectStateTest.php
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/RoleTest.php
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/RootTest.php
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/SectionTest.php
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/SessionTest.php
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/TestCase.php
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/TrashTest.php
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/UrlAliasTest.php
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/UrlWildcardTest.php
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/UserTest.php
Labels: Needs rebase

#2292 EZP-28863: REST search error for searching fields with the same name
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/SearchViewTest.php
  eZ/Publish/API/Repository/Tests/SearchServiceTest.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/Field.php
Labels: Ready for QA

#2301 Fix EZP-28967: RichText FieldType removes line breaks inside table cells
  eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/edit/core.xsl
  eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/docbook/xhtml5/output/core.xsl
  eZ/Publish/Core/FieldType/RichText/Resources/stylesheets/xhtml5/edit/docbook.xsl
  eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/docbook/018-htmlTable.xml
  eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/ezxml/018-htmlTable.lossy.xml
  eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/edit/018-htmlTable.xml
  eZ/Publish/Core/FieldType/Tests/RichText/Converter/Xslt/_fixtures/xhtml5/output/018-htmlTable.xml
Labels: QA approved

#2305 Fixed EZEE-1864: Set ezpublish.cache_pool Service to be lazy
  eZ/Bundle/EzPublishCoreBundle/Resources/config/cache.yml
Labels: Ready for review, Siteaccess hell

#2308 EZP-28224: Change the way cache is cleared in Behat tests
  eZ/Bundle/EzPublishCoreBundle/Features/Context/YamlConfigurationContext.php
Labels: Ready for merge
