Repository ezsystems/ezpublish-kernel, pull requests merged in 2019-10, with the labels that each got.

#2774 EZP-30968: Added method to count the number of content's reverse relations
  eZ/Publish/API/Repository/ContentService.php
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/Core/Persistence/Cache/ContentHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
  eZ/Publish/Core/REST/Client/ContentService.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentServiceTest.php
  eZ/Publish/Core/SignalSlot/ContentService.php
  eZ/Publish/Core/SignalSlot/Tests/ContentServiceTest.php
  eZ/Publish/SPI/Persistence/Content/Handler.php
Labels: Bug, QA approved

#2784 [Travis] Bumped solr version in tests to 3.0
  bin/.travis/prepare_unittest.sh
Labels: Ready for review

#2777 EZP-30969: Added method to fetch paginated list of content's reverse relations
  eZ/Publish/API/Repository/ContentService.php
  eZ/Publish/API/Repository/Lists/UnauthorizedListItem.php
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/API/Repository/Values/Content/RelationList.php
  eZ/Publish/API/Repository/Values/Content/RelationList/Item/RelationListItem.php
  eZ/Publish/API/Repository/Values/Content/RelationList/Item/UnauthorizedRelationListItem.php
  eZ/Publish/API/Repository/Values/Content/RelationList/RelationListItemInterface.php
  eZ/Publish/Core/Persistence/Cache/ContentHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
  eZ/Publish/Core/REST/Client/ContentService.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
  eZ/Publish/Core/SignalSlot/ContentService.php
  eZ/Publish/SPI/Persistence/Content/Handler.php
Labels: Bug, QA approved

#2799 EZP-30823: Cleared in-memory cache pools during rollback
  eZ/Publish/Core/Persistence/Cache/Adapter/TransactionalInMemoryCacheAdapter.php
Labels: Bug

#2775 EZP-30835: Added support for Solr 7.7
  eZ/Publish/API/Repository/Tests/SearchServiceFulltextTest.php
  eZ/Publish/API/Repository/Tests/SearchServiceTranslationLanguageFallbackTest.php
Labels: Feature

#2797 Refactored Exception Conversion Content Gateway to use multi catch
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
Labels: Improvement

#2779 EZP-30899: Propagated ContentInfo::isHidden status when publishing
  eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php
  eZ/Publish/Core/Persistence/Legacy/Content/Mapper.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
  eZ/Publish/SPI/Persistence/Content/CreateStruct.php
Labels: Bug, QA approved, Ready for MERGE

#2788 EZP-30983: Prevented users from reusing old password
  eZ/Publish/API/Repository/Tests/FieldType/UserIntegrationTest.php
  eZ/Publish/API/Repository/Tests/UserServiceTest.php
  eZ/Publish/Core/FieldType/Tests/UserTest.php
  eZ/Publish/Core/FieldType/User/Type.php
  eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/UserConverter.php
  eZ/Publish/Core/Repository/UserService.php
Labels: Improvement, QA approved

#2803 Added password_updated_at column initialization to the 7.5.3 to 7.5.4 update scripts
  data/update/mysql/dbupdate-7.5.4-to-7.5.5.sql
  data/update/postgres/dbupdate-7.5.4-to-7.5.5.sql
Labels: Improvement

#2804 Fixed "Out of range value for 'password_update_at'" error during the 7.5.4 to 7.5.5 update script execution on Maria DB
  data/update/mysql/dbupdate-7.5.4-to-7.5.5.sql
Labels: Bug

#2802 [Travis] Updated Solr version in test matrix
  .travis.yml
Labels: Bug

#2798 EZP-30985: Replaced deprecated DI short factory syntax
  eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
  eZ/Publish/Core/settings/repository/autowire.yml
  eZ/Publish/Core/settings/search_engines/legacy/sort_clause_handlers_common.yml
  eZ/Publish/Core/settings/storage_engines/legacy.yml
  eZ/Publish/Core/settings/tests/integration_legacy.yml
Labels: Improvement

#2792 EZP-30624: Dropped obsolete data/demo_data.php
  data/demo_data.php
  doc/bc/changes-8.0.md
Labels: Improvement, Ready for MERGE

#2805 EZP-31006: Bumped hautelook/templated-uri-bundle to v3
  composer.json
Labels: Improvement

#2728 EZP-30827: Introduced strict types for ObjectStateService
  eZ/Publish/API/Repository/ObjectStateService.php
  eZ/Publish/API/Repository/Values/ObjectState/ObjectStateGroup.php
  eZ/Publish/Core/Event/ObjectStateService.php
  eZ/Publish/Core/Event/Tests/ObjectStateServiceTest.php
  eZ/Publish/Core/Repository/ObjectStateService.php
  eZ/Publish/Core/Repository/SiteAccessAware/ObjectStateService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/AbstractServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/ObjectStateServiceTest.php
  eZ/Publish/SPI/Repository/Decorator/ObjectStateServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/ObjectStateServiceDecoratorTest.php
Labels: DX, Improvement, QA approved

#2801 Added DatabaseException to replace RuntimeException occurrence in Gateway class
  eZ/Publish/Core/Base/Exceptions/DatabaseException.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
Labels: Improvement

#2810 Fixed PermissionCriterionResolver::getPermissionsCriterion calls without parameters
  eZ/Publish/Core/Repository/LocationService.php
Labels: Bug

#2813 EZP-30621: Dropped deprecated LegacyStorage Gateways
  doc/bc/changes-8.0.md
  eZ/Publish/Core/Base/Tests/Container/Compiler/Storage/ExternalStorageRegistryPassTest.php
  eZ/Publish/Core/FieldType/BinaryBase/BinaryBaseStorage/Gateway/LegacyStorage.php
  eZ/Publish/Core/FieldType/BinaryFile/BinaryFileStorage/Gateway/LegacyStorage.php
  eZ/Publish/Core/FieldType/Image/ImageStorage/Gateway/LegacyStorage.php
  eZ/Publish/Core/FieldType/Keyword/KeywordStorage/Gateway/LegacyStorage.php
  eZ/Publish/Core/FieldType/MapLocation/MapLocationStorage/Gateway/LegacyStorage.php
  eZ/Publish/Core/FieldType/Media/MediaStorage/Gateway/LegacyStorage.php
  eZ/Publish/Core/FieldType/Tests/Url/Gateway/LegacyStorageTest.php
  eZ/Publish/Core/FieldType/Url/UrlStorage/Gateway/LegacyStorage.php
  eZ/Publish/Core/FieldType/User/UserStorage/Gateway/LegacyStorage.php
  eZ/Publish/SPI/Tests/FieldType/MediaIntegrationTest.php
Labels: Improvement, Ready for MERGE

#2785 EZP-30971: Removed deprecated role service methods
  doc/bc/changes-8.0.md
  eZ/Publish/API/Repository/Events/Role/AddPolicyEvent.php
  eZ/Publish/API/Repository/Events/Role/BeforeAddPolicyEvent.php
  eZ/Publish/API/Repository/Events/Role/BeforeUnassignRoleFromUserEvent.php
  eZ/Publish/API/Repository/Events/Role/BeforeUnassignRoleFromUserGroupEvent.php
  eZ/Publish/API/Repository/Events/Role/BeforeUpdatePolicyEvent.php
  eZ/Publish/API/Repository/Events/Role/BeforeUpdateRoleEvent.php
  eZ/Publish/API/Repository/Events/Role/UnassignRoleFromUserEvent.php
  eZ/Publish/API/Repository/Events/Role/UnassignRoleFromUserGroupEvent.php
  eZ/Publish/API/Repository/Events/Role/UpdatePolicyEvent.php
  eZ/Publish/API/Repository/Events/Role/UpdateRoleEvent.php
  eZ/Publish/API/Repository/RoleService.php
  eZ/Publish/API/Repository/Tests/LocationServiceAuthorizationTest.php
  eZ/Publish/API/Repository/Tests/Regression/EZP21798Test.php
  eZ/Publish/API/Repository/Tests/Regression/EZP22840RoleLimitations.php
  eZ/Publish/API/Repository/Tests/RoleServiceAuthorizationTest.php
  eZ/Publish/API/Repository/Tests/RoleServiceTest.php
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/BaseLimitationTest.php
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/ContentTypeLimitationTest.php
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/LocationLimitationTest.php
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/NewObjectStateLimitationTest.php
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/NewSectionLimitationTest.php
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/ObjectStateLimitationTest.php
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/OwnerLimitationTest.php
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/ParentContentTypeLimitationTest.php
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/ParentDepthLimitationTest.php
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/ParentOwnerLimitationTest.php
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/ParentUserGroupLimitationTest.php
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/SectionLimitationTest.php
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/StatusLimitationTest.php
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/SubtreeLimitationTest.php
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/UserGroupLimitationTest.php
  eZ/Publish/API/Repository/Values/User/RoleDraft.php
  eZ/Publish/Core/Event/RoleService.php
  eZ/Publish/Core/Event/Tests/RoleServiceTest.php
  eZ/Publish/Core/Repository/RoleService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/RoleTest.php
  eZ/Publish/SPI/Repository/Decorator/RoleServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/RoleServiceDecoratorTest.php
Labels: QA approved, Ready for MERGE

#2809 EZP-31000: Added support to fragment identifier for URL alias generator
  eZ/Publish/Core/MVC/Symfony/Routing/Generator/UrlAliasGenerator.php
  eZ/Publish/Core/MVC/Symfony/Routing/Tests/UrlAliasGeneratorTest.php
Labels: Bug, QA approved, Ready for MERGE

#2816 EZP-31026: Fixed resolving of lang params in SA loadContentListByContentInfo
  eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentServiceTest.php
Labels: Bug

#2811 EZP-30885: Introduced strict types for LanguageService
  eZ/Publish/API/Repository/LanguageService.php
  eZ/Publish/API/Repository/Tests/LanguageServiceTest.php
  eZ/Publish/Core/Event/LanguageService.php
  eZ/Publish/Core/Repository/LanguageService.php
  eZ/Publish/Core/Repository/SiteAccessAware/LanguageService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/LanguageServiceTest.php
  eZ/Publish/SPI/Repository/Decorator/LanguageServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/LanguageServiceDecoratorTest.php
Labels: DX, Improvement, QA approved

#2812 EZP-30985: Replaced deprecated Twig classes
  eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/FileSystemTwigIntegrationTestCase.php
  eZ/Publish/Core/MVC/Symfony/Templating/Twig/FieldBlockRenderer.php
  eZ/Publish/Core/MVC/Symfony/Translation/TranslatableExceptionsFileVisitor.php
  eZ/Publish/Core/MVC/Symfony/Translation/ValidationErrorFileVisitor.php
Labels: Improvement, Ready for MERGE

#2814 [Travis] Disabled testing 6.7 and 6.13 branches on push / merge
  .travis.yml
Labels: Ready for review

#2817 Refactored Location's Exception Conversion
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/ExceptionConversion.php
Labels: Improvement, Ready for MERGE

#2820 Bookmark exception conversion
  eZ/Publish/Core/Persistence/Legacy/Bookmark/Gateway/ExceptionConversion.php
Labels: Improvement, Ready for MERGE, Ready for review

#2823 Refactored Language's Exception Conversion to use multi catch
  eZ/Publish/Core/Persistence/Legacy/Content/Language/Gateway/ExceptionConversion.php
Labels: Improvement, Ready for review

#2789 EZP-30985: Replaced deprecated ExtensionGuesser with MimeTypes class from symfony/mime
  composer.json
  eZ/Bundle/EzPublishCoreBundle/Command/ResizeOriginalImagesCommand.php
  eZ/Bundle/EzPublishCoreBundle/Imagine/BinaryLoader.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/BinaryLoaderTest.php
Labels: Improvement, QA approved

#2832 EZP-31050: Fixed resolving of lang params in SA ContentTypeService::loadContentTypeList
  eZ/Publish/Core/Repository/SiteAccessAware/ContentTypeService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentTypeServiceTest.php
Labels: Bug

#2793 EZP-30985: Removed usage of deprecated AdvancedUserInterface
  eZ/Bundle/EzPublishCoreBundle/Resources/config/security.yml
  eZ/Publish/Core/MVC/Symfony/Security/Tests/User/ProviderTest.php
  eZ/Publish/Core/MVC/Symfony/Security/Tests/UserCheckerTest.php
  eZ/Publish/Core/MVC/Symfony/Security/Tests/UserTest.php
  eZ/Publish/Core/MVC/Symfony/Security/Tests/UserWrappedTest.php
  eZ/Publish/Core/MVC/Symfony/Security/User.php
  eZ/Publish/Core/MVC/Symfony/Security/User/Provider.php
  eZ/Publish/Core/MVC/Symfony/Security/UserChecker.php
  eZ/Publish/Core/MVC/Symfony/Security/UserInterface.php
  eZ/Publish/Core/MVC/Symfony/Security/UserWrapped.php
Labels: Improvement, QA approved

#2822 EZP-31029: Introduced strict types for RoleService
  eZ/Publish/API/Repository/RoleService.php
  eZ/Publish/Core/Event/RoleService.php
  eZ/Publish/Core/Repository/RoleService.php
  eZ/Publish/SPI/Repository/Decorator/RoleServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/RoleServiceDecoratorTest.php
Labels: DX, Improvement, QA approved, Ready for review

#2831 EZP-30985: Replaced usage of deprecated transchoice Twig function
  eZ/Bundle/EzPublishCoreBundle/Resources/translations/fielddefinition.en.xlf
  eZ/Bundle/EzPublishCoreBundle/Resources/views/fielddefinition_settings.html.twig
Labels: Improvement

#2833 EZP-31053: Prioritized languages should be respected by Content::getContentType
  eZ/Publish/API/Repository/Tests/ContentServiceAuthorizationTest.php
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/Core/Repository/ContentService.php
Labels: Bug

#2834 EZP-30689: Registered Query Types for automatic configuration
  doc/bc/changes-8.0.md
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/QueryTypePass.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Bundle/EzPublishCoreBundle/Features/Context/QueryControllerContext.php
  eZ/Bundle/EzPublishCoreBundle/Features/QueryController/query_controller.feature
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/QueryTypePassTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
Labels: Bug, Improvement, Ready for MERGE

#2783 EZP-30988: Implemented Section filtering URL Query Criterion
  eZ/Publish/API/Repository/Tests/URLServiceTest.php
  eZ/Publish/API/Repository/Values/URL/Query/Criterion/SectionId.php
  eZ/Publish/API/Repository/Values/URL/Query/Criterion/SectionIdentifier.php
  eZ/Publish/Core/Persistence/Legacy/Tests/URL/Query/CriterionHandler/VisibleOnlyTest.php
  eZ/Publish/Core/Persistence/Legacy/URL/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/Base.php
  eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/SectionId.php
  eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/SectionIdentifier.php
  eZ/Publish/Core/Persistence/Legacy/URL/Query/CriterionHandler/VisibleOnly.php
  eZ/Publish/Core/settings/storage_engines/legacy/url_criterion_handlers.yml
Labels: Feature, QA approved

#2815 EZP-31023: Fixed root location loading with prioritized languages
  eZ/Publish/API/Repository/Tests/LocationServiceTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
Labels: Bug, QA approved

#2651 EZP-30567: Impl. ez_query:pagingQueryAction to handle pagination
  eZ/Bundle/EzPublishCoreBundle/Features/Context/QueryControllerContext.php
  eZ/Bundle/EzPublishCoreBundle/Features/QueryController/query_controller.feature
  eZ/Publish/Core/MVC/Symfony/Controller/Content/QueryController.php
Labels: Feature, QA approved

#2837 EZP-24520: Impl. IteratorAggregate for SearchResult and LocationList
  eZ/Publish/API/Repository/Values/Content/LocationList.php
  eZ/Publish/API/Repository/Values/Content/Search/SearchResult.php
Labels: DX, Feature

#2842 EZP-30865: Fixed creating the same custom URL alias for different language
  eZ/Publish/API/Repository/Tests/URLAliasServiceTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
Labels: Bug, QA approved
