Repository ezsystems/ezpublish-kernel, pull requests merged in 2019-03, with the labels that each got.

#2550 EZP-30149: Unified eznotification table definition for MySQL and PostgreSQL
  data/mysql/schema.sql
  data/update/mysql/dbupdate-7.4.0-to-7.5.0.sql
  data/update/postgres/dbupdate-7.4.0-to-7.5.0.sql
  eZ/Publish/Core/Persistence/Legacy/Notification/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.pgsql.sql
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.sqlite.sql
Labels: Improvement, QA approved, Ready for MERGE, Ready for review

#2547 EZP-30144: Add paths option for translator service instead of injecting files into the translator service paths
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/TranslationCollectorPass.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/TranslationCollectorPassTest.php
Labels: Ready for review

#2551 EZP-30204: Checked if orig URL Alias is correct when repairing arch.
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php
Labels: QA approved, Ready for MERGE

#2539 EZP-29891: "Add Location" button is greyed out although editor has sufficient rights
  eZ/Publish/API/Repository/Tests/PermissionResolverTest.php
  eZ/Publish/Core/Limitation/ParentContentTypeLimitationType.php
  eZ/Publish/Core/Limitation/Tests/ParentContentTypeLimitationTypeTest.php
  phpunit-integration-legacy.xml
Labels: Bug, QA approved, Ready for review

#2422 EZP-29279: Fix value displayed by the Date Field Type being affected by server time zone
  eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
Labels: Ready for QA

#2499 EZP-29279: Script converting ezdate & ezdatetime timestamps to UTC
  eZ/Bundle/EzPublishCoreBundle/Command/UpdateTimestampsToUTCCommand.php
Labels: Ready for QA

#2552 EZP-29938: Modified CleanInstaller to use SchemaBuilder
  composer.json
  data/postgresql/cleandata.sql
  eZ/Bundle/EzPublishCoreBundle/Resources/config/storage/legacy/schema.yaml
  eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php
  eZ/Bundle/PlatformInstallerBundle/src/DependencyInjection/Compiler/SchemaBuilderInstallerPass.php
  eZ/Bundle/PlatformInstallerBundle/src/Event/Subscriber/BuildSchemaSubscriber.php
  eZ/Bundle/PlatformInstallerBundle/src/EzSystemsPlatformInstallerBundle.php
  eZ/Bundle/PlatformInstallerBundle/src/Installer/CleanInstaller.php
  eZ/Bundle/PlatformInstallerBundle/src/Installer/CoreInstaller.php
  eZ/Bundle/PlatformInstallerBundle/src/Installer/DbBasedInstaller.php
  eZ/Bundle/PlatformInstallerBundle/src/Installer/Installer.php
  eZ/Bundle/PlatformInstallerBundle/src/Resources/config/services.yml
Labels: QA approved, Ready for MERGE

#2559 [Tests] Refactored Twig runtime error checking to be less strict
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/FileSystemTwigIntegrationTestCase.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/_fixtures/field_rendering_functions/ez_render_field_exception.test
Labels: Bug, Ready for review

#2561 EZP-30147: Fixed moving a subtree with invisible items
  eZ/Publish/API/Repository/Tests/LocationServiceTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
Labels: Bug, QA approved, Ready for review

#2556 EZP-30202: Error to preview / publish content item with empty Image Asset field
  eZ/Publish/Core/MVC/Symfony/FieldType/ImageAsset/ParameterProvider.php
  eZ/Publish/Core/MVC/Symfony/FieldType/Tests/ImageAsset/ParameterProviderTest.php
Labels: Bug, Ready for QA

#2563 EZP-30107: Name of Content Item is not updated after changing the main language
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/API/Repository/Values/Content/ContentMetadataUpdateStruct.php
  eZ/Publish/Core/Repository/ContentService.php
Labels: QA approved

#2537 EZP-30111: [REST] Added Content status to RestContent output
  doc/specifications/rest/REST-API-V2.rst
  doc/specifications/rest/xsd/Content.xsd
  eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/RestContent.php
  eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/RestContentTest.php
Labels: Feature, QA approved, Ready for MERGE

#2560 EZP-30300: Methods buildLocationWithContent and buildLocation should behave exactly the same in case of tree root
  eZ/Publish/Core/Repository/Helper/DomainMapper.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/DomainMapperTest.php
Labels: Bug, QA approved

#2553 EZP-29659: As a v2 Cluster Admin & Developer I want support for InMemory SPI cache
  eZ/Bundle/EzPublishDebugBundle/Collector/PersistenceCacheCollector.php
  eZ/Bundle/EzPublishDebugBundle/Resources/views/Profiler/layout.html.twig
  eZ/Bundle/EzPublishDebugBundle/Resources/views/Profiler/persistence/panel.html.twig
  eZ/Bundle/EzPublishDebugBundle/Resources/views/Profiler/persistence/toolbar.html.twig
  eZ/Publish/API/Repository/Tests/LanguageServiceTest.php
  eZ/Publish/Core/Persistence/Cache/AbstractInMemoryHandler.php
  eZ/Publish/Core/Persistence/Cache/ContentLanguageHandler.php
  eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php
  eZ/Publish/Core/Persistence/Cache/InMemory/InMemoryCache.php
  eZ/Publish/Core/Persistence/Cache/InMemory/README.md
  eZ/Publish/Core/Persistence/Cache/PersistenceLogger.php
  eZ/Publish/Core/Persistence/Cache/Tests/AbstractBaseHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/AbstractInMemoryCacheHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/ContentLanguageHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/ContentTypeHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/InMemory/InMemoryCacheTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/PersistenceLoggerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/UserHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/TransactionHandler.php
  eZ/Publish/Core/Persistence/Cache/UserHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Language/Cache.php
  eZ/Publish/Core/Persistence/Legacy/Content/Language/CachingHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/MemoryCachingHandler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Language/CacheTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Language/CachingLanguageHandlerTest.php
  eZ/Publish/Core/settings/storage_engines/cache.yml
  eZ/Publish/Core/settings/storage_engines/legacy/content_type.yml
  eZ/Publish/Core/settings/storage_engines/legacy/language.yml
Labels: Ready for QA

#2568 EZP-30322: Fix list of users assigned to Role is not updated
  eZ/Publish/API/Repository/Tests/RoleServiceTest.php
  eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php
  eZ/Publish/Core/Persistence/Cache/UserHandler.php
Labels: Ready for QA

#2567 EZP-30230: Fixed issue revealing content with hidden children/parent
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
Labels: QA approved

#2569 EZP-30139: Fixed testRevealContent randomly failing on PostgreSQL
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
Labels: Bug, Ready for review

#2570 EZP-30316: Changed default password quality settings
  data/demo_data.php
  data/mysql/cleandata.sql
  data/postgresql/cleandata.sql
  doc/bc/changes-7.5.md
  doc/upgrade/7.5.md
  eZ/Bundle/EzPublishRestBundle/Features/Context/UserContentContext.php
  eZ/Publish/API/Repository/Tests/FieldType/UserIntegrationTest.php
  eZ/Publish/Core/FieldType/Tests/UserTest.php
  eZ/Publish/Core/FieldType/User/Type.php
Labels: QA approved

#2571 EZP-30271: Published version table disappears after bulk removing of drafts under edit
  eZ/Publish/API/Repository/Tests/BaseTest.php
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/Core/Persistence/Cache/ContentHandler.php
  eZ/Publish/Core/Persistence/Cache/Tests/ContentHandlerTest.php
Labels: Bug, QA approved

#2580 Command UpdateTimestampsToUTCCommand will fail on php 5.6
  eZ/Bundle/EzPublishCoreBundle/Command/UpdateTimestampsToUTCCommand.php
Labels: QA approved, Ready for MERGE

#2581 EZP-30331: Cannot edit ezmedia properties after publishing
  eZ/Publish/Core/FieldType/BinaryBase/BinaryBaseStorage.php
  eZ/Publish/Core/FieldType/BinaryBase/BinaryBaseStorage/Gateway/DoctrineStorage.php
  eZ/Publish/Core/FieldType/Media/MediaStorage/Gateway/DoctrineStorage.php
Labels: QA approved

#2584 EZP-30314: Content is cached even after deletion
  eZ/Publish/API/Repository/Tests/TrashServiceTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/TrashHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/TrashHandler.php
Labels: QA approved

#2587 EZP-30300: Fixed "Undefined offset: 0" notice when LocationService::loadLocationList is invoked with id of the root location
  eZ/Publish/API/Repository/Tests/LocationServiceTest.php
  eZ/Publish/Core/Repository/LocationService.php
Labels: Ready for QA, Ready for review

#2562 EZP-30229: Track original state of Location::$hidden
  eZ/Publish/API/Repository/Values/Content/Location.php
  eZ/Publish/Core/Repository/Helper/DomainMapper.php
Labels: QA approved

#2589 EZP-30365: Accessing some invalid links will result in 500 error instead of 404
  eZ/Publish/Core/Persistence/Cache/UrlAliasHandler.php
Labels: Bug, QA approved

#2574 EZP-29324: Limited ezcontentobject_tree_contentobject_id_path_string index column length
  data/mysql/schema.sql
  data/update/mysql/dbupdate-7.4.4-to-7.4.5.sql
Labels: Bug, Ready for MERGE

#2592 EZP-30374: Limited PK columns lengths to fix max index size limit
  eZ/Bundle/EzPublishCoreBundle/Resources/config/storage/legacy/schema.yaml
Labels: Bug, QA approved
