Repository ezsystems/ezpublish-kernel, pull requests merged in 2019-09, with the labels that each got.

#2757 Refactored integration test for ContentService
  eZ/Publish/API/Repository/Tests/ContentServiceAuthorizationTest.php
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
Labels: Improvement, Ready for MERGE

#2755 EZP-30905: Removed deprecated MatcherInterface
  doc/bc/changes-8.0.md
  eZ/Bundle/EzPublishCoreBundle/Matcher/ServiceAwareMatcherFactory.php
  eZ/Bundle/EzPublishCoreBundle/Matcher/ViewMatcherRegistry.php
  eZ/Publish/Core/MVC/Symfony/Matcher/AbstractMatcherFactory.php
  eZ/Publish/Core/MVC/Symfony/Matcher/ClassNameMatcherFactory.php
  eZ/Publish/Core/MVC/Symfony/Matcher/ContentBased/MatcherInterface.php
  eZ/Publish/Core/MVC/Symfony/Matcher/ContentBased/ViewMatcherInterface.php
  eZ/Publish/Core/MVC/Symfony/Matcher/ContentBasedMatcherFactory.php
  eZ/Publish/Core/MVC/Symfony/Matcher/ContentMatcherFactory.php
  eZ/Publish/Core/MVC/Symfony/Matcher/LocationMatcherFactory.php
  eZ/Publish/Core/MVC/Symfony/Matcher/MatcherInterface.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentMatcherFactoryTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/LocationMatcherFactoryTest.php
Labels: Improvement, QA approved

#2756 EZP-30912: Provided forward compatibility for CoreInstaller
  doc/bc/changes-7.5.md
  eZ/Bundle/PlatformInstallerBundle/src/DependencyInjection/Compiler/SchemaBuilderInstallerPass.php
  eZ/Bundle/PlatformInstallerBundle/src/EzSystemsPlatformInstallerBundle.php
  eZ/Bundle/PlatformInstallerBundle/src/Resources/config/services.yml
Labels: Bug, Improvement, QA approved

#2750 [Behat] EZP-30884: Added support for class name as service id
  eZ/Bundle/PlatformBehatBundle/Context/Argument/AnnotationArgumentResolver.php
Labels: Ready for MERGE

#2765 Dropped eZ\Publish\Core\FieldType\NameableFieldTypeFallback class
  eZ/Publish/Core/FieldType/NameableFieldTypeFallback.php
Labels: Bug

#2739 EZP-30823: Fixed possible race condition on version loading
  eZ/Publish/Core/Persistence/Cache/ContentHandler.php
  eZ/Publish/Core/Persistence/Cache/Tests/ContentHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase/QueryBuilder.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/ContentHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/_fixtures/extract_version_info_from_rows_multiple_versions.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
  eZ/Publish/SPI/Persistence/Content/Handler.php
Labels: QA approved

#2759 EZP-30906: Removed deprecated templating component integration
  doc/bc/changes-8.0.md
  doc/specifications/debug/data_collectors.md
  eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/security.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/CommonTest.php
  eZ/Bundle/EzPublishDebugBundle/Resources/config/services.yml
  eZ/Bundle/EzPublishDebugBundle/Resources/views/Profiler/layout.html.twig
  eZ/Publish/Core/MVC/Symfony/Controller/SecurityController.php
  eZ/Publish/Core/MVC/Symfony/View/Manager.php
  eZ/Publish/Core/MVC/Symfony/View/Renderer/TemplateRenderer.php
  eZ/Publish/Core/MVC/Symfony/View/Tests/Renderer/TemplateRendererTest.php
  eZ/Publish/Core/MVC/Symfony/View/Tests/ViewManagerTest.php
Labels: QA approved

#2742 EZP-30797: Implemented configuration for user password expiration
  data/update/mysql/dbupdate-7.5.3-to-7.5.4.sql
  data/update/postgres/dbupdate-7.5.3-to-7.5.4.sql
  eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/storage/legacy/schema.yaml
  eZ/Publish/API/Repository/Tests/FieldType/UserIntegrationTest.php
  eZ/Publish/API/Repository/Tests/UserServiceTest.php
  eZ/Publish/API/Repository/UserService.php
  eZ/Publish/API/Repository/Values/User/PasswordInfo.php
  eZ/Publish/API/Repository/Values/User/User.php
  eZ/Publish/Core/FieldType/Tests/Integration/User/UserStorage/UserStorageGatewayTest.php
  eZ/Publish/Core/FieldType/Tests/UserTest.php
  eZ/Publish/Core/FieldType/User/Type.php
  eZ/Publish/Core/FieldType/User/UserStorage/Gateway.php
  eZ/Publish/Core/FieldType/User/UserStorage/Gateway/DoctrineStorage.php
  eZ/Publish/Core/FieldType/User/UserStorage/Gateway/LegacyStorage.php
  eZ/Publish/Core/FieldType/User/Value.php
  eZ/Publish/Core/MVC/Symfony/FieldType/Tests/User/ParameterProviderTest.php
  eZ/Publish/Core/MVC/Symfony/FieldType/User/ParameterProvider.php
  eZ/Publish/Core/MVC/Symfony/Security/Tests/User/ProviderTest.php
  eZ/Publish/Core/MVC/Symfony/Security/User.php
  eZ/Publish/Core/MVC/Symfony/Security/User/Provider.php
  eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/UserConverter.php
  eZ/Publish/Core/Persistence/Legacy/Tests/User/UserHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.mysql.sql
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.pgsql.sql
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.sqlite.sql
  eZ/Publish/Core/Persistence/Legacy/User/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/User/Mapper.php
  eZ/Publish/Core/REST/Client/UserService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/UserServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/UserService.php
  eZ/Publish/Core/Repository/UserService.php
  eZ/Publish/Core/SignalSlot/Tests/UserServiceTest.php
  eZ/Publish/Core/SignalSlot/UserService.php
  eZ/Publish/SPI/Persistence/User.php
Labels: Feature, QA approved

#2740 EZP-30823: [6.x] Isolated cache during transactions to avoid race condition
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/Core/Persistence/Cache/Adapter/Item/TransactionItem.php
  eZ/Publish/Core/Persistence/Cache/Adapter/TransactionAwareAdapterInterface.php
  eZ/Publish/Core/Persistence/Cache/CacheServiceDecorator.php
  eZ/Publish/Core/Persistence/Cache/Tests/TransactionHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/TransactionHandler.php
  eZ/Publish/Core/Repository/ContentTypeService.php
Labels: QA approved

#2714 EZP-30790: Introduced strict types for Search supports methods
  doc/bc/changes-8.0.md
  eZ/Publish/API/Repository/SearchService.php
  eZ/Publish/Core/Repository/SearchService.php
  eZ/Publish/Core/Repository/SiteAccessAware/SearchService.php
  eZ/Publish/SPI/Repository/Decorator/SearchServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/SearchServiceDecoratorTest.php
  eZ/Publish/SPI/Search/Capable.php
Labels: Improvement, QA approved

#2772 EZP-30966: Fixed notice "Undefined index: PasswordTTL" while updating ezuser field definition using PAPI
  eZ/Publish/API/Repository/Tests/FieldType/UserIntegrationTest.php
  eZ/Publish/Core/FieldType/Tests/UserTest.php
  eZ/Publish/Core/FieldType/User/Type.php
  eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/UserConverter.php
Labels: Bug

#2773 Renamed data/update/{mysql,postgres}/dbupdate-7.5.3-to-7.5.4.sql to dbupdate-7.5.4-to-7.5.5.sql
  data/update/mysql/dbupdate-7.5.4-to-7.5.5.sql
  data/update/postgres/dbupdate-7.5.4-to-7.5.5.sql
Labels: Improvement

#2778 EZP-30974: Fixed outstanding PHPUnit warnings
  eZ/Bundle/EzPublishCoreBundle/SiteAccess/MatcherBuilder.php
  eZ/Bundle/EzPublishCoreBundle/SiteAccess/SiteAccessMatcherRegistry.php
  eZ/Bundle/EzPublishCoreBundle/SiteAccess/SiteAccessMatcherRegistryInterface.php
  eZ/Bundle/EzPublishCoreBundle/Tests/SiteAccess/MatcherBuilderTest.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
Labels: Bug, Ready for MERGE

#2767 EZP-30382: Add content hide/reveal to REST API
  doc/specifications/rest/REST-API-V2.rst
  eZ/Bundle/EzPublishRestBundle/Resources/config/routing.yml
  eZ/Publish/Core/REST/Server/Controller/Content.php
Labels: QA approved, Ready for MERGE

#2776 EZP-30911: Added option to pass location-id parameter to URL alias regeneration Command
  eZ/Bundle/EzPublishCoreBundle/Command/RegenerateUrlAliasesCommand.php
Labels: Improvement, QA approved

#2621 EZP-30394: Implemented External Storage for User Field Type
  doc/bc/changes-8.0.md
  eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php
  eZ/Publish/API/Repository/Tests/BaseTest.php
  eZ/Publish/API/Repository/Tests/FieldType/UserIntegrationTest.php
  eZ/Publish/API/Repository/Tests/PHPUnitConstraint/AllValidationErrorsOccur.php
  eZ/Publish/API/Repository/Tests/PHPUnitConstraint/ValidationErrorOccurs.php
  eZ/Publish/API/Repository/Tests/UserServiceTest.php
  eZ/Publish/API/Repository/Values/User/User.php
  eZ/Publish/Core/Base/Container/ApiLoader/RepositoryFactory.php
  eZ/Publish/Core/FieldType/Tests/Integration/User/UserStorage/Gateway/DoctrineStorageTest.php
  eZ/Publish/Core/FieldType/Tests/Integration/User/UserStorage/Gateway/LegacyStorageTest.php
  eZ/Publish/Core/FieldType/Tests/UserTest.php
  eZ/Publish/Core/FieldType/User/Type.php
  eZ/Publish/Core/FieldType/User/UserStorage.php
  eZ/Publish/Core/FieldType/User/UserStorage/Gateway.php
  eZ/Publish/Core/FieldType/User/UserStorage/Gateway/DoctrineStorage.php
  eZ/Publish/Core/FieldType/User/UserStorage/Gateway/LegacyStorage.php
  eZ/Publish/Core/FieldType/User/Value.php
  eZ/Publish/Core/Persistence/Cache/Tests/AbstractInMemoryCacheHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/UserHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/UserHandler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/User/UserHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/User/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/User/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/User/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/User/Handler.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/UserTest.php
  eZ/Publish/Core/Repository/User/PasswordHashGenerator.php
  eZ/Publish/Core/Repository/User/PasswordHashGeneratorInterface.php
  eZ/Publish/Core/Repository/User/PasswordValidator.php
  eZ/Publish/Core/Repository/User/PasswordValidatorInterface.php
  eZ/Publish/Core/Repository/UserService.php
  eZ/Publish/Core/settings/fieldtype_services.yml
  eZ/Publish/Core/settings/fieldtypes.yml
  eZ/Publish/Core/settings/repository/inner.yml
  eZ/Publish/Core/settings/storage_engines/legacy/external_storage_gateways.yml
  eZ/Publish/SPI/Tests/FieldType/UserIntegrationTest.php
Labels: Feature, Improvement, QA approved

#2753 EZP-30427: Added support to paginate a list of drafts
  eZ/Publish/API/Repository/ContentService.php
  eZ/Publish/API/Repository/Tests/ContentServiceAuthorizationTest.php
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/API/Repository/Values/Content/ContentDraftList.php
  eZ/Publish/API/Repository/Values/Content/DraftList/ContentDraftListItemInterface.php
  eZ/Publish/API/Repository/Values/Content/DraftList/Item/ContentDraftListItem.php
  eZ/Publish/API/Repository/Values/Content/DraftList/Item/UnauthorizedContentDraftListItem.php
  eZ/Publish/Core/Persistence/Cache/ContentHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
  eZ/Publish/Core/REST/Client/ContentService.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentServiceTest.php
  eZ/Publish/Core/SignalSlot/ContentService.php
  eZ/Publish/Core/SignalSlot/Tests/ContentServiceTest.php
  eZ/Publish/SPI/Persistence/Content/Handler.php
Labels: Bug, QA approved

#2768 Dropped Setup and Design from clean data directory structure
  data/mysql/cleandata.sql
  data/postgresql/cleandata.sql
  doc/bc/changes-8.0.md
Labels: Improvement, QA approved

#2751 EZP-30898: Dropped CleanInstaller and cleaned up installer code
  composer.json
  doc/bc/changes-8.0.md
  eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php
  eZ/Bundle/PlatformInstallerBundle/src/DependencyInjection/Compiler/InstallerTagPass.php
  eZ/Bundle/PlatformInstallerBundle/src/DependencyInjection/Compiler/SchemaBuilderInstallerPass.php
  eZ/Bundle/PlatformInstallerBundle/src/EzSystemsPlatformInstallerBundle.php
  eZ/Bundle/PlatformInstallerBundle/src/Installer/CleanInstaller.php
  eZ/Bundle/PlatformInstallerBundle/src/Installer/CoreInstaller.php
  eZ/Bundle/PlatformInstallerBundle/src/Resources/config/services.yml
  eZ/Bundle/PlatformInstallerBundle/tests/DependencyInjection/Compiler/InstallerTagPassTest.php
  eZ/Bundle/PlatformInstallerBundle/tests/DependencyInjection/EzSystemsPlatformInstallerExtensionTest.php
  eZ/Bundle/PlatformInstallerBundle/tests/EzSystemsPlatformInstallerBundleTest.php
Labels: Feature, Improvement, QA approved

#2752 EZP-30624: Dropped deprecated SQL schema files
  data/mysql/dfs_schema.sql
  data/mysql/schema.sql
  doc/bc/changes-8.0.md
  eZ/Bundle/EzPublishCoreBundle/Command/TestInitDbCommand.php
  eZ/Publish/API/Repository/Tests/LegacySchemaImporter.php
  eZ/Publish/API/Repository/Tests/SetupFactory/Legacy.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/TestCase.php
  eZ/Publish/Core/Persistence/Legacy/Tests/User/UserHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.mysql.sql
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.pgsql.sql
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.sqlite.sql
  eZ/Publish/Core/Persistence/Tests/DatabaseConnectionFactory.php
  eZ/Publish/SPI/Tests/FieldType/BaseIntegrationTest.php
  eZ/Publish/SPI/Tests/FieldType/BinaryFileIntegrationTest.php
  eZ/Publish/SPI/Tests/FieldType/FileBaseIntegrationTest.php
Labels: Improvement

#2749 EZP-30823: [7.x] Isolated cache during transactions to avoid race condition
  eZ/Bundle/EzPublishCoreBundle/Resources/config/cache.yml
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/API/Repository/Tests/Regression/EnvTest.php
  eZ/Publish/Core/Persistence/Cache/AbstractInMemoryHandler.php
  eZ/Publish/Core/Persistence/Cache/Adapter/InMemoryClearingProxyAdapter.php
  eZ/Publish/Core/Persistence/Cache/Adapter/README.md
  eZ/Publish/Core/Persistence/Cache/Adapter/TransactionAwareAdapterInterface.php
  eZ/Publish/Core/Persistence/Cache/Adapter/TransactionalCacheAdapterDecorator.php
  eZ/Publish/Core/Persistence/Cache/Adapter/TransactionalInMemoryCacheAdapter.php
  eZ/Publish/Core/Persistence/Cache/InMemory/InMemoryCache.php
  eZ/Publish/Core/Persistence/Cache/Tests/AbstractBaseHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/Adapter/InMemoryClearingProxyAdapterTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/TransactionHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/TransactionHandler.php
  eZ/Publish/Core/settings/storage_engines/cache.yml
Labels: Ready for review
