Repository ezsystems/ezpublish-kernel, pull requests merged in 2019-08, with the labels that each got.

#2709 EZP-30725: Added slot that delete content type drafts of removed user
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Publish/API/Repository/ContentTypeService.php
  eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
  eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/MemoryCachingHandler.php
  eZ/Publish/Core/REST/Client/ContentTypeService.php
  eZ/Publish/Core/Repository/ContentTypeService.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/SiteAccessAware/ContentTypeService.php
  eZ/Publish/Core/Repository/Slot/User/DeleteUser.php
  eZ/Publish/Core/SignalSlot/ContentTypeService.php
  eZ/Publish/Core/settings/containerBuilder.php
  eZ/Publish/Core/settings/slot.yml
  eZ/Publish/SPI/Persistence/Content/Type/DeleteByParamsStruct.php
  eZ/Publish/SPI/Persistence/Content/Type/Handler.php
  eZ/Publish/SPI/Tests/FieldType/BaseIntegrationTest.php
  eZ/Publish/SPI/Tests/FieldType/FileBaseIntegrationTest.php
Labels: Bug, QA approved, Ready for review

#2716 EZP-30725: Added db upgrade script for CT drafts cleanup
  data/update/mysql/dbupdate-7.5.2-to-7.5.3.sql
  data/update/postgres/dbupdate-7.5.2-to-7.5.3.sql
Labels: Bug, QA approved, Ready for review

#2723 EZP-30725: Replaced DeleteUser Slot with Event Subscriber
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/events.yml
  eZ/Publish/Core/Repository/EventSubscriber/DeleteUserSubscriber.php
  eZ/Publish/Core/Repository/Slot/User/DeleteUser.php
  eZ/Publish/Core/settings/containerBuilder.php
  eZ/Publish/Core/settings/events.yml
  eZ/Publish/Core/settings/slot.yml
  eZ/Publish/SPI/Tests/FieldType/BaseIntegrationTest.php
  eZ/Publish/SPI/Tests/FieldType/FileBaseIntegrationTest.php
Labels: QA approved

#2708 Remove Twig deprecations
  composer.json
  eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/style/default.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/FieldType/RichText/style/default_inline.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
Labels: QA approved

#2380 EZP-29386: Added FQCN-named Repository services to simplify autowiring
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Publish/Core/settings/containerBuilder.php
  eZ/Publish/Core/settings/repository/autowire.yml
  eZ/Publish/SPI/Tests/FieldType/BaseIntegrationTest.php
  eZ/Publish/SPI/Tests/FieldType/FileBaseIntegrationTest.php
Labels: Improvement, QA approved

#2724 EZP-30817: Fixed ezplatform:timestamps:to-utc cmd to respect version no.
  eZ/Bundle/EzPublishCoreBundle/Command/UpdateTimestampsToUTCCommand.php
Labels: Bug, QA approved

#2718 Fixed error when building UserGroup when a user has no access to a parent location
  eZ/Publish/API/Repository/Tests/BaseTest.php
  eZ/Publish/API/Repository/Tests/UserServiceTest.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/UserTest.php
  eZ/Publish/Core/Repository/UserService.php
Labels: Bug, QA approved, Ready for review

#2721 EZP-30812: Fixed deprecated use of Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch method
  eZ/Bundle/EzPublishCoreBundle/EventListener/ConsoleCommandListener.php
  eZ/Bundle/EzPublishCoreBundle/EventListener/ViewControllerListener.php
  eZ/Bundle/EzPublishCoreBundle/SignalSlot/Slot/SymfonyEventConverterSlot.php
  eZ/Bundle/EzPublishCoreBundle/Tests/SignalSlot/SymfonyEventConverterSlotTest.php
  eZ/Publish/Core/Helper/ContentPreviewHelper.php
  eZ/Publish/Core/Helper/Tests/ContentPreviewHelperTest.php
  eZ/Publish/Core/MVC/Symfony/EventListener/SiteAccessMatchListener.php
  eZ/Publish/Core/MVC/Symfony/EventListener/Tests/SiteAccessMatchListenerTest.php
  eZ/Publish/Core/MVC/Symfony/Routing/Generator/RouteReferenceGenerator.php
  eZ/Publish/Core/MVC/Symfony/Routing/Tests/RouteReferenceGeneratorTest.php
  eZ/Publish/Core/MVC/Symfony/Security/EventListener/SecurityListener.php
  eZ/Publish/Core/MVC/Symfony/View/Manager.php
  eZ/Publish/Core/MVC/Symfony/View/ParametersInjector/EventDispatcherInjector.php
  eZ/Publish/Core/MVC/Symfony/View/Renderer/TemplateRenderer.php
  eZ/Publish/Core/MVC/Symfony/View/Tests/Renderer/TemplateRendererTest.php
Labels: Improvement, QA approved

#2725 EZP-30819: Removed deprecated controller references from routes definitions
  eZ/Bundle/EzPublishCoreBundle/Resources/config/routing/internal.yml
Labels: Improvement, QA approved

#2726 EZP-30821: Fixed wrong usage of hasAccess in URLService
  eZ/Publish/API/Repository/Tests/URLServiceAuthorizationTest.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/UrlTest.php
  eZ/Publish/Core/Repository/URLService.php
Labels: Bug, QA approved, Ready for MERGE

#2733 EZP-30831: Fixed wrong usage of hasAccess in TrashService
  eZ/Publish/API/Repository/Tests/TrashServiceTest.php
  eZ/Publish/Core/Repository/TrashService.php
Labels: Bug, QA approved

#2729 EZP-30822: Fixed wrong usage of hasAccess in URLAliasService
  eZ/Publish/API/Repository/Tests/URLAliasServiceAuthorizationTest.php
  eZ/Publish/API/Repository/Tests/URLAliasServiceTest.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/UrlAliasTest.php
  eZ/Publish/Core/Repository/URLAliasService.php
Labels: Bug, QA approved

#2732 EZP-30832: Fixed wrong usage of hasAccess in URLWildcardService
  eZ/Publish/API/Repository/Tests/URLWildcardServiceAuthorizationTest.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/UrlWildcardTest.php
  eZ/Publish/Core/Repository/URLWildcardService.php
Labels: Bug, QA approved, Ready for MERGE, Ready for review

#2730 EZP-30828: Replaced \Symfony\Component\EventDispatcher\Event usage in favor of Symfony\Contracts\EventDispatcher\Event
  eZ/Publish/Core/MVC/Symfony/Event/APIContentExceptionEvent.php
  eZ/Publish/Core/MVC/Symfony/Event/ContentCacheClearEvent.php
  eZ/Publish/Core/MVC/Symfony/Event/PostSiteAccessMatchEvent.php
  eZ/Publish/Core/MVC/Symfony/Event/PreContentViewEvent.php
  eZ/Publish/Core/MVC/Symfony/Event/RouteReferenceGenerationEvent.php
  eZ/Publish/Core/MVC/Symfony/Event/ScopeChangeEvent.php
  eZ/Publish/Core/MVC/Symfony/View/Event/FilterViewBuilderParametersEvent.php
  eZ/Publish/Core/MVC/Symfony/View/Event/FilterViewParametersEvent.php
Labels: Improvement, QA approved

#2734 EZP-30846: Dropped deprecated Symfony\Component\Config\Definition\Builder\TreeBuilder::root method calls
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php
  eZ/Bundle/EzPublishIOBundle/DependencyInjection/Configuration.php
Labels: Improvement, QA approved

#2736 Fixed reference to undefined property "settingsSchema" in Generic\Type::validateFieldSettings
  eZ/Publish/SPI/FieldType/Generic/Type.php
Labels: Bug

#2737 Fixed missing % in parameters names passed to {UnknownValidator,NonConfigurable}ValidationError
  eZ/Publish/SPI/FieldType/ValidationError/NonConfigurableValidationError.php
  eZ/Publish/SPI/FieldType/ValidationError/UnknownValidatorValidationError.php
Labels: Bug

#2731 EZP-30737: As a Developer I want IO HandlerFactory to not use direct …
  doc/bc/changes-8.0.md
  eZ/Bundle/EzPublishIOBundle/ApiLoader/HandlerRegistry.php
  eZ/Bundle/EzPublishIOBundle/DependencyInjection/Compiler/IOConfigurationPass.php
  eZ/Bundle/EzPublishIOBundle/DependencyInjection/ConfigurationFactory/Flysystem.php
  eZ/Bundle/EzPublishIOBundle/Migration/FileLister/BinaryFileLister.php
  eZ/Bundle/EzPublishIOBundle/Migration/FileLister/ImageFileLister.php
  eZ/Bundle/EzPublishIOBundle/Migration/MigrationHandler.php
  eZ/Bundle/EzPublishIOBundle/Resources/config/io.yml
  eZ/Bundle/EzPublishIOBundle/Tests/DependencyInjection/Compiler/IOConfigurationPassTest.php
  eZ/Publish/Core/settings/io.yml
Labels: Improvement, QA approved

#2735 EZP-30839: Fixed loading Content of Location for 1st draft in preview
  eZ/Publish/Core/Helper/PreviewLocationProvider.php
  eZ/Publish/Core/Helper/Tests/PreviewLocationProviderTest.php
  eZ/Publish/Core/MVC/Symfony/Controller/Content/PreviewController.php
  eZ/Publish/Core/MVC/Symfony/Controller/Tests/Controller/Content/PreviewControllerTest.php
Labels: QA approved

#2738 EZP-30852: Section handler has been used in methods create and updateSection
  eZ/Publish/API/Repository/Tests/SectionServiceAuthorizationTest.php
  eZ/Publish/API/Repository/Tests/SectionServiceTest.php
  eZ/Publish/Core/Repository/SectionService.php
Labels: Bug, QA approved

#2691 EZP-30729: Added a possibility to exclude Content Types when running CleanupVersionsCommand
  eZ/Bundle/EzPublishCoreBundle/Command/CleanupVersionsCommand.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
Labels: Bug, QA approved, Ready for MERGE

#2744 EZP-30796: Fixed copying content with Subtree limitation
  eZ/Publish/API/Repository/Tests/ContentServiceAuthorizationTest.php
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/Helper/DomainMapper.php
  eZ/Publish/Core/Repository/LocationService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
Labels: Bug, QA approved

#2743 EZP-30869: Added extension point in login form view
  eZ/Publish/Core/MVC/Symfony/Controller/SecurityController.php
  eZ/Publish/Core/MVC/Symfony/View/LoginFormView.php
  eZ/Publish/Core/MVC/Symfony/View/Tests/AbstractViewTest.php
  eZ/Publish/Core/MVC/Symfony/View/Tests/ContentViewTest.php
  eZ/Publish/Core/MVC/Symfony/View/Tests/LoginFormViewTest.php
Labels: Feature, Ready for MERGE, Ready for QA

#2671 EZP-30681: Fixed double slash in path_identification_string after moveSubtree
  eZ/Publish/API/Repository/Tests/LocationServiceTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
Labels: Bug, QA approved

#2696 EZP-30544: Use configurable user hash header name
  eZ/Bundle/EzPublishCoreBundle/EventListener/RequestEventListener.php
  eZ/Publish/Core/MVC/Symfony/Controller/Content/ViewController.php
Labels: QA approved

#2745 EZP-30880: Refactored MatcherFactory to avoid using direct Container calls
  doc/bc/changes-8.0.md
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/ViewMatcherRegistryPass.php
  eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php
  eZ/Bundle/EzPublishCoreBundle/Matcher/ContentMatcherFactory.php
  eZ/Bundle/EzPublishCoreBundle/Matcher/LocationMatcherFactory.php
  eZ/Bundle/EzPublishCoreBundle/Matcher/ServiceAwareMatcherFactory.php
  eZ/Bundle/EzPublishCoreBundle/Matcher/ViewMatcherRegistry.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/ViewMatcherRegistryPassTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Matcher/BaseMatcherFactoryTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Matcher/ContentMatcherFactoryTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Matcher/LocationMatcherFactoryTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Matcher/ViewMatcherRegistryTest.php
Labels: Improvement, QA approved

#2747 EZP-30598: Removed Container::get calls from SiteAccess MatcherBuilder
  doc/bc/changes-8.0.md
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/SiteAccessMatcherRegistryPass.php
  eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/routing.yml
  eZ/Bundle/EzPublishCoreBundle/SiteAccess/MatcherBuilder.php
  eZ/Bundle/EzPublishCoreBundle/SiteAccess/SiteAccessMatcherRegistry.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/SiteAccessMatcherRegistryPassTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/SiteAccess/MatcherBuilderTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/SiteAccess/SiteAccessMatcherRegistryTest.php
Labels: Improvement, QA approved
