Repository ezsystems/ezpublish-kernel, pull requests merged in 2019-01, with the labels that each got.

#2520 EZP-29997: Exposed information about removed content items in EmptyTrashSignal and DeleteTrashItemSignal
  eZ/Publish/API/Repository/TrashService.php
  eZ/Publish/API/Repository/Values/Content/Trash/TrashItemDeleteResult.php
  eZ/Publish/API/Repository/Values/Content/Trash/TrashItemDeleteResultList.php
  eZ/Publish/Core/Persistence/Cache/TrashHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Trash/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/TrashHandlerTest.php
  eZ/Publish/Core/Repository/TrashService.php
  eZ/Publish/Core/SignalSlot/Signal/TrashService/DeleteTrashItemSignal.php
  eZ/Publish/Core/SignalSlot/Signal/TrashService/EmptyTrashSignal.php
  eZ/Publish/Core/SignalSlot/Tests/TrashServiceTest.php
  eZ/Publish/Core/SignalSlot/TrashService.php
  eZ/Publish/SPI/Persistence/Content/Location/Trash/Handler.php
Labels: Improvement, QA approved, Ready for MERGE

#2522 EZP-30004: ezplatform:urls:regenerate-aliases changes parent of broken link
  eZ/Publish/API/Repository/Tests/URLAliasServiceTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php
Labels: Bug, Ready for MERGE

#2518 EZP-29924: Can't save ContentType with RelationList which has selectionMethod from legacy
  eZ/Publish/Core/FieldType/RelationList/Type.php
  eZ/Publish/Core/FieldType/Tests/RelationListTest.php
Labels: QA approved, Ready for MERGE

#2510 EZP-29959: Token not found exception in ContentViewBuilder when used to build own exception page
  eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
  eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php
Labels: Ready for QA

#2515 EZP-29041: Content still visible in ezobjectrelationlist after sending it to trash
  eZ/Publish/Core/Persistence/Cache/Tests/TrashHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/TrashHandler.php
Labels: QA approved, Ready for review

#2531 EZP-28663: Cannot swap location when viewing item from non-main location
  eZ/Publish/API/Repository/Tests/LocationServiceTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php
Labels: Bug, Ready for QA
