Repository ezsystems/ezpublish-kernel, pull requests merged in 2019-12, with the labels that each got.

#2786 EZP-30973: Made siteaccess aware repository to be used as default
  doc/bc/changes-8.0.md
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/API/Repository/Tests/LocationServiceTest.php
  eZ/Publish/API/Repository/Tests/ObjectStateServiceTest.php
  eZ/Publish/API/Repository/Tests/SearchServiceTranslationLanguageFallbackTest.php
  eZ/Publish/API/Repository/Tests/UserServiceTest.php
  eZ/Publish/Core/Repository/ObjectStateService.php
  eZ/Publish/Core/Repository/Values/ObjectState/ObjectState.php
  eZ/Publish/Core/Repository/Values/ObjectState/ObjectStateGroup.php
  eZ/Publish/Core/settings/repository.yml
  eZ/Publish/Core/settings/repository/siteaccessaware.yml
Labels: Feature, QA approved

#2862 EZP-31113: Implemented indexing subtree after assigning Section to it
  eZ/Publish/Core/Search/Common/Slot/AssignSectionToSubtree.php
  eZ/Publish/Core/settings/search_engines/elasticsearch/slots.yml
  eZ/Publish/Core/settings/search_engines/legacy/slots.yml
Labels: Bug, QA approved

#2895 Removed `*.class` parameters from routing configuration
  doc/bc/changes-8.0.md
  eZ/Bundle/EzPublishCoreBundle/Resources/config/routing.yml
Labels: Improvement

#2850 EZP-30754: Fixed handling always available flag for ContentInfo update
  eZ/Publish/API/Repository/Tests/BaseTest.php
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Mapper.php
Labels: Bug, QA approved

#2858 EZP-30997: Fixed permission checks when copying translations during publishing
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/LanguageLimitationTest.php
  eZ/Publish/Core/Limitation/LanguageLimitationType.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
  eZ/Publish/SPI/Limitation/Target/Builder/VersionBuilder.php
  eZ/Publish/SPI/Limitation/Target/Version.php
  eZ/Publish/SPI/Tests/Limitation/Target/Builder/VersionBuilderTest.php
Labels: Bug, QA approved, Ready for review

#2876 EZP-31059: Limited URL Search Results to unique entries only
  eZ/Publish/API/Repository/Tests/BaseURLServiceTest.php
  eZ/Publish/API/Repository/Tests/URLServiceTest.php
  eZ/Publish/Core/Persistence/Legacy/URL/Gateway/DoctrineDatabase.php
Labels: Bug, QA approved

#2883 EZP-30806: Fixed processing REST logical op. input with list of objects
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/ViewTest.php
  eZ/Publish/Core/REST/Server/Input/Parser/Criterion/LogicalOperator.php
  eZ/Publish/Core/REST/Server/Tests/Input/Parser/BaseTest.php
  eZ/Publish/Core/REST/Server/Tests/Input/Parser/Criterion/LogicalAndTest.php
  eZ/Publish/Core/REST/Server/Tests/Input/Parser/Criterion/LogicalOperatorTestCase.php
  eZ/Publish/Core/REST/Server/Tests/Input/Parser/Criterion/LogicalOrTest.php
Labels: Bug, QA approved

#2879 EZP-30806: Added example of REST search query with logical operators
  doc/specifications/rest/REST-API-V2.rst
Labels: Improvement, Ready for review

#2897 EZEE-2876: Fixed invalid list order being returned by AbstractInMemoryHandler
  eZ/Publish/API/Repository/Tests/LocationServiceTest.php
  eZ/Publish/Core/Persistence/Cache/AbstractInMemoryHandler.php
Labels: Bug, QA approved

#2892 EZP-31049: Implemented SiteAccess service
  eZ/Bundle/EzPublishCoreBundle/Resources/config/routing.yml
  eZ/Publish/Core/MVC/Symfony/SiteAccess/SiteAccessService.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/SiteAccessServiceInterface.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/SiteAccessServiceTest.php
Labels: Improvement, Ready for QA, Ready for review

#2884 EZP-31193: Added information about Site Access groups to the Site Access
  eZ/Bundle/EzPublishCoreBundle/Resources/config/routing.yml
  eZ/Publish/Core/MVC/Symfony/SiteAccess.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Provider/StaticSiteAccessProvider.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/SiteAccessService.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/SiteAccessServiceInterface.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/Provider/ChainSiteAccessProviderTest.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/SiteAccessServiceTest.php
  eZ/Publish/Core/MVC/Symfony/SiteAccessGroup.php
Labels: Improvement, QA approved, Ready for review

#2898 Typo in rest-api-v2.rst
  doc/specifications/rest/REST-API-V2.rst
Labels: Ready for review

#2840 EZP-31083: Improvements to Persistence/Cache to reduce (unfreeable) memory usage on Redis (mainly due to our tag usage)
  eZ/Publish/Core/Persistence/Cache/ContentHandler.php
  eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php
  eZ/Publish/Core/Persistence/Cache/LocationHandler.php
  eZ/Publish/Core/Persistence/Cache/NotificationHandler.php
  eZ/Publish/Core/Persistence/Cache/Readme.md
  eZ/Publish/Core/Persistence/Cache/Tests/AbstractCacheHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/ContentHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/ContentTypeHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/LocationHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/NotificationHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/TrashHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/UrlAliasHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/UrlWildcardHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/UserHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/UserPreferenceHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/TrashHandler.php
  eZ/Publish/Core/Persistence/Cache/UrlWildcardHandler.php
  eZ/Publish/Core/Persistence/Cache/UserHandler.php
  eZ/Publish/Core/Persistence/Cache/UserPreferenceHandler.php
Labels: QA approved

#2885 EZP-31125: Added TranslatedName to Content/ContentInfo in REST response
  doc/specifications/rest/REST-API-V2.rst
  eZ/Bundle/EzPublishRestBundle/Resources/config/value_object_visitors.yml
  eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/RestContent.php
  eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/RestContentTest.php
Labels: Improvement, QA approved

#2464 EZP-29586: Set ownership of copied Content Versions to the current User
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
Labels: QA approved

#2902 EZP-31235: Fixed validating translation list for publishing in LanguageLimitation
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/LanguageLimitationTest.php
  eZ/Publish/Core/Limitation/LanguageLimitation/ContentTranslationEvaluator.php
  eZ/Publish/Core/Limitation/LanguageLimitation/NewDraftEvaluator.php
  eZ/Publish/Core/Limitation/LanguageLimitation/VersionPublishingEvaluator.php
  eZ/Publish/Core/Limitation/LanguageLimitation/VersionTargetEvaluator.php
  eZ/Publish/Core/Limitation/LanguageLimitation/VersionTranslationUpdateEvaluator.php
  eZ/Publish/Core/Limitation/LanguageLimitationType.php
  eZ/Publish/Core/settings/limitations/language.yml
  eZ/Publish/Core/settings/roles.yml
Labels: Bug, QA approved

#2849 EZP-28900: Improved fromHash function in FloatType to return correct float value
  eZ/Publish/Core/FieldType/Float/Type.php
Labels: Improvement, QA approved, Ready for review

#2900 EZP-31203 (1.13): Fixed always using default connection for install Command
  eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php
  eZ/Bundle/PlatformInstallerBundle/src/Resources/config/services.yml
Labels: Bug, QA approved, Ready for QA

#2839 EZP-31078: Enhanced Content Type Value Object
  doc/bc/changes-8.0.md
  eZ/Publish/API/Repository/Exceptions/OutOfBoundsException.php
  eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
  eZ/Publish/API/Repository/Tests/FieldType/UserIntegrationTest.php
  eZ/Publish/API/Repository/Values/ContentType/ContentType.php
  eZ/Publish/API/Repository/Values/ContentType/FieldDefinitionCollection.php
  eZ/Publish/Core/Helper/Tests/FieldHelperTest.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/ContentExtensionTest.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/FieldRenderingExtensionIntegrationTest.php
  eZ/Publish/Core/Repository/ContentTypeService.php
  eZ/Publish/Core/Repository/Helper/ContentTypeDomainMapper.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/RelationProcessorTest.php
  eZ/Publish/Core/Repository/Tests/Values/ContentType/ContentTypeTest.php
  eZ/Publish/Core/Repository/Tests/Values/ContentType/FieldDefinitionCollectionTest.php
  eZ/Publish/Core/Repository/UserService.php
  eZ/Publish/Core/Repository/Values/ContentType/ContentType.php
  eZ/Publish/Core/Repository/Values/ContentType/ContentTypeDraft.php
  eZ/Publish/Core/Repository/Values/ContentType/FieldDefinitionCollection.php
Labels: DX, Feature

#2906 Merged database upgrade scripts for 8.0.0
  data/update/mysql/dbupdate-7.5.3-to-8.0.0.sql
  data/update/mysql/dbupdate-7.5.latest-to-8.0.0.sql
  data/update/postgres/dbupdate-7.5.3-to-8.0.0.sql
  data/update/postgres/dbupdate-7.5.latest-to-8.0.0.sql
Labels: DX, Improvement, Ready for review
