Repository ezsystems/ezpublish-kernel, pull requests merged in 2019-02, with the labels that each got.

#2516 EZP-29961: Add preferred language value to User Preferences
  eZ/Bundle/EzPublishCoreBundle/Resources/config/locale.yml
  eZ/Publish/Core/MVC/Symfony/Locale/Tests/UserLanguagePreferenceProviderTest.php
  eZ/Publish/Core/MVC/Symfony/Locale/UserLanguagePreferenceProvider.php
Labels: QA approved, Ready for review

#2513 EZP-29980 : Anonymous should be able to see images
  data/mysql/cleandata.sql
  eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
  eZ/Publish/Core/MVC/Symfony/FieldType/ImageAsset/ParameterProvider.php
  eZ/Publish/Core/MVC/Symfony/FieldType/Tests/ImageAsset/ParameterProviderTest.php
Labels: Bug, QA approved

#2541 EZP-30118: Fix typo in UnauthorizedException message
  eZ/Publish/Core/Base/Exceptions/UnauthorizedException.php
Labels: Ready for review

#2526 EZP-30013: --env option not passed to parallel processes of `ezplatform:reindex` Command
  eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php
Labels: Bug, QA approved

#2511 EZP-29466: As a Developer, I would like to have configuration for absolute/relative URLs for generated images
  eZ/Bundle/EzPublishCoreBundle/Imagine/Cache/Resolver/RelativeResolver.php
  eZ/Bundle/EzPublishCoreBundle/Imagine/Cache/ResolverFactory.php
  eZ/Bundle/EzPublishCoreBundle/Imagine/ResolverFactory.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Cache/Resolver/RelativeResolverTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Cache/ResolverFactoryTest.php
Labels: QA approved, Ready for MERGE

#2529 EZP-30029: As a Developer I'd like API for bulk loading Content Info Items
  eZ/Publish/API/Repository/ContentService.php
  eZ/Publish/API/Repository/Tests/ContentServiceAuthorizationTest.php
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/Core/MVC/Symfony/FieldType/RelationList/ParameterProvider.php
  eZ/Publish/Core/MVC/Symfony/FieldType/Tests/RelationList/ParameterProviderTest.php
  eZ/Publish/Core/REST/Client/ContentService.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentServiceTest.php
  eZ/Publish/Core/SignalSlot/ContentService.php
  eZ/Publish/Core/SignalSlot/Tests/ContentServiceTest.php
Labels: Ready for QA

#2524 EZP-30006: As a Developer I possibility to load several languages at once
  eZ/Publish/API/Repository/LanguageService.php
  eZ/Publish/API/Repository/Tests/LanguageServiceTest.php
  eZ/Publish/Core/Persistence/Cache/ContentLanguageHandler.php
  eZ/Publish/Core/Persistence/Cache/Tests/ContentLanguageHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Language/Cache.php
  eZ/Publish/Core/Persistence/Legacy/Content/Language/CachingHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Language/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Language/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Language/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/Language/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Language/Mapper.php
  eZ/Publish/Core/Persistence/Legacy/Content/Language/MaskGenerator.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Mapper.php
  eZ/Publish/Core/Persistence/Legacy/Content/ObjectState/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/ObjectState/Mapper.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Language/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Language/LanguageHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Language/MaskGeneratorTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/LanguageHandlerMock.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/MapperTest.php
  eZ/Publish/Core/REST/Client/LanguageService.php
  eZ/Publish/Core/Repository/LanguageService.php
  eZ/Publish/Core/Repository/SiteAccessAware/LanguageService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/LanguageServiceTest.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/LanguageCode.php
  eZ/Publish/Core/Search/Legacy/Content/Handler.php
  eZ/Publish/Core/SignalSlot/LanguageService.php
  eZ/Publish/Core/SignalSlot/Tests/LanguageServiceTest.php
  eZ/Publish/SPI/Persistence/Content/Language/Handler.php
Labels: Ready for QA

#2534 [DX] Provided autoconfiguration for API/Repository integration tests
  eZ/Publish/API/Repository/Tests/BaseTest.php
Labels: Improvement

#2546 EZP-30146: Added missing LocationId SortClause REST Input Parser
  eZ/Bundle/EzPublishRestBundle/Resources/config/input_parsers.yml
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/SortClauseTest.php
Labels: QA approved

#2544 EZP-30136: Updating content with "ezuser" field will not commit changes to Solr
  eZ/Publish/API/Repository/Tests/SearchEngineIndexingTest.php
  eZ/Publish/Core/Search/Common/Slot/UpdateUser.php
  eZ/Publish/Core/settings/search_engines/elasticsearch/slots.yml
  eZ/Publish/Core/settings/search_engines/legacy/slots.yml
Labels: Bug, QA approved

#2532 EZP-29990: As an Administrator I want to translate ezselection Field Definition options
  data/mysql/schema.sql
  data/update/mysql/dbupdate-7.4.0-to-7.5.0.sql
  data/update/postgres/dbupdate-7.4.0-to-7.5.0.sql
  eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
  eZ/Publish/API/Repository/Tests/BaseContentTypeServiceTest.php
  eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
  eZ/Publish/API/Repository/Tests/FieldType/BaseIntegrationTest.php
  eZ/Publish/API/Repository/Tests/FieldType/SelectionIntegrationTest.php
  eZ/Publish/API/Repository/Tests/FieldType/SelectionMultilingualIntegrationTest.php
  eZ/Publish/API/Repository/Values/ContentType/FieldDefinition.php
  eZ/Publish/Core/FieldType/Selection/NameableField.php
  eZ/Publish/Core/FieldType/Selection/SearchField.php
  eZ/Publish/Core/FieldType/Selection/Type.php
  eZ/Publish/Core/FieldType/Tests/SelectionTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/SelectionConverter.php
  eZ/Publish/Core/Persistence/Legacy/Content/MultilingualStorageFieldDefinition.php
  eZ/Publish/Core/Persistence/Legacy/Content/StorageFieldDefinition.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Mapper.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Update/Handler/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/FieldValue/Converter/SelectionTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/ContentTypeHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/MapperTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.mysql.sql
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.pgsql.sql
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.sqlite.sql
  eZ/Publish/Core/Repository/ContentTypeService.php
  eZ/Publish/Core/Repository/Helper/ContentTypeDomainMapper.php
  eZ/Publish/Core/settings/storage_engines/legacy/field_value_converters.yml
  eZ/Publish/SPI/Persistence/Content/Type/FieldDefinition.php
  eZ/Publish/SPI/Tests/FieldType/SelectionIntegrationTest.php
Labels: QA approved

#2536 EZP-29539: Deleting object will remove all subtree items even when user does not have permission to delete them
  eZ/Publish/API/Repository/Tests/BaseTest.php
  eZ/Publish/API/Repository/Tests/TrashServiceAuthorizationTest.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/TrashService.php
Labels: Bug, Ready for QA
