Repository ezsystems/ezpublish-kernel, pull requests merged in 2019-05, with the labels that each got.

#2622 EZP-30504: Removed trailing space from img attributes
  eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
Labels: Bug, QA approved

#2514 EZP-29865: Removed spaceless Twig tag from ezpage_field block
  eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
Labels: Bug

#2624 [Tests] Fixed failing hide/reveal Content integration tests
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
Labels: Bug

#2627 [Travis] Dropped testing Elasticsearch
  .travis.yml
  bin/.travis/init_elasticsearch.sh
Labels: Improvement

#2608 EZP-30458: Added more descriptive exception message
  eZ/Publish/Core/Search/Common/FieldRegistry.php
Labels: Improvement

#2640 [CI] Fixed AppVeyor memory issues
  appveyor.yml
Labels: Improvement, Ready for review

#2527 EZP-30027: [REST] Fixed logical op. parsing for Criterions of the same type
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/TestCase.php
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/ViewTest.php
  eZ/Publish/Core/REST/Server/Input/Parser/Criterion/LogicalAnd.php
  eZ/Publish/Core/REST/Server/Input/Parser/Criterion/LogicalOperator.php
  eZ/Publish/Core/REST/Server/Input/Parser/Criterion/LogicalOr.php
  eZ/Publish/Core/REST/Server/Tests/Input/Parser/Criterion/LogicalAndTest.php
  eZ/Publish/Core/REST/Server/Tests/Input/Parser/Criterion/LogicalOrTest.php
Labels: Bug, QA approved

#2644 EZP-29858: Fix broken Core tests
  .travis.yml
  eZ/Bundle/EzPublishCoreBundle/Features/Content/content_preview.feature
  eZ/Bundle/EzPublishCoreBundle/Features/Context/ContentPreviewContext.php
Labels: Ready for MERGE

#2646 [Composer][6.7] Dropped mikey179/vfsStream from dev dependencies
  composer.json
Labels: Improvement

#2623 EZP-30508: Fixed Exception being thrown when previewing
  eZ/Bundle/EzPublishCoreBundle/EventListener/PreviewRequestListener.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/routing.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
  eZ/Publish/Core/MVC/Symfony/Controller/Content/PreviewController.php
  eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php
  eZ/Publish/Core/MVC/Symfony/View/Tests/Builder/ContentViewBuilderTest.php
Labels: Bug, QA approved

#2628 EZP-30470: Improved filtering Content Types and Languages based on permissions
  eZ/Publish/API/Repository/Tests/Limitation/PermissionResolver/ContentLimitationsMixIntegrationTest.php
  eZ/Publish/Core/Limitation/ContentTypeLimitationType.php
  eZ/Publish/Core/Limitation/LocationLimitationType.php
  eZ/Publish/Core/Limitation/ParentContentTypeLimitationType.php
  eZ/Publish/Core/Limitation/ParentDepthLimitationType.php
  eZ/Publish/Core/Limitation/ParentOwnerLimitationType.php
  eZ/Publish/Core/Limitation/ParentUserGroupLimitationType.php
  eZ/Publish/Core/Limitation/SubtreeLimitationType.php
  eZ/Publish/Core/Limitation/Tests/ContentTypeLimitationTypeTest.php
  eZ/Publish/SPI/Limitation/Target/Builder/VersionBuilder.php
  eZ/Publish/SPI/Limitation/Target/Version.php
  eZ/Publish/SPI/Tests/Limitation/Target/Builder/VersionBuilderTest.php
Labels: Bug, QA approved

#2642 EZP-30539: Moved Platform Behat Bundle to BehatBundle
  bin/extract-translations.sh
  composer.json
  doc/behat/README.md
  eZ/Bundle/EzPublishCoreBundle/Features/Context/BasicContentContext.php
  eZ/Bundle/EzPublishCoreBundle/Features/Context/ContentPreviewContext.php
  eZ/Bundle/EzPublishCoreBundle/Features/Context/ContentTypeContext.php
  eZ/Bundle/EzPublishCoreBundle/Features/Context/FieldTypeContext.php
  eZ/Bundle/EzPublishCoreBundle/Features/Context/QueryControllerContext.php
  eZ/Bundle/EzPublishCoreBundle/Features/Context/RoleContext.php
  eZ/Bundle/EzPublishCoreBundle/Features/Context/UserContext.php
  eZ/Bundle/PlatformBehatBundle/Command/CreateLanguageCommand.php
  eZ/Bundle/PlatformBehatBundle/Command/TestSiteaccessCommand.php
  eZ/Bundle/PlatformBehatBundle/Context/Argument/AnnotationArgumentResolver.php
  eZ/Bundle/PlatformBehatBundle/Context/RepositoryContext.php
  eZ/Bundle/PlatformBehatBundle/Context/SubContext/DeprecationNoticeSupressor.php
  eZ/Bundle/PlatformBehatBundle/Controller/ExceptionController.php
  eZ/Bundle/PlatformBehatBundle/DependencyInjection/EzPlatformBehatExtension.php
  eZ/Bundle/PlatformBehatBundle/EzPlatformBehatBundle.php
  eZ/Bundle/PlatformBehatBundle/Resources/config/routing.yml
  eZ/Bundle/PlatformBehatBundle/Resources/config/services.yml
  eZ/Bundle/PlatformBehatBundle/Resources/views/dump.html.twig
  eZ/Bundle/PlatformBehatBundle/ServiceContainer/EzBehatExtension.php
Labels: Improvement, Ready for MERGE

#2615 EZEE-2661: Allowed translation filtering when publishing version
  eZ/Publish/API/Repository/ContentService.php
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/ContentHandlerTest.php
  eZ/Publish/Core/REST/Client/ContentService.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
  eZ/Publish/Core/SignalSlot/ContentService.php
  eZ/Publish/Core/SignalSlot/Signal/ContentService/PublishVersionSignal.php
  eZ/Publish/Core/SignalSlot/Tests/ContentServiceTest.php
  eZ/Publish/Core/settings/storage_engines/legacy/content.yml
Labels: Improvement, QA approved
