Repository ezsystems/ezpublish-kernel, pull requests merged in 2019-04, with the labels that each got.

#2590 EZP-30367: Error: `Location cannot be displayed as it is flagged as invisible.`
  eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php
Labels: Ready for QA

#2604 EZP-30333: The host's port is added to image variations URIs when configured through image_host
  eZ/Bundle/EzPublishCoreBundle/Imagine/Cache/Resolver/ProxyResolver.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Cache/Resolver/ProxyResolverTest.php
Labels: Bug, Ready for QA

#2599 EZP-30298: As a Cluster User I want in-memory cache for all content related lookups
  eZ/Publish/Core/Persistence/Cache/AbstractInMemoryHandler.php
  eZ/Publish/Core/Persistence/Cache/Adapter/InMemoryClearingProxyAdapter.php
  eZ/Publish/Core/Persistence/Cache/ContentHandler.php
  eZ/Publish/Core/Persistence/Cache/LocationHandler.php
  eZ/Publish/Core/Persistence/Cache/Tests/AbstractBaseHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/Adapter/InMemoryClearingProxyAdapterTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/ContentHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/LocationHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/UrlAliasHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/UrlAliasHandler.php
  eZ/Publish/Core/settings/storage_engines/cache.yml
Labels: Improvement, Ready for QA

#2548 EZP-30061: Created integration tests schema using Schema Importer
  eZ/Publish/API/Repository/Tests/SetupFactory/Legacy.php
  eZ/Publish/Core/Persistence/Tests/DatabaseConnectionFactory.php
  eZ/Publish/Core/Repository/Tests/Service/Integration/Legacy/_fixtures/clean_ezdemo_47_dump.php
  eZ/Publish/Core/settings/tests/integration_legacy.yml
  eZ/Publish/Core/settings/tests/integration_legacy_elasticsearch.yml
Labels: Feature, Ready for MERGE

#2602 EZP-30281: Added deprecation info to Core RichText FT namespace
  doc/bc/changes-7.4.md
  eZ/Publish/Core/FieldType/RichText/Converter.php
  eZ/Publish/Core/FieldType/RichText/Converter/Aggregate.php
  eZ/Publish/Core/FieldType/RichText/Converter/Link.php
  eZ/Publish/Core/FieldType/RichText/Converter/ProgramListing.php
  eZ/Publish/Core/FieldType/RichText/Converter/Render.php
  eZ/Publish/Core/FieldType/RichText/Converter/Render/Embed.php
  eZ/Publish/Core/FieldType/RichText/Converter/Render/Template.php
  eZ/Publish/Core/FieldType/RichText/Converter/Xslt.php
  eZ/Publish/Core/FieldType/RichText/ConverterDispatcher.php
  eZ/Publish/Core/FieldType/RichText/CustomTagsValidator.php
  eZ/Publish/Core/FieldType/RichText/InternalLinkValidator.php
  eZ/Publish/Core/FieldType/RichText/Normalizer.php
  eZ/Publish/Core/FieldType/RichText/Normalizer/Aggregate.php
  eZ/Publish/Core/FieldType/RichText/Normalizer/DocumentTypeDefinition.php
  eZ/Publish/Core/FieldType/RichText/README.md
  eZ/Publish/Core/FieldType/RichText/RendererInterface.php
  eZ/Publish/Core/FieldType/RichText/RichTextStorage/Gateway.php
  eZ/Publish/Core/FieldType/RichText/SearchField.php
  eZ/Publish/Core/FieldType/RichText/Type.php
  eZ/Publish/Core/FieldType/RichText/Validator.php
  eZ/Publish/Core/FieldType/RichText/ValidatorDispatcher.php
  eZ/Publish/Core/FieldType/RichText/Value.php
  eZ/Publish/Core/FieldType/RichText/XmlBase.php
Labels: Bug, Ready for MERGE

#2612 [Tests] Called DbPlatform::addEventSubscribers prior to connecting
  eZ/Publish/Core/Persistence/Tests/DatabaseConnectionFactory.php
Labels: Bug

#2585 EZP-30344: Allowed limiting Content management to specific translations
  doc/bc/changes-7.5.md
  eZ/Publish/API/Repository/PermissionResolver.php
  eZ/Publish/API/Repository/Tests/BaseTest.php
  eZ/Publish/API/Repository/Tests/Limitation/PermissionResolver/BaseLimitationIntegrationTest.php
  eZ/Publish/API/Repository/Tests/Limitation/PermissionResolver/ContentLimitationsMixIntegrationTest.php
  eZ/Publish/API/Repository/Tests/Limitation/PermissionResolver/LanguageLimitationIntegrationTest.php
  eZ/Publish/API/Repository/Tests/PermissionResolverTest.php
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/LanguageLimitationTest.php
  eZ/Publish/API/Repository/Values/User/LookupLimitationResult.php
  eZ/Publish/API/Repository/Values/User/LookupPolicyLimitations.php
  eZ/Publish/Core/Limitation/LanguageLimitationType.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/Permission/CachedPermissionService.php
  eZ/Publish/Core/Repository/Permission/PermissionResolver.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
  eZ/Publish/Core/settings/roles.yml
  eZ/Publish/SPI/Limitation/Target.php
  eZ/Publish/SPI/Limitation/Target/Builder/VersionBuilder.php
  eZ/Publish/SPI/Limitation/Target/Version.php
  eZ/Publish/SPI/Limitation/TargetAwareType.php
  eZ/Publish/SPI/Tests/Limitation/Target/Builder/VersionBuilderTest.php
  phpunit-integration-legacy.xml
Labels: Feature, QA approved

#2598 EZP-29694: Copied translations from published version to draft
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/FieldHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/ContentHandlerTest.php
  eZ/Publish/Core/settings/storage_engines/legacy/content.yml
Labels: Improvement, QA approved

#2613 Bumped minimal Symfony version to reduce Composer's work
  .travis.yml
  composer.json
Labels: Ready for MERGE

#2620 Fixed SOLR integration tests with dedicated cores setup fails on ContentServiceTest::testCopyTranslationsFromPublishedToDraft
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
Labels: Bug
