Repository ezsystems/ezpublish-kernel, pull requests merged in 2019-06, with the labels that each got.

#2629 EZP-30503: Changed names of base layout parameters
  doc/bc/changes-8.0.md
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/Common.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/full.html.twig
  eZ/Publish/Core/MVC/Symfony/Controller/Content/ViewController.php
  eZ/Publish/Core/MVC/Symfony/View/Manager.php
  eZ/Publish/Core/MVC/Symfony/View/ParametersInjector/NoLayout.php
  eZ/Publish/Core/MVC/Symfony/View/ParametersInjector/ViewbaseLayout.php
  eZ/Publish/Core/MVC/Symfony/View/Tests/ViewManagerTest.php
Labels: Improvement, Ready for review

#2652 EZP-30573: As a Developer I want to filter by status when using ContentService::loadVersions method
  eZ/Publish/API/Repository/ContentService.php
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/Core/REST/Client/ContentService.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
  eZ/Publish/Core/SignalSlot/ContentService.php
  eZ/Publish/Core/SignalSlot/Tests/ContentServiceTest.php
Labels: Improvement, QA approved

#2664 EZP-30635: Fixed infinite loop in Reindex Command on the last iteration
  eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php
Labels: Bug

#2667 EZP-30643: Images are stored under wrong path
  eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
Labels: Bug, QA approved

#2665 EZP-29301: Added class and data attributes support for embed(inline)
  eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/embed_inline.html.twig
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/DataAttributesExtensionTest.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/_fixtures/filters/ez_data_attributes_serialize.test
  eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/DataAttributesExtension.php
Labels: Feature, QA approved

#2635 EZP-30547: As a Developer I'd like to be able to debug config resolver & services
  eZ/Bundle/EzPublishCoreBundle/Command/DebugConfigResolverCommand.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/commands.yml
Labels: Ready for QA

#2657 EZP-30613: Implemented abstract decorators to reduce code required for new Repository layers
  eZ/Publish/SPI/Repository/Decorator/BookmarkServiceDecorator.php
  eZ/Publish/SPI/Repository/Decorator/ContentServiceDecorator.php
  eZ/Publish/SPI/Repository/Decorator/ContentTypeServiceDecorator.php
  eZ/Publish/SPI/Repository/Decorator/FieldTypeServiceDecorator.php
  eZ/Publish/SPI/Repository/Decorator/LanguageServiceDecorator.php
  eZ/Publish/SPI/Repository/Decorator/LocationServiceDecorator.php
  eZ/Publish/SPI/Repository/Decorator/NotificationServiceDecorator.php
  eZ/Publish/SPI/Repository/Decorator/ObjectStateServiceDecorator.php
  eZ/Publish/SPI/Repository/Decorator/RoleServiceDecorator.php
  eZ/Publish/SPI/Repository/Decorator/SearchServiceDecorator.php
  eZ/Publish/SPI/Repository/Decorator/SectionServiceDecorator.php
  eZ/Publish/SPI/Repository/Decorator/TranslationServiceDecorator.php
  eZ/Publish/SPI/Repository/Decorator/TrashServiceDecorator.php
  eZ/Publish/SPI/Repository/Decorator/URLAliasServiceDecorator.php
  eZ/Publish/SPI/Repository/Decorator/URLServiceDecorator.php
  eZ/Publish/SPI/Repository/Decorator/URLWildcardServiceDecorator.php
  eZ/Publish/SPI/Repository/Decorator/UserPreferenceServiceDecorator.php
  eZ/Publish/SPI/Repository/Decorator/UserServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/BookmarkServiceDecoratorTest.php
  eZ/Publish/SPI/Repository/Tests/Decorator/ContentServiceDecoratorTest.php
  eZ/Publish/SPI/Repository/Tests/Decorator/ContentTypeServiceDecoratorTest.php
  eZ/Publish/SPI/Repository/Tests/Decorator/FieldTypeServiceDecoratorTest.php
  eZ/Publish/SPI/Repository/Tests/Decorator/LanguageServiceDecoratorTest.php
  eZ/Publish/SPI/Repository/Tests/Decorator/LocationServiceDecoratorTest.php
  eZ/Publish/SPI/Repository/Tests/Decorator/NotificationServiceDecoratorTest.php
  eZ/Publish/SPI/Repository/Tests/Decorator/ObjectStateServiceDecoratorTest.php
  eZ/Publish/SPI/Repository/Tests/Decorator/RoleServiceDecoratorTest.php
  eZ/Publish/SPI/Repository/Tests/Decorator/SearchServiceDecoratorTest.php
  eZ/Publish/SPI/Repository/Tests/Decorator/SectionServiceDecoratorTest.php
  eZ/Publish/SPI/Repository/Tests/Decorator/TranslationServiceDecoratorTest.php
  eZ/Publish/SPI/Repository/Tests/Decorator/TrashServiceDecoratorTest.php
  eZ/Publish/SPI/Repository/Tests/Decorator/URLAliasServiceDecoratorTest.php
  eZ/Publish/SPI/Repository/Tests/Decorator/URLServiceDecoratorTest.php
  eZ/Publish/SPI/Repository/Tests/Decorator/URLWildcardServiceDecoratorTest.php
  eZ/Publish/SPI/Repository/Tests/Decorator/UserPreferenceServiceDecoratorTest.php
  eZ/Publish/SPI/Repository/Tests/Decorator/UserServiceDecoratorTest.php
Labels: Feature, Ready for MERGE

#2647 [CS] Bumped php-cs-fixer to v2.15.0
  .php_cs
  .travis.yml
  composer.json
  eZ/Bundle/EzPublishCoreBundle/Command/DebugConfigResolverCommand.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver.php
  eZ/Publish/API/Repository/Tests/BaseTest.php
  eZ/Publish/Core/FieldType/RichText/Converter/Link.php
  eZ/Publish/Core/MVC/Symfony/Matcher/MatcherInterface.php
  eZ/Publish/Core/Repository/Helper/RoleDomainMapper.php
  eZ/Publish/Core/Search/Elasticsearch/Content/SortClauseVisitor/Field/MapLocationDistance.php
Labels: Improvement

#2653 EZP-30462: Unified Field Type service tag names
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/FieldTypeParameterProviderRegistryPass.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/FieldTypeParameterProviderRegistryPassTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
  eZ/Publish/Core/Base/Container/Compiler/FieldTypeCollectionPass.php
  eZ/Publish/Core/Base/Container/Compiler/Search/FieldRegistryPass.php
  eZ/Publish/Core/Base/Container/Compiler/Storage/Legacy/FieldValueConverterRegistryPass.php
  eZ/Publish/Core/Base/Tests/Container/Compiler/FieldTypeCollectionPassTest.php
  eZ/Publish/Core/Base/Tests/Container/Compiler/Storage/Legacy/FieldValueConverterRegistryPassTest.php
  eZ/Publish/Core/settings/fieldtypes.yml
  eZ/Publish/Core/settings/indexable_fieldtypes.yml
  eZ/Publish/Core/settings/richtext/fieldtypes.yml
  eZ/Publish/Core/settings/richtext/indexable_fieldtypes.yml
  eZ/Publish/Core/settings/richtext/storage_engines/legacy/field_value_converters.yml
  eZ/Publish/Core/settings/search_engines/common.yml
  eZ/Publish/Core/settings/storage_engines/legacy/field_value_converters.yml
Labels: Improvement, QA approved

#2637 EZP-30548: Added support for Romanian special characters
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/Core/Persistence/Tests/TransformationProcessor/_fixtures/transformations/latin.tr
  eZ/Publish/Core/Persistence/Tests/TransformationProcessor/_fixtures/transformations/latin.tr.result
Labels: Improvement, QA approved

#2609 EZP-28633: Implemented support for custom wildcard URLs
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/url_wildcard.yml
  eZ/Publish/Core/MVC/Symfony/Routing/UrlWildcardRouter.php
  eZ/Publish/Core/Persistence/Cache/Handler.php
  eZ/Publish/Core/Persistence/Cache/Tests/AbstractBaseHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/PersistenceHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/UrlWildcardHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Mapper.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/UrlWildcardTest.php
  eZ/Publish/Core/Repository/URLWildcardService.php
  eZ/Publish/Core/settings/storage_engines/cache.yml
  eZ/Publish/SPI/Persistence/Content/UrlWildcard/Handler.php
Labels: Feature, QA approved, Ready for MERGE

#2663 EZP-30627: Unified Twig helpers naming
  doc/bc/changes-8.0.md
  doc/specifications/template/ez_functions.md
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/FieldDefinitionSettingsTemplates.php
  eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/asset_image.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/embed_image.html.twig
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/_fixtures/content_functions/ez_is_field_empty.test
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/_fixtures/content_functions/ez_trans_prop.test
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/_fixtures/field_rendering_functions/ez_render_fielddefinition_settings.test
  eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/ContentExtension.php
  eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/CoreExtension.php
  eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/FieldRenderingExtension.php
  eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/ImageExtension.php
  eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/RichTextExtension.php
Labels: Improvement, Ready for review

#2673 EZP-30647: Refactored View Matcher Factory to use ConfigResolver
  eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
  eZ/Publish/Core/MVC/Symfony/Matcher/ClassNameMatcherFactory.php
  eZ/Publish/Core/MVC/Symfony/Matcher/ConfigurableMatcherFactoryInterface.php
  eZ/Publish/Core/MVC/Symfony/Matcher/DynamicallyConfiguredMatcherFactoryDecorator.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/DynamicallyConfiguredMatcherFactoryDecoratorTest.php
Labels: Bug, QA approved

#2677 EZP-30457: FieldType::getSortInfo should be implemented by impl. only if the FT is sortable
  eZ/Publish/Core/FieldType/FieldType.php
Labels: DX, Feature

#2676 EZP-30699: Made image rendering services used by Twig extensions lazy
  eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
Labels: Bug, QA approved
