Repository ezsystems/ezpublish-kernel, pull requests merged in 2019-11, with the labels that each got.

#2692 EZP-30733: CleanupVersionsCommand should use new ContentService::loadVersions status argument for better performance
  eZ/Bundle/EzPublishCoreBundle/Command/CleanupVersionsCommand.php
  eZ/Publish/Core/Persistence/Cache/ContentHandler.php
Labels: Improvement, QA approved, Ready for MERGE

#2852 EZP-31094: Introduced strict types for SearchService
  eZ/Publish/API/Repository/SearchService.php
  eZ/Publish/Core/Repository/SearchService.php
  eZ/Publish/Core/Repository/SiteAccessAware/SearchService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/SearchServiceTest.php
  eZ/Publish/SPI/Repository/Decorator/SearchServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/SearchServiceDecoratorTest.php
  eZ/Publish/SPI/Search/Capable.php
Labels: DX, Improvement, QA approved

#2851 EZP-31093: Introduced strict types for TrashService
  eZ/Publish/API/Repository/TrashService.php
  eZ/Publish/Core/Event/TrashService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/TrashServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/TrashService.php
  eZ/Publish/Core/Repository/TrashService.php
  eZ/Publish/SPI/Repository/Decorator/TrashServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/TrashServiceDecoratorTest.php
Labels: DX, Improvement, QA approved

#2853 EZP-31095: Introduced strict types for FieldTypeService
  eZ/Publish/API/Repository/FieldTypeService.php
  eZ/Publish/Core/Helper/Tests/FieldHelperTest.php
  eZ/Publish/Core/Repository/FieldTypeService.php
  eZ/Publish/SPI/Repository/Decorator/FieldTypeServiceDecorator.php
Labels: DX, Improvement, QA approved

#2855 EZP-31098: Introduced strict types for URLWildcardService
  eZ/Publish/API/Repository/URLWildcardService.php
  eZ/Publish/Core/Event/URLWildcardService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/UrlWildcardTest.php
  eZ/Publish/Core/Repository/URLWildcardService.php
  eZ/Publish/SPI/Repository/Decorator/URLWildcardServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/URLWildcardServiceDecoratorTest.php
Labels: DX, Improvement, QA approved

#2848 EZP-31114: Added "skip-indexing" option for install command
  eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php
Labels: Improvement, QA approved

#2847 EZP-31084: Memory exhausted / timeout on too many items in the trash - part 1
  eZ/Publish/API/Repository/Tests/TrashServiceTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/TrashHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/TrashHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Trash/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/Gateway/DoctrineDatabaseTrashTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/TrashHandlerTest.php
  eZ/Publish/Core/Repository/TrashService.php
  eZ/Publish/SPI/Persistence/Content/Location/Trash/Handler.php
  eZ/Publish/SPI/Persistence/Content/Location/Trash/TrashResult.php
Labels: Bug, Ready for QA

#2871 EZP-31084: Fix infinitive loop in cache emptyTrash()
  eZ/Publish/Core/Persistence/Cache/Tests/TrashHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/TrashHandler.php
Labels: QA approved

#2865 EZP-31115: Added `isHidden` flag to `ContentInfo` in REST response
  doc/specifications/rest/REST-API-V2.rst
  eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/RestContent.php
  eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/RestContentTest.php
Labels: QA approved

#2856 EZP-31103: Introduced strict types for ContentTypeService
  eZ/Publish/API/Repository/ContentTypeService.php
  eZ/Publish/Core/Event/ContentTypeService.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/ContentExtensionTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Repository/ContentTypeService.php
  eZ/Publish/Core/Repository/SiteAccessAware/ContentTypeService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentTypeServiceTest.php
  eZ/Publish/SPI/Repository/Decorator/ContentTypeServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/ContentTypeServiceDecoratorTest.php
Labels: DX, Improvement, QA approved

#2867 EZP-31119: Fixed usage of deprecated ContainerAwareCommand class in CheckURLsCommand
  eZ/Bundle/EzPublishCoreBundle/Command/CheckURLsCommand.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/commands.yml
Labels: Improvement, QA approved

#2854 EZP-31097: Introduced strict types for URLService
  eZ/Publish/API/Repository/Tests/URLServiceTest.php
  eZ/Publish/API/Repository/URLService.php
  eZ/Publish/Core/Event/URLService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/UrlTest.php
  eZ/Publish/Core/Repository/URLService.php
  eZ/Publish/SPI/Repository/Decorator/URLServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/URLServiceDecoratorTest.php
Labels: DX, Improvement, QA approved

#2880 EZP-31030: Introduced strict types for SectionService
  eZ/Publish/API/Repository/SectionService.php
  eZ/Publish/Core/Event/SectionService.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Identifier/SectionTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/Section/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Repository/SectionService.php
  eZ/Publish/Core/Repository/SiteAccessAware/SectionService.php
  eZ/Publish/SPI/Repository/Decorator/SectionServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/SectionServiceDecoratorTest.php
Labels: DX, Improvement, QA approved

#2838 EZP-31044: Implemented SiteAccess providers
  doc/bc/changes-8.0.md
  eZ/Bundle/EzPublishCoreBundle/EventListener/ConsoleCommandListener.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/routing.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/ConsoleCommandListenerTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/RequestEventListenerTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/RoutingListenerTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/SessionInitByPostListenerTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/SessionSetDynamicNameListenerTest.php
  eZ/Publish/API/Repository/Tests/Regression/EZP22840RoleLimitations.php
  eZ/Publish/Core/Limitation/Tests/SiteAccessLimitationTypeTest.php
  eZ/Publish/Core/MVC/Exception/InvalidSiteAccessException.php
  eZ/Publish/Core/MVC/Symfony/EventListener/Tests/SiteAccessMatchListenerTest.php
  eZ/Publish/Core/MVC/Symfony/Security/Tests/EventListener/SecurityListenerTest.php
  eZ/Publish/Core/MVC/Symfony/Security/Tests/HttpUtilsTest.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Provider/ChainSiteAccessProvider.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Provider/StaticSiteAccessProvider.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Router.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/SiteAccessProviderInterface.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/Provider/ChainSiteAccessProviderTest.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterBaseTest.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterHostElementTest.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterHostPortURITest.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterHostRegexTest.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterHostTextTest.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterPortHostURITest.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterSpecialPortsTest.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterTest.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterURIElement2Test.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterURIElementTest.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterURIRegexTest.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/RouterURITextTest.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/SiteAccessSetting.php
Labels: Improvement, QA approved

#2877 [Composer] Added missing ext-dom requirement
  composer.json
Labels: DX, Improvement, Ready for MERGE

#2870 EZP-31122: Added explicitlyHidden flag to Location in REST response
  eZ/Publish/API/Repository/Values/Content/Location.php
  eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/RestLocation.php
  eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/RestLocationRootNodeTest.php
  eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/RestLocationTest.php
Labels: Improvement, QA approved

#2869 [Travis] Fix memory issues during build
  .travis.yml
  bin/.travis/enable_swap.sh
  bin/.travis/prepare_behat.sh
  composer.json
Labels: Ready for review

#2887 Fixed Query Controller tests
  eZ/Bundle/EzPublishCoreBundle/Features/Context/QueryControllerContext.php
  eZ/Bundle/EzPublishCoreBundle/Features/QueryController/query_controller.feature
Labels: Ready for MERGE

#2875 EZP-30936: Added option to create content draft in provided Language
  doc/upgrade/7.5.md
  eZ/Publish/API/Repository/ContentService.php
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/Core/Persistence/Cache/ContentHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Mapper.php
  eZ/Publish/Core/REST/Client/ContentService.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentServiceTest.php
  eZ/Publish/Core/SignalSlot/ContentService.php
  eZ/Publish/Core/SignalSlot/Signal/ContentService/CreateContentDraftSignal.php
  eZ/Publish/Core/SignalSlot/Tests/ContentServiceTest.php
  eZ/Publish/Core/SignalSlot/Tests/ServiceTest.php
  eZ/Publish/SPI/Persistence/Content/Handler.php
Labels: Improvement, QA approved, Ready for MERGE
