Repository ezsystems/ezpublish-kernel, pull requests merged in 2019-07, with the labels that each got.

#2605 EZP-28898: Implemented Random SortClause for LSE
  eZ/Publish/API/Repository/Tests/SearchServiceTest.php
  eZ/Publish/API/Repository/Values/Content/Query/SortClause/Random.php
  eZ/Publish/API/Repository/Values/Content/Query/SortClause/Target/RandomTarget.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Gateway/RandomSortClauseHandlerFactoryTest.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/SortClauseHandler/AbstractRandom.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/SortClauseHandler/Factory/RandomSortClauseHandlerFactory.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/SortClauseHandler/Random/MySqlRandom.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/SortClauseHandler/Random/PgSqlRandom.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/SortClauseHandler/Random/SqlLiteRandom.php
  eZ/Publish/Core/settings/search_engines/legacy/sort_clause_handlers_common.yml
Labels: Feature, QA approved

#2648 [CS][Travis] Added Code Style checking job to Travis
  .travis.yml
  bin/.travis/check_code_style.sh
  bin/.travis/prepare_unittest.sh
Labels: Improvement, Ready for MERGE

#2674 EZP-30696: Changed Repository::sudo typehint form self to Repository
  .php_cs
  eZ/Publish/API/Repository/Repository.php
Labels: Improvement, Ready for MERGE

#2654 EZP-30585: Dropped unused translation methods from inner ContentService
  eZ/Publish/Core/REST/Client/ContentService.php
  eZ/Publish/Core/SignalSlot/ContentService.php
  eZ/Publish/Core/SignalSlot/Signal/ContentService/AddTranslationInfoSignal.php
  eZ/Publish/Core/SignalSlot/Signal/ContentService/TranslateVersionSignal.php
Labels: Improvement, Ready for MERGE

#2686 Fixed incorrect Value class import in RelationProcessor
  eZ/Publish/Core/Repository/Helper/RelationProcessor.php
Labels: Bug

#2685 [Tests] Fixed PHPUnit 8.x deprecated assertions warnings
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/API/Repository/Tests/LocationServiceTest.php
  eZ/Publish/API/Repository/Tests/ObjectStateServiceTest.php
  eZ/Publish/API/Repository/Tests/SearchServiceLocationTest.php
  eZ/Publish/API/Repository/Tests/SearchServiceTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/ContentTypeHandlerTest.php
Labels: Improvement

#2680 EZP-30503: Fixed missing default value for the new page_layout parameter
  doc/specifications/security/authentication_symfony.md
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/Common.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/CommonTest.php
  eZ/Publish/Core/MVC/Symfony/View/ParametersInjector/ViewbaseLayout.php
Labels: Bug, QA approved

#2698 fixed annotation typo y the persistence cache collector file
  eZ/Bundle/EzPublishDebugBundle/Collector/PersistenceCacheCollector.php
Labels: Ready for MERGE

#2632 EZP-30461: Implemented generic Field Type
  composer.json
  eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php
  eZ/Publish/Core/Base/Container/Compiler/FieldTypeCollectionPass.php
  eZ/Publish/Core/Base/Container/Compiler/GenericFieldTypeConverterPass.php
  eZ/Publish/Core/Base/Container/Compiler/Storage/Legacy/FieldValueConverterRegistryPass.php
  eZ/Publish/Core/Base/Tests/Container/Compiler/GenericFieldTypeConverterPassTest.php
  eZ/Publish/Core/Base/Tests/Container/Compiler/Storage/Legacy/FieldValueConverterRegistryPassTest.php
  eZ/Publish/Core/Base/Tests/Container/Compiler/Stubs/GenericFieldType.php
  eZ/Publish/Core/FieldType/Tests/FieldTypeTest.php
  eZ/Publish/Core/FieldType/Tests/Generic/ValueSerializer/SymfonySerializerAdapterTest.php
  eZ/Publish/Core/FieldType/ValueSerializer/SymfonySerializerAdapter.php
  eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/SerializableConverter.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/FieldValue/Converter/SerializableConverterTest.php
  eZ/Publish/Core/settings/fieldtypes.yml
  eZ/Publish/Core/settings/storage_engines/legacy/field_value_converters.yml
  eZ/Publish/Core/settings/tests/common.yml
  eZ/Publish/SPI/Exception/InvalidArgumentException.php
  eZ/Publish/SPI/Exception/InvalidArgumentType.php
  eZ/Publish/SPI/FieldType/Generic/Tests/GenericTest.php
  eZ/Publish/SPI/FieldType/Generic/Tests/Stubs/Type.php
  eZ/Publish/SPI/FieldType/Generic/Tests/Stubs/Value.php
  eZ/Publish/SPI/FieldType/Generic/Type.php
  eZ/Publish/SPI/FieldType/Generic/ValidationError/ConstraintViolationAdapter.php
  eZ/Publish/SPI/FieldType/Tests/FieldTypeTest.php
  eZ/Publish/SPI/FieldType/ValidationError/AbstractValidationError.php
  eZ/Publish/SPI/FieldType/ValidationError/NonConfigurableValidationError.php
  eZ/Publish/SPI/FieldType/ValidationError/UnknownValidatorValidationError.php
  eZ/Publish/SPI/FieldType/Value.php
  eZ/Publish/SPI/FieldType/ValueSerializerInterface.php
Labels: Feature, Ready for MERGE

#2700 EZP-30749: Passed explicitly event name to dispatcher
  eZ/Publish/API/Repository/Tests/LanguageServiceTest.php
  eZ/Publish/Core/Event/BookmarkService.php
  eZ/Publish/Core/Event/ContentService.php
  eZ/Publish/Core/Event/ContentTypeService.php
  eZ/Publish/Core/Event/LanguageService.php
  eZ/Publish/Core/Event/LocationService.php
  eZ/Publish/Core/Event/NotificationService.php
  eZ/Publish/Core/Event/ObjectStateService.php
  eZ/Publish/Core/Event/Repository.php
  eZ/Publish/Core/Event/RoleService.php
  eZ/Publish/Core/Event/SectionService.php
  eZ/Publish/Core/Event/Tests/BookmarkServiceTest.php
  eZ/Publish/Core/Event/Tests/ContentServiceTest.php
  eZ/Publish/Core/Event/Tests/ContentTypeServiceTest.php
  eZ/Publish/Core/Event/Tests/LanguageServiceTest.php
  eZ/Publish/Core/Event/Tests/LocationServiceTest.php
  eZ/Publish/Core/Event/Tests/NotificationServiceTest.php
  eZ/Publish/Core/Event/Tests/ObjectStateServiceTest.php
  eZ/Publish/Core/Event/Tests/RoleServiceTest.php
  eZ/Publish/Core/Event/Tests/SectionServiceTest.php
  eZ/Publish/Core/Event/Tests/TrashServiceTest.php
  eZ/Publish/Core/Event/Tests/URLAliasServiceTest.php
  eZ/Publish/Core/Event/Tests/URLServiceTest.php
  eZ/Publish/Core/Event/Tests/URLWildcardServiceTest.php
  eZ/Publish/Core/Event/Tests/UserPreferenceServiceTest.php
  eZ/Publish/Core/Event/Tests/UserServiceTest.php
  eZ/Publish/Core/Event/TrashService.php
  eZ/Publish/Core/Event/URLAliasService.php
  eZ/Publish/Core/Event/URLService.php
  eZ/Publish/Core/Event/URLWildcardService.php
  eZ/Publish/Core/Event/UserPreferenceService.php
  eZ/Publish/Core/Event/UserService.php
Labels: Bug

#2695 EZP-30745: Introduced new names for External Storage service tags
  eZ/Publish/Core/Base/Container/Compiler/Storage/ExternalStorageRegistryPass.php
  eZ/Publish/Core/Base/Tests/Container/Compiler/Storage/ExternalStorageRegistryPassTest.php
  eZ/Publish/Core/settings/fieldtype_external_storages.yml
  eZ/Publish/Core/settings/richtext/fieldtype_external_storages.yml
Labels: DX, Improvement

#2702 EZP-30571: Legacy storage column size for default TextField value is too short
  data/update/mysql/dbupdate-7.5.2-to-7.5.3.sql
  data/update/postgres/dbupdate-7.5.2-to-7.5.3.sql
  eZ/Bundle/EzPublishCoreBundle/Resources/config/storage/legacy/schema.yaml
Labels: Bug, QA approved, Ready for MERGE

#2704 [8.0] EZP-30571: Legacy storage column size for default TextField value is too short
  data/update/mysql/dbupdate-7.5.3-to-8.0.0.sql
  data/update/mysql/unstable/dbupdate-8.0.0-beta1-to-8.0.0-beta2.sql
  data/update/postgres/dbupdate-7.5.3-to-8.0.0.sql
  data/update/postgres/unstable/dbupdate-8.0.0-beta1-to-8.0.0-beta2.sql
Labels: Bug, Ready for review

#2703 EZP-30721: Implemented deferred tags invalidation and items deletion for transactions
  eZ/Publish/API/Repository/Tests/Regression/EnvTest.php
  eZ/Publish/Core/Persistence/Cache/AbstractInMemoryHandler.php
  eZ/Publish/Core/Persistence/Cache/AbstractInMemoryPersistenceHandler.php
  eZ/Publish/Core/Persistence/Cache/Adapter/TransactionAwareAdapterInterface.php
  eZ/Publish/Core/Persistence/Cache/Adapter/TransactionalCacheAdapterDecorator.php
  eZ/Publish/Core/Persistence/Cache/Tests/AbstractBaseHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/AbstractCacheHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/TransactionHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/TransactionHandler.php
  eZ/Publish/Core/settings/storage_engines/cache.yml
Labels: Bug, QA approved

#2701 EZP-30697: Fixed content creation under subtree when assignment limitation is used
  eZ/Publish/API/Repository/Tests/PermissionResolverTest.php
  eZ/Publish/Core/Limitation/SubtreeLimitationType.php
  eZ/Publish/Core/Repository/Permission/PermissionResolver.php
Labels: Bug, QA approved, Ready for MERGE

#2706 Fixed test which fails on PostgreSQL because it depends on items order
  eZ/Publish/API/Repository/Tests/PermissionResolverTest.php
Labels: Bug

#2705 EZP-30724: Allowed to load content type draft owned by any user via API
  eZ/Publish/API/Repository/ContentTypeService.php
  eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
  eZ/Publish/Core/REST/Client/ContentTypeService.php
  eZ/Publish/Core/Repository/ContentTypeService.php
  eZ/Publish/Core/Repository/SiteAccessAware/ContentTypeService.php
  eZ/Publish/Core/SignalSlot/ContentTypeService.php
  eZ/Publish/Core/SignalSlot/Tests/ContentTypeServiceTest.php
Labels: Improvement, QA approved, Ready for review

#2688 EZP-30529: Injected Field Types into Repository from DI Container
  eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/papi.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
  eZ/Publish/Core/Base/Container/ApiLoader/FieldTypeCollectionFactory.php
  eZ/Publish/Core/Base/Container/ApiLoader/RepositoryFactory.php
  eZ/Publish/Core/Base/Container/ApiLoader/Storage/FieldTypeRegistryFactory.php
  eZ/Publish/Core/Base/Container/Compiler/AbstractFieldTypeBasedPass.php
  eZ/Publish/Core/Base/Container/Compiler/FieldTypeRegistryPass.php
  eZ/Publish/Core/Base/Container/Compiler/GenericFieldTypeConverterPass.php
  eZ/Publish/Core/Base/Container/Compiler/Persistence/FieldTypeRegistryPass.php
  eZ/Publish/Core/Base/Tests/Container/Compiler/FieldTypeRegistryPassTest.php
  eZ/Publish/Core/Base/Tests/Container/Compiler/GenericFieldTypeConverterPassTest.php
  eZ/Publish/Core/FieldType/FieldTypeRegistry.php
  eZ/Publish/Core/MVC/Symfony/Translation/FieldTypesTranslationExtractor.php
  eZ/Publish/Core/Persistence/FieldTypeRegistry.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/FieldHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/HandlerTest.php
  eZ/Publish/Core/Persistence/Tests/FieldTypeRegistryTest.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/ContentTypeService.php
  eZ/Publish/Core/Repository/FieldTypeService.php
  eZ/Publish/Core/Repository/Helper/ContentTypeDomainMapper.php
  eZ/Publish/Core/Repository/Helper/DomainMapper.php
  eZ/Publish/Core/Repository/Helper/NameSchemaService.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/Tests/Helper/FieldTypeRegistryTest.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
  eZ/Publish/Core/settings/containerBuilder.php
  eZ/Publish/Core/settings/fieldtype_services.yml
  eZ/Publish/Core/settings/fieldtypes.yml
  eZ/Publish/Core/settings/repository/inner.yml
  eZ/Publish/Core/settings/storage_engines/common.yml
Labels: Improvement, QA approved

#2707 EZP-30753: Changed loadSections method to filter available sections
  eZ/Publish/API/Repository/SectionService.php
  eZ/Publish/API/Repository/Tests/SectionServiceAuthorizationTest.php
  eZ/Publish/Core/REST/Client/SectionService.php
  eZ/Publish/Core/Repository/SectionService.php
  eZ/Publish/Core/SignalSlot/SectionService.php
Labels: Bug, QA approved

#2711 [Travis] Bumped dist to Xenial to use MySQL 5.7
  .travis.yml
  bin/.travis/prepare_unittest.sh
Labels: Improvement, Work in progress

#2710 EZP-30739: Removed ExternalStorageRegistryFactory
  doc/bc/changes-8.0.md
  eZ/Publish/Core/Base/Container/ApiLoader/Storage/ExternalStorageRegistryFactory.php
  eZ/Publish/Core/Base/Container/Compiler/Storage/ExternalStorageRegistryPass.php
  eZ/Publish/Core/Base/Tests/Container/Compiler/Storage/ExternalStorageRegistryPassTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/StorageRegistry.php
  eZ/Publish/Core/settings/fieldtype_external_storages.yml
  eZ/Publish/Core/settings/storage_engines/common.yml
Labels: Improvement, QA approved

#2715 Fixed random error during the test with PostgreSQL
  eZ/Publish/API/Repository/Tests/PermissionResolverTest.php
Labels: Bug, QA approved, Ready for MERGE, Ready for review
