Repository ezsystems/ezpublish-kernel, pull requests merged in 2020-06, with the labels that each got.

#3041 EZP-31677: Added normalizer to decrese amount of data when compound matcher is encoded to JSON
  eZ/Bundle/EzPublishCoreBundle/Resources/config/routing.yml
  eZ/Publish/Core/MVC/Symfony/Component/Serializer/CompoundMatcherNormalizer.php
  eZ/Publish/Core/MVC/Symfony/Component/Serializer/SerializerTrait.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/MatcherSerializationTest.php
Labels: Bug, QA approved

#3040 EZEE-3159: Added support for items in the trash for SubtreeLimitationType
  eZ/Publish/API/Repository/Tests/TrashServiceTest.php
  eZ/Publish/Core/Limitation/SubtreeLimitationType.php
  eZ/Publish/Core/Persistence/Cache/LocationHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Mapper.php
  eZ/Publish/SPI/Persistence/Content/Location/Handler.php
Labels: Bug, QA approved

#3043 EZP-31680: Provided `languageCode` param to REST Views
  eZ/Publish/Core/REST/Server/Controller/Views.php
  eZ/Publish/Core/REST/Server/Input/Parser/ViewInput.php
  eZ/Publish/Core/REST/Server/Input/Parser/ViewInputOneDotOne.php
  eZ/Publish/Core/REST/Server/Values/RestViewInput.php
Labels: Improvement, Ready for review

#3045 Fixed code example in Criterion::getSpecifications docblock
  eZ/Publish/API/Repository/Values/Content/Query/Criterion.php
Labels: Bug
