Repository ezsystems/ezpublish-kernel, pull requests merged in 2020-05, with the labels that each got.

#2904 EZP-31248: Fixed handling non-printable characters for Search
  eZ/Publish/API/Repository/Tests/SearchServiceLocationTest.php
  eZ/Publish/Core/Search/Common/FieldValueMapper/StringMapper.php
Labels: Bug, QA approved

#3013 EZP-31240: Added ContentTranslationHandler for delete translation document in solr
  eZ/Publish/API/Repository/Tests/SearchService/DeleteTranslationTest.php
  eZ/Publish/Core/Search/Common/Slot/DeleteTranslation.php
  eZ/Publish/SPI/Search/ContentTranslationHandler.php
Labels: Bug, Ready for QA

#3027 [Travis] Changed notification key after rebranding
  .travis.yml
Labels: Ready for review

#3028 [Tests] Stopped relying on Location ID SortClause in testContentWithMultipleLocations
  eZ/Publish/API/Repository/Tests/SearchServiceTest.php
Labels: Bug, Ready for review

#3031 [Tests] Added SortClause in testFieldIsEmptyInLocation
  eZ/Publish/API/Repository/Tests/SearchServiceLocationTest.php
Labels: Improvement

#3037 EZP-31644: Fixed serialization of Compound SiteAccess matcher
  eZ/Bundle/EzPublishCoreBundle/Fragment/DecoratedFragmentRenderer.php
  eZ/Bundle/EzPublishCoreBundle/Fragment/InlineFragmentRenderer.php
  eZ/Bundle/EzPublishCoreBundle/Fragment/SiteAccessSerializationTrait.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Fragment/DecoratedFragmentRendererTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Fragment/FragmentRendererBaseTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Fragment/InlineFragmentRendererTest.php
  eZ/Publish/Core/MVC/Symfony/Component/Serializer/SerializerTrait.php
  eZ/Publish/Core/MVC/Symfony/EventListener/SiteAccessMatchListener.php
  eZ/Publish/Core/MVC/Symfony/EventListener/Tests/SiteAccessMatchListenerTest.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/HostText.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/Regex/Host.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/Regex/URI.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Matcher/URIText.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/MatcherSerializationTest.php
Labels: Bug

#3034 EZP-25484: Implemented dedicated strategy to map remote IDs for search
  bin/.travis/prepare_unittest.sh
  eZ/Publish/API/Repository/Tests/SearchService/DeleteTranslationTest.php
  eZ/Publish/API/Repository/Tests/SearchService/RemoteIdIndexingTest.php
  eZ/Publish/Core/Search/Common/FieldValueMapper/MultipleRemoteIdentifierMapper.php
  eZ/Publish/Core/Search/Common/FieldValueMapper/RemoteIdentifierMapper.php
  eZ/Publish/Core/Search/Tests/Common/FieldValueMapper/RemoteIdentifierMapperTest.php
  eZ/Publish/Core/settings/search_engines/field_value_mappers.yml
  eZ/Publish/SPI/Search/FieldType/MultipleRemoteIdentifierField.php
  eZ/Publish/SPI/Search/FieldType/RemoteIdentifierField.php
  phpunit-integration-legacy.xml
Labels: Bug, QA approved

#3036 EZP-30925: Added Language limitation to 'content remove' policy
  eZ/Publish/API/Repository/Tests/SearchService/DeleteTranslationTest.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/settings/policies.yml
Labels: Improvement, QA approved
