Repository ezsystems/ezpublish-kernel, pull requests merged in 2020-03, with the labels that each got.

#2967 Fixed Unit tests for 6.13 branch
  eZ/Publish/Core/settings/tests/integration_legacy.yml
  eZ/Publish/Core/settings/tests/integration_legacy_core.yml
Labels: Bug

#2973 EZP-31299: [Tests] Added missing language mask to initial test data
  eZ/Publish/Core/Repository/Tests/Service/Integration/Legacy/_fixtures/clean_ezdemo_47_dump.php
Labels: Bug

#2976 EZP-31451: Cleaned up Content Type update handlers
  doc/bc/changes-8.0.md
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Update/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Update/Handler/DeferredLegacy.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Update/Handler/DoctrineDatabase.php
  eZ/Publish/Core/settings/storage_engines/legacy/content_type.yml
Labels: Improvement, QA approved

#2929 Added ChainConfigResolver tests
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/ConfigResolver/ChainConfigResolverTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/ConfigResolver/ConfigResolverTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/ConfigResolver/DefaultScopeConfigResolverTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/ConfigResolver/GlobalScopeConfigResolverTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/ConfigResolver/SiteAccessGroupConfigResolverTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/ConfigResolver/StaticSiteAccessConfigResolverTest.php
Labels: Improvement

#2955 EZP-31002: Skipped Location check for ContentCreateStruct in ObjectStateLimitation
  eZ/Publish/Core/Limitation/ObjectStateLimitationType.php
  eZ/Publish/Core/Limitation/Tests/ObjectStateLimitationTypeTest.php
Labels: Bug, Ready for QA

#2952 EZP-31080: Created missing search Criterions
  eZ/Publish/API/Repository/Tests/SearchServiceTest.php
  eZ/Publish/API/Repository/Tests/_fixtures/Legacy/IsUserBasedFalse.php
  eZ/Publish/API/Repository/Tests/_fixtures/Legacy/IsUserBasedTrue.php
  eZ/Publish/API/Repository/Tests/_fixtures/Legacy/IsUserEnabledFalse.php
  eZ/Publish/API/Repository/Tests/_fixtures/Legacy/IsUserEnabledTrue.php
  eZ/Publish/API/Repository/Tests/_fixtures/Legacy/ObjectStateIdentifier.php
  eZ/Publish/API/Repository/Tests/_fixtures/Legacy/SectionIdentifier.php
  eZ/Publish/API/Repository/Tests/_fixtures/Legacy/UserEmail.php
  eZ/Publish/API/Repository/Tests/_fixtures/Legacy/UserIdEq.php
  eZ/Publish/API/Repository/Tests/_fixtures/Legacy/UserIdIn.php
  eZ/Publish/API/Repository/Tests/_fixtures/Legacy/UserLogin.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/IsUserBased.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/IsUserEnabled.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/ObjectStateIdentifier.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/SectionIdentifier.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/UserEmail.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/UserId.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/UserLogin.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/IsUserBased.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/IsUserEnabled.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/ObjectStateIdentifier.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/SectionIdentifier.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/UserEmail.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/UserId.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/UserLogin.php
  eZ/Publish/Core/settings/search_engines/legacy/criterion_handlers_common.yml
Labels: Feature, QA approved

#2966 EZP-31436: Fixed fetching configuration for SiteAccess group
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver/SiteAccessConfigResolver.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver/SiteAccessGroupConfigResolver.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/ConfigResolver/ChainConfigResolverTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/ConfigResolver/SiteAccessGroupConfigResolverTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/AbstractParserTestCase.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/CommonTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/IOTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/LanguagesTest.php
Labels: Bug, QA approved

#2980 [CS][Travis] Fixed Code Style check for branches
  bin/.travis/check_code_style.sh
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Filter/Loader/ScaleDownOnlyFilterLoaderTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Filter/Loader/ScaleHeightDownOnlyFilterLoaderTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Filter/Loader/ScaleWidthDownOnlyFilterLoaderTest.php
  eZ/Publish/Core/FieldType/Tests/BinaryBaseTest.php
  eZ/Publish/Core/FieldType/Tests/ImageTest.php
  eZ/Publish/Core/FieldType/Validator/FileExtensionBlackListValidator.php
  eZ/Publish/Core/FieldType/Validator/ImageValidator.php
  eZ/Publish/Core/settings/containerBuilder.php
  eZ/Publish/SPI/Tests/FieldType/BinaryFileIntegrationTest.php
  eZ/Publish/SPI/Tests/FieldType/ImageIntegrationTest.php
  eZ/Publish/SPI/Tests/FieldType/MediaIntegrationTest.php
Labels: Bug, Ready for QA

#2958 EZP-31415: Impl. composite & sibling criterion
  eZ/Publish/API/Repository/Tests/SearchServiceTest.php
  eZ/Publish/API/Repository/Tests/_fixtures/Legacy/Sibling.php
  eZ/Publish/API/Repository/Tests/_fixtures/Solr/Sibling.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/CompositeCriterion.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/Sibling.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/CompositeCriterion.php
  eZ/Publish/Core/settings/search_engines/legacy/criterion_handlers_common.yml
Labels: DX, Feature, QA approved

#2982 EZP-31299: Added semicolon in dbupdate-7.5.6-to-7.5.7.sql
  data/update/mysql/dbupdate-7.5.6-to-7.5.7.sql
  data/update/postgres/dbupdate-7.5.6-to-7.5.7.sql
Labels: Bug

#2866 EZP-31118: Introduced strict types for ContentService
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/ImageAsset/AliasGeneratorTest.php
  eZ/Publish/API/Repository/ContentService.php
  eZ/Publish/Core/Event/ContentService.php
  eZ/Publish/Core/FieldType/ImageAsset/Type.php
  eZ/Publish/Core/FieldType/Relation/Type.php
  eZ/Publish/Core/MVC/Symfony/FieldType/Relation/ParameterProvider.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/SearchService.php
  eZ/Publish/Core/Repository/SiteAccessAware/ContentService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/ContentServiceTest.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/SearchTest.php
  eZ/Publish/Core/Repository/TrashService.php
  eZ/Publish/Core/Repository/UserService.php
  eZ/Publish/SPI/Repository/Decorator/ContentServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/ContentServiceDecoratorTest.php
Labels: DX, Improvement, QA approved

#2983 EZP-31477: Fixed loading Site Accesses on limitation list
  eZ/Publish/Core/Limitation/SiteAccessLimitationType.php
  eZ/Publish/Core/Limitation/Tests/SiteAccessLimitationTypeTest.php
  eZ/Publish/Core/settings/roles.yml
  eZ/Publish/Core/settings/tests/common.yml
Labels: Improvement, QA approved

#2990 [Travis] Specified PHP dev image for jobs using full product setup
  .travis.yml
Labels: Ready for review

#2920 EZP-31088: Refactored Language GW to use Doctrine\DBAL
  eZ/Publish/API/Repository/Tests/LanguageServiceTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/Language/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Language/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Language/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Language/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
  eZ/Publish/Core/settings/storage_engines/legacy/language.yml
Labels: Improvement, Ready for QA

#2925 EZP-31088: Refactored Section GW methods to use Doctrine\DBAL
  eZ/Publish/Core/Persistence/Legacy/Content/Section/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Section/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Section/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/Section/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Section/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/settings/storage_engines/legacy/section.yml
Labels: Improvement, Ready for QA

#2951 EZP-31088: Refactored ObjectState GW methods to use Doctrine\DBAL
  eZ/Publish/Core/Persistence/Legacy/Content/ObjectState/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/ObjectState/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/ObjectState/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/ObjectState/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/settings/storage_engines/legacy/object_state.yml
Labels: Improvement, Ready for QA

#2845 EZP-31088: Refactored Content GW to use Doctrine\DBAL
  eZ/Publish/API/Repository/Tests/FieldType/BaseIntegrationTest.php
  eZ/Publish/API/Repository/Tests/Values/User/Limitation/ObjectStateLimitationTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase/QueryBuilder.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/Language/MaskGenerator.php
  eZ/Publish/Core/Persistence/Legacy/SharedGateway/DatabasePlatform/FallbackGateway.php
  eZ/Publish/Core/Persistence/Legacy/SharedGateway/DatabasePlatform/SqliteGateway.php
  eZ/Publish/Core/Persistence/Legacy/SharedGateway/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/SharedGateway/GatewayFactory.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/ContentUpdater/Action/RemoveFieldTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/_fixtures/extract_version_info_from_rows_multiple_versions.php
  eZ/Publish/Core/Persistence/Legacy/Tests/SharedGateway/GatewayFactoryTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/TestCase.php
  eZ/Publish/Core/settings/storage_engines/legacy.yml
  eZ/Publish/Core/settings/storage_engines/legacy/content.yml
  eZ/Publish/Core/settings/storage_engines/legacy/shared_gateway.yaml
  eZ/Publish/SPI/Persistence/Content/Field.php
Labels: Improvement, Ready for QA, Rebase required

#2975 EZP-31088: Refactored Content Type GW to use Doctrine\DBAL
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/AbstractTestCase.php
  eZ/Publish/Core/settings/storage_engines/legacy/content_type.yml
Labels: Improvement, Ready for QA, Rebase required

#2949 EZP-31088: Refactored Location gateway methods to use Doctrine\DBAL
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Content/TreeHandler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Location/Gateway/DoctrineDatabaseTrashTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/LocationHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
  eZ/Publish/Core/settings/storage_engines/legacy/location.yml
  eZ/Publish/SPI/Persistence/Content/Location/Handler.php
Labels: Improvement, Ready for QA

#2953 EZP-31088: Refactored UrlAlias GW methods to use Doctrine\DBAL
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
  eZ/Publish/Core/settings/storage_engines/legacy/url_alias.yml
Labels: Improvement, Ready for QA

#2964 EZP-31088: Refactored UrlWildcard GW to use Doctrine\DBAL
  eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlWildcard/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlWildcard/UrlWildcardHandlerTest.php
  eZ/Publish/Core/settings/storage_engines/legacy/url_wildcard.yml
Labels: Improvement, Ready for QA

#2961 EZP-31088: Refactored User GW to use Doctrine\DBAL
  eZ/Publish/Core/Persistence/Legacy/Tests/User/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/User/UserHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/User/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/User/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/User/Gateway/ExceptionConversion.php
  eZ/Publish/Core/settings/storage_engines/legacy/user.yml
Labels: Improvement, Ready for QA

#2963 EZP-31088: Refactored User Role GW to use Doctrine\DBAL
  eZ/Publish/Core/Persistence/Legacy/Tests/User/Role/Gateway/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/User/UserHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/User/Role/Gateway/ExceptionConversion.php
  eZ/Publish/Core/settings/storage_engines/legacy/user.yml
Labels: Improvement, Ready for QA

#2970 EZP-31440: Simplified non content/location related Query Types rendering
  eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
  eZ/Publish/Core/MVC/Symfony/Controller/QueryRenderController.php
  eZ/Publish/Core/MVC/Symfony/Controller/Tests/QueryRenderControllerTest.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/QueryRenderingExtensionTest.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/_fixtures/query_rendering_functions/ez_render_content_query.test
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/_fixtures/query_rendering_functions/ez_render_content_query_esi.test
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/_fixtures/query_rendering_functions/ez_render_location_query.test
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/_fixtures/query_rendering_functions/ez_render_location_query_esi.test
  eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/QueryRenderingExtension.php
  eZ/Publish/Core/MVC/Symfony/View/QueryView.php
  eZ/Publish/Core/Pagination/Pagerfanta/AdapterFactory/SearchHitAdapterFactory.php
  eZ/Publish/Core/Pagination/Pagerfanta/AdapterFactory/SearchHitAdapterFactoryInterface.php
  eZ/Publish/Core/Pagination/Tests/AdapterFactory/SearchHitAdapterFactoryTest.php
  eZ/Publish/Core/Query/QueryFactory.php
  eZ/Publish/Core/Query/QueryFactoryInterface.php
  eZ/Publish/Core/Query/Tests/QueryFactoryTest.php
Labels: DX, Feature, Ready for QA

#2938 EZP-31107: Built-in query types for site building
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/query_types.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/sort_spec.yml
  eZ/Publish/Core/QueryType/BuiltIn/AbstractLocationQueryType.php
  eZ/Publish/Core/QueryType/BuiltIn/AbstractQueryType.php
  eZ/Publish/Core/QueryType/BuiltIn/AncestorsQueryType.php
  eZ/Publish/Core/QueryType/BuiltIn/ChildrenQueryType.php
  eZ/Publish/Core/QueryType/BuiltIn/GeoLocationQueryType.php
  eZ/Publish/Core/QueryType/BuiltIn/RelatedToContentQueryType.php
  eZ/Publish/Core/QueryType/BuiltIn/SiblingsQueryType.php
  eZ/Publish/Core/QueryType/BuiltIn/SortClausesFactory.php
  eZ/Publish/Core/QueryType/BuiltIn/SortClausesFactoryInterface.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/Exception/SyntaxErrorException.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/Exception/UnsupportedSortClauseException.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/SortClauseParser/DefaultSortClauseParser.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/SortClauseParser/FieldSortClauseParser.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/SortClauseParser/MapDistanceSortClauseParser.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/SortClauseParser/RandomSortClauseParser.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/SortClauseParserDispatcher.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/SortClauseParserInterface.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/SortSpecLexer.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/SortSpecLexerInterface.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/SortSpecParser.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/SortSpecParserInterface.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/Tests/SortClauseParser/DefaultSortClauseParserTest.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/Tests/SortClauseParser/FieldSortClauseParserTest.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/Tests/SortClauseParser/MapDistanceSortClauseParserTest.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/Tests/SortClauseParser/RandomSortClauseParserTest.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/Tests/SortClauseParserDispatcherTest.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/Tests/SortSpecLexerStub.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/Tests/SortSpecLexerTest.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/Tests/SortSpecParserTest.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/Token.php
  eZ/Publish/Core/QueryType/BuiltIn/SubtreeQueryType.php
  eZ/Publish/Core/QueryType/BuiltIn/Tests/AbstractQueryTypeTest.php
  eZ/Publish/Core/QueryType/BuiltIn/Tests/AncestorsQueryTypeTest.php
  eZ/Publish/Core/QueryType/BuiltIn/Tests/ChildrenQueryTypeTest.php
  eZ/Publish/Core/QueryType/BuiltIn/Tests/GeoLocationQueryTypeTest.php
  eZ/Publish/Core/QueryType/BuiltIn/Tests/RelatedToContentQueryTypeTest.php
  eZ/Publish/Core/QueryType/BuiltIn/Tests/SiblingsQueryTypeTest.php
  eZ/Publish/Core/QueryType/BuiltIn/Tests/SubtreeQueryTest.php
  phpunit.xml
Labels: Feature

#2991 EZP-31485: Updated image creatorId in cleandata.sql
  data/mysql/cleandata.sql
  data/postgresql/cleandata.sql
Labels: Bug

#2987 EZP-31481: Introduced strict types for Repository
  eZ/Publish/API/Repository/Repository.php
  eZ/Publish/Core/Event/Repository.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/SiteAccessAware/Repository.php
Labels: DX, Improvement

#2986 EZP-31480: Introduced strict types for PermissionResolver & PermissionCriterionResolver
  eZ/Publish/API/Repository/PermissionCriterionResolver.php
  eZ/Publish/API/Repository/PermissionResolver.php
  eZ/Publish/Core/Repository/Permission/CachedPermissionService.php
  eZ/Publish/Core/Repository/Permission/PermissionCriterionResolver.php
  eZ/Publish/Core/Repository/Permission/PermissionResolver.php
  eZ/Publish/Core/Repository/Tests/Permission/CachedPermissionServiceTest.php
Labels: DX, Improvement

#2944 EZP-31079: Added way to use login or email (or both) during authentication
  doc/bc/changes-8.0.md
  eZ/Bundle/EzPublishCoreBundle/Resources/config/security.yml
  eZ/Publish/API/Repository/Tests/UserServiceTest.php
  eZ/Publish/API/Repository/UserService.php
  eZ/Publish/Core/MVC/Symfony/Security/Tests/Authentication/RepositoryAuthenticationProviderTest.php
  eZ/Publish/Core/MVC/Symfony/Security/Tests/User/EmailProviderTest.php
  eZ/Publish/Core/MVC/Symfony/Security/Tests/User/UsernameProviderTest.php
  eZ/Publish/Core/MVC/Symfony/Security/User/BaseProvider.php
  eZ/Publish/Core/MVC/Symfony/Security/User/EmailProvider.php
  eZ/Publish/Core/MVC/Symfony/Security/User/UsernameProvider.php
  eZ/Publish/Core/Persistence/Cache/Tests/UserHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/UserHandler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/User/UserHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/User/Handler.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/UserServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/UserService.php
  eZ/Publish/Core/Repository/UserService.php
  eZ/Publish/SPI/Persistence/User/Handler.php
  eZ/Publish/SPI/Repository/Decorator/UserServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/UserServiceDecoratorTest.php
Labels: Feature

#2972 EZP-31448: Introduced strict types for LocationService
  eZ/Publish/API/Repository/LocationService.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ParentContentTypeTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Identifier/ParentContentTypeTest.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/GlobalHelperTest.php
  eZ/Publish/Core/Repository/LocationService.php
  eZ/Publish/Core/Repository/SiteAccessAware/LocationService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/LocationServiceTest.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
  eZ/Publish/SPI/Repository/Decorator/LocationServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/LocationServiceDecoratorTest.php
Labels: DX, Improvement

#2974 EZP-31450: Introduced strict types for URLAliasService
  eZ/Publish/API/Repository/URLAliasService.php
  eZ/Publish/Core/Event/URLAliasService.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/UrlAliasServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/URLAliasService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/UrlAliasTest.php
  eZ/Publish/Core/Repository/URLAliasService.php
  eZ/Publish/SPI/Repository/Decorator/URLAliasServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/URLAliasServiceDecoratorTest.php
Labels: DX, Improvement, QA approved

#2979 EZP-31469: Introduced strict types for UserService
  eZ/Publish/API/Repository/UserService.php
  eZ/Publish/Core/Event/UserService.php
  eZ/Publish/Core/Persistence/Legacy/User/Mapper.php
  eZ/Publish/Core/Repository/SiteAccessAware/Tests/UserServiceTest.php
  eZ/Publish/Core/Repository/SiteAccessAware/UserService.php
  eZ/Publish/Core/Repository/UserService.php
  eZ/Publish/SPI/Repository/Decorator/UserServiceDecorator.php
  eZ/Publish/SPI/Repository/Tests/Decorator/UserServiceDecoratorTest.php
Labels: DX, Improvement

#2997 EZP-31448: Added missing casting $locationId to int in the URLAliasService::createGlobalUrlAlias
  eZ/Publish/Core/Repository/URLAliasService.php
Labels: Bug

#2998 EZP-31482: Allowed null as $operator in UserMetadata criterion
  eZ/Publish/API/Repository/Tests/SearchServiceTest.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/UserMetadata.php
Labels: Bug

#2899 EZP-30956: fix false positive view parameters detection
  eZ/Bundle/EzPublishCoreBundle/EventListener/SiteAccessListener.php
Labels: Ready for QA

#2985 EZP-31497: Prepared clean data for eZ Platform 3.0 release
  data/mysql/cleandata.sql
  data/postgresql/cleandata.sql
Labels: Improvement, QA approved

#3002 EZP-31506: Deprecated `ezpublish.query_type` tag in favour of `ezplatform.query_type`
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/QueryTypePass.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/query_types.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/QueryTypePassTest.php
Labels: DX, Improvement

#3004 EZP-31134: Added exit codes to UpdateTimestampsToUTCCommand to reflect Sf5 standards
  eZ/Bundle/EzPublishCoreBundle/Command/UpdateTimestampsToUTCCommand.php
Labels: Bug, QA approved

#2993 EZP-31457: Fix supportsClass in user provider
  eZ/Publish/Core/MVC/Symfony/Security/User/Provider.php
Labels: Bug, QA approved

#3003 EZP-31507: Allowed to use Ancestors/Children/Siblings/Subtree Query Types with location search
  eZ/Publish/Core/QueryType/BuiltIn/AbstractLocationQueryType.php
  eZ/Publish/Core/QueryType/BuiltIn/AbstractQueryType.php
  eZ/Publish/Core/QueryType/BuiltIn/Tests/AncestorsQueryTypeTest.php
  eZ/Publish/Core/QueryType/BuiltIn/Tests/ChildrenQueryTypeTest.php
  eZ/Publish/Core/QueryType/BuiltIn/Tests/SiblingsQueryTypeTest.php
  eZ/Publish/Core/QueryType/BuiltIn/Tests/SubtreeQueryTest.php
Labels: Bug

#2889 EZP-31113: Indexed subtree for search on AssignSectionToSubtree event
  eZ/Publish/Core/Search/Common/EventSubscriber/LocationEventSubscriber.php
Labels: Bug, QA approved

#3000 EZP-31499: Implemented ez_path/ez_url Twig functions
  eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/views/content_fields.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/embed.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/embed_inline.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/line.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/text_linked.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/pagelayout.html.twig
  eZ/Publish/Core/MVC/Symfony/Controller/Content/DownloadRedirectionController.php
  eZ/Publish/Core/MVC/Symfony/Routing/ChainRouter.php
  eZ/Publish/Core/MVC/Symfony/Routing/Tests/UrlAliasRouterTest.php
  eZ/Publish/Core/MVC/Symfony/Routing/UrlAliasRouter.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/RoutingExtensionTest.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/_fixtures/routing_functions/ez_path.test
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/_fixtures/routing_functions/ez_route.test
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/_fixtures/routing_functions/ez_url.test
  eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/RoutingExtension.php
Labels: DX, Improvement

#3005 EZP-31490: Added multilingual content route
  eZ/Bundle/EzPublishCoreBundle/Resources/config/routing/internal.yml
  eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php
  eZ/Publish/Core/MVC/Symfony/View/Tests/Builder/ContentViewBuilderTest.php
Labels: QA approved

#3007 EZP-31499: Fixed unclosed "(" in embed_inline.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/embed_inline.html.twig
Labels: Bug

#3008 EZP-31512: Fixed extracting Search Fields from RichText
  eZ/Publish/Core/FieldType/RichText/SearchField.php
  eZ/Publish/Core/FieldType/Tests/RichText/SearchFieldTest.php
Labels: Bug

#2978 EZP-31463: Handled fetching of non existing type field type
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Handler.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerContentTest.php
Labels: Bug, QA approved

#3001 EZP-31471: Added keywords versioning
  data/update/mysql/dbupdate-7.5.latest-to-8.0.0.sql
  data/update/postgres/dbupdate-7.5.latest-to-8.0.0.sql
  eZ/Bundle/EzPublishCoreBundle/Resources/config/storage/legacy/schema.yaml
  eZ/Publish/API/Repository/Tests/FieldType/KeywordIntegrationTest.php
  eZ/Publish/Core/FieldType/Keyword/KeywordStorage.php
  eZ/Publish/Core/FieldType/Keyword/KeywordStorage/Gateway.php
  eZ/Publish/Core/FieldType/Keyword/KeywordStorage/Gateway/DoctrineStorage.php
Labels: Improvement, QA approved

#3011 [Tests] Enforced failure on warning
  phpunit-integration-legacy-solr.xml
  phpunit-integration-legacy.xml
  phpunit.xml
Labels: Bug, Improvement

#2957 EZP-31129: Added optional parameter to unlinkURL to better delete unused links
  eZ/Publish/Core/FieldType/Url/UrlStorage/Gateway.php
  eZ/Publish/Core/FieldType/Url/UrlStorage/Gateway/DoctrineStorage.php
  eZ/Publish/Core/FieldType/Url/UrlStorage/Gateway/LegacyStorage.php
Labels: Bug, QA approved

#2977 EZP-31461: LocationCreateStruct will inherit ContentType's sorting options
  eZ/Publish/API/Repository/Tests/LocationServiceTest.php
  eZ/Publish/API/Repository/Values/Content/LocationCreateStruct.php
  eZ/Publish/Core/Repository/LocationService.php
Labels: Improvement, QA approved
