Repository ezsystems/ezpublish-kernel, pull requests merged in 2020-04, with the labels that each got.

#3010 EZP-31519: Move app.php rejection snippet from front controller to ezpublish-kernel
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Bundle/EzPublishCoreBundle/EventListener/RejectExplicitFrontControllerRequestsListener.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/http_kernel.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/RejectExplicitFrontControllerRequestsListenerTest.php
Labels: Improvement, Ready for review

#2965 EZP-30760: Fixed broken link after historical parent location removed
  eZ/Publish/API/Repository/Tests/LocationServiceTest.php
  eZ/Publish/API/Repository/Tests/URLAliasServiceTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/UrlAliasHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/UrlAliasHandler.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/_fixtures/urlaliases_location_delete.php
  eZ/Publish/SPI/Persistence/Content/UrlAlias/Handler.php
Labels: Bug, QA approved

#2923 EZP-31112: Refactored locationSwapped function to keep custom aliases
  eZ/Publish/API/Repository/Tests/LocationServiceTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/ExceptionConversion.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Handler.php
Labels: Bug, QA approved

#3015 EZP-31136: Added unlink to remove old link from ezurl table
  eZ/Publish/Core/FieldType/Tests/Url/UrlStorageTest.php
  eZ/Publish/Core/FieldType/Url/UrlStorage.php
Labels: Bug, Ready for QA

#3018 EZP-31558: Updated loadByIdentifier to use escapeForCacheKey function before get value from cache
  eZ/Publish/Core/Persistence/Cache/ContentLanguageHandler.php
  eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php
  eZ/Publish/Core/Persistence/Cache/ObjectStateHandler.php
  eZ/Publish/Core/Persistence/Cache/SectionHandler.php
  eZ/Publish/Core/Persistence/Cache/UserHandler.php
Labels: Bug, QA approved

#2954 EZP-31411: Added ability to sort Trash items by trashed date
  eZ/Publish/API/Repository/Tests/BaseTrashServiceTest.php
  eZ/Publish/API/Repository/Tests/TrashServiceTest.php
  eZ/Publish/API/Repository/Values/Content/Query/SortClause/Trash/DateTrashed.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
Labels: Feature, QA approved

#3020 EZP-31560: [Tests] Fixed namespaces not following PSR
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/RichTextHtml5ConverterPassTest.php
  eZ/Publish/Core/IO/Tests/MetadataHandler/ImageSizeTest.php
  eZ/Publish/Core/MVC/Symfony/Cache/Tests/Http/LocalPurgeClientTest.php
  eZ/Publish/Core/MVC/Symfony/Cache/Tests/Http/LocationAwareStoreTest.php
  eZ/Publish/Core/MVC/Symfony/FieldType/Tests/Relation/ParameterProviderTest.php
  eZ/Publish/Core/MVC/Symfony/FieldType/Tests/RelationList/ParameterProviderTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ContentTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ContentTypeGroupTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ContentTypeTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/LocationTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ParentContentTypeTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ParentLocationTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/RemoteTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/SectionTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Identifier/ContentTypeTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Identifier/ParentContentTypeTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Identifier/SectionTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/MultipleValuedTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/UrlAliasTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/URLHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/Update/Handler/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerLocationSortTest.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerLocationTest.php
  eZ/Publish/Core/SignalSlot/Tests/SlotFactory/GeneralSlotFactoryTest.php
Labels: Bug

#3022 [Fast Forward MERGE] EZP-31560: [Tests] Fixed namespaces not following PSR
  eZ/Bundle/EzPublishCoreBundle/Tests/Matcher/ViewMatcherRegistryTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/SiteAccess/SiteAccessMatcherRegistryTest.php
  eZ/Publish/Core/IO/Tests/MetadataHandler/ImageSizeTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ContentTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ContentTypeGroupTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ContentTypeTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/LocationTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ParentContentTypeTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/ParentLocationTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/RemoteTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Id/SectionTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Identifier/ContentTypeTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Identifier/ParentContentTypeTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/Identifier/SectionTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/MultipleValuedTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/UrlAliasTest.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/Provider/ChainSiteAccessProviderTest.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/SiteAccessServiceTest.php
  eZ/Publish/Core/Pagination/Tests/AdapterFactory/SearchHitAdapterFactoryTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/BookmarkHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/NotificationHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/URLHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/Tests/UrlWildcardHandlerTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/Type/Update/Handler/DoctrineDatabaseTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/Tests/SortSpecLexerTest.php
  eZ/Publish/Core/QueryType/BuiltIn/SortSpec/Tests/SortSpecParserTest.php
Labels: Bug, Rebase required

#3024 EZP-31592: Added missing deprecation info to data/mysql/schema.sql
  data/mysql/schema.sql
Labels: Bug, Ready for QA

#3025 EZP-31586: Added missing columns to data/mysql/schema.sql
  data/mysql/schema.sql
Labels: Bug, QA approved

#3017 EZP-31542: Added PHP 7.4 support (eZ Platform 2.5)
  .travis.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/Assetic/AssetFactoryTest.php
  eZ/Publish/API/Repository/Tests/FieldType/SearchBaseIntegrationTest.php
  eZ/Publish/Core/FieldType/BinaryFile/SearchField.php
  eZ/Publish/Core/FieldType/DateAndTime/SearchField.php
  eZ/Publish/Core/FieldType/Image/SearchField.php
  eZ/Publish/Core/FieldType/MapLocation/SearchField.php
  eZ/Publish/Core/FieldType/Media/SearchField.php
  eZ/Publish/Core/FieldType/Relation/Type.php
  eZ/Publish/Core/FieldType/Tests/Url/UrlStorageTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/AuthorConverter.php
  eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/DateAndTimeConverter.php
  eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/DateConverter.php
  eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/TimeConverter.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/ContentHandlerTest.php
  eZ/Publish/Core/Persistence/TransformationProcessor/PcreCompiler.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/UserPreferenceTest.php
  eZ/Publish/Core/Repository/UserPreferenceService.php
Labels: Improvement, Ready for QA
