Repository ezsystems/ezpublish-kernel, pull requests merged in 2020-10, with the labels that each got.

#3066 EZP-31837: Creating an additional Content Location does not repect Content visibility
  eZ/Publish/API/Repository/Tests/LocationServiceTest.php
  eZ/Publish/API/Repository/Values/Content/Location.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/Helper/DomainMapper.php
  eZ/Publish/Core/Repository/LocationService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
Labels: QA approved

#3069 EZP-31800: Cleared persistence cache on Content Type copy
  eZ/Publish/API/Repository/Tests/ContentTypeServiceTest.php
  eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php
Labels: Ready for review

#3068 EZP-31891: Use specified templates for embedded image and asset FT
  eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/asset_image.html.twig
  eZ/Bundle/EzPublishCoreBundle/Resources/views/default/content/embed_image.html.twig
Labels: QA approved

#3070 EZP-31930: Cleaned up output of commands displaying progress bar
  eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php
  eZ/Bundle/PlatformInstallerBundle/src/Installer/CoreInstaller.php
Labels: Improvement, QA approved, Ready for review

#3071 EZP-31039: Skip requirement of sort params when updating Location via REST
  eZ/Publish/Core/REST/Server/Input/Parser/LocationUpdate.php
  eZ/Publish/Core/REST/Server/Tests/Input/Parser/LocationUpdateTest.php
Labels: Improvement, QA approved

#3023 EZP-31287: Added FullText search Fields for Email and ISBN
  eZ/Publish/API/Repository/Tests/FieldType/EmailAddressIntegrationTest.php
  eZ/Publish/API/Repository/Tests/FieldType/ISBNIntegrationTest.php
  eZ/Publish/Core/FieldType/EmailAddress/SearchField.php
  eZ/Publish/Core/FieldType/ISBN/SearchField.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/FullText.php
  eZ/Publish/Core/Search/Legacy/Content/FullTextValue.php
  eZ/Publish/Core/Search/Legacy/Content/Mapper/FullTextMapper.php
  eZ/Publish/Core/Search/Legacy/Content/WordIndexer/Gateway/DoctrineDatabase.php
  eZ/Publish/SPI/Search/FieldType/FullTextField.php
Labels: Bug, QA approved

#3073 CS hotfix for ContentServiceTest.php
  eZ/Publish/API/Repository/Tests/Parallel/ContentServiceTest.php
Labels: Bug, Ready for MERGE
