Repository ezsystems/ezpublish-kernel, pull requests merged in 2020-02, with the labels that each got.

#2935 [Tests] Dropped Solr 6 tests
  eZ/Publish/API/Repository/Tests/SearchServiceFulltextTest.php
Labels: Improvement

#2937 EZP-31348: Dropped deprecated createFromQueryBuilder method from the Criterion classes
  doc/bc/changes-8.0.md
  eZ/Publish/API/Repository/Values/Content/Query/Criterion.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/Ancestor.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/ContentId.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/ContentTypeGroupId.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/ContentTypeId.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/ContentTypeIdentifier.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/FieldRelation.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/FullText.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/LanguageCode.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/LocationId.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/LocationRemoteId.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/MatchAll.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/MatchNone.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/MoreLikeThis.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/ObjectStateId.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/ParentLocationId.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/RemoteId.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/SectionId.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/Subtree.php
  eZ/Publish/API/Repository/Values/Content/Query/Criterion/Visibility.php
Labels: Improvement

#2844 EZP-30981: Enhanced ContentInfo/VersionInfo/Location Value Object
  eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php
  eZ/Bundle/EzPublishCoreBundle/Cache/Warmer/ProxyCacheWarmer.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/cache.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/papi.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/Cache/Warmer/ProxyCacheWarmerTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
  eZ/Publish/API/Repository/Tests/ContentServiceTest.php
  eZ/Publish/API/Repository/Tests/LocationServiceTest.php
  eZ/Publish/API/Repository/Values/Content/ContentInfo.php
  eZ/Publish/API/Repository/Values/Content/Location.php
  eZ/Publish/API/Repository/Values/Content/VersionInfo.php
  eZ/Publish/Core/Base/Container/ApiLoader/RepositoryFactory.php
  eZ/Publish/Core/Repository/Helper/ContentTypeDomainMapper.php
  eZ/Publish/Core/Repository/Helper/DomainMapper.php
  eZ/Publish/Core/Repository/ProxyFactory/ProxyDomainMapper.php
  eZ/Publish/Core/Repository/ProxyFactory/ProxyDomainMapperFactory.php
  eZ/Publish/Core/Repository/ProxyFactory/ProxyDomainMapperFactoryInterface.php
  eZ/Publish/Core/Repository/ProxyFactory/ProxyDomainMapperInterface.php
  eZ/Publish/Core/Repository/ProxyFactory/ProxyGenerator.php
  eZ/Publish/Core/Repository/ProxyFactory/ProxyGeneratorInterface.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/DomainMapperTest.php
  eZ/Publish/Core/Repository/TrashService.php
  eZ/Publish/Core/Repository/Values/Content/ContentContentInfoProxy.php
  eZ/Publish/Core/Repository/Values/Content/ContentProxy.php
  eZ/Publish/Core/Repository/Values/Content/Location.php
  eZ/Publish/Core/Repository/Values/Content/TrashItem.php
  eZ/Publish/Core/Repository/Values/Content/VersionInfo.php
  eZ/Publish/Core/Repository/Values/ContentType/ContentTypeGroupProxy.php
  eZ/Publish/Core/Repository/Values/GeneratorProxyTrait.php
  eZ/Publish/Core/settings/repository/inner.yml
Labels: DX, Feature, QA approved

#2930 EZP-31047: Made Site Access group configuration available in DIC
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/SiteAccessAware/ConfigurationProcessor.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/SiteAccessAware/Contextualizer.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/LanguagesTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/SiteAccessAware/ConfigurationProcessorTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/SiteAccessAware/ContextualizerTest.php
Labels: Feature, QA approved

#2939 EZP-31351: Added a new argument to check the permissions for embedded…
  eZ/Publish/Core/MVC/Symfony/View/Builder/ContentViewBuilder.php
Labels: Bug, QA approved

#2941 Fix - Removed clearing from tags in low-level code
  eZ/Publish/Core/Persistence/Legacy/Tests/UserPreference/MapperTest.php
  eZ/Publish/Core/Persistence/Legacy/UserPreference/Mapper.php
Labels: Bug, QA approved

#2936 Added totalCount attribute to REST ContentList response
  eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/ContentList.php
  eZ/Publish/Core/REST/Server/Values/ContentList.php
Labels: QA approved

#2945 EZP-31298: Made non verbose exception messages in REST responses
  .travis.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/translations/repository_exceptions.en.xlf
  eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/Exception.php
  eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/ExceptionTest.php
Labels: Bug, QA approved

#2947 Backported #2945 "EZP-31298: Made non verbose exception messages in REST responses"
  .travis.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/translations/repository_exceptions.en.xlf
  eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/Exception.php
  eZ/Publish/Core/REST/Server/Tests/Output/ValueObjectVisitor/ExceptionTest.php
Labels: Bug, QA approved

#2924 EZP-31329: Injected project dir into ezplatform:reindex cmd to find console path
  eZ/Bundle/EzPublishCoreBundle/Command/ReindexCommand.php
Labels: Improvement, QA approved

#2666 EZP-30664: Skipped indexing erroneous Content and logged all exceptions
  eZ/Publish/Core/Search/Common/IncrementalIndexer.php
  eZ/Publish/Core/Search/Legacy/Content/Indexer.php
Labels: Bug, QA approved

#2933 [Behat] Make Behat SiteAccess aware
  eZ/Bundle/PlatformBehatBundle/Initializer/BehatSiteAccessInitializer.php
  eZ/Bundle/PlatformBehatBundle/ServiceContainer/EzBehatExtension.php
Labels: Ready for MERGE

#2914 EZP-31278: Injected LimitationService into the Repository
  eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php
  eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php
  eZ/Publish/Core/Base/Container/ApiLoader/RepositoryFactory.php
  eZ/Publish/Core/Base/Container/Compiler/RegisterLimitationTypePass.php
  eZ/Publish/Core/Base/Tests/Container/Compiler/RegisterLimitationTypePassTest.php
  eZ/Publish/Core/Helper/Tests/ContentInfoLocationLoader/SudoMainLocationLoaderTest.php
  eZ/Publish/Core/MVC/Symfony/Matcher/Tests/ContentBased/BaseTest.php
  eZ/Publish/Core/MVC/Symfony/Routing/Tests/UrlAliasGeneratorTest.php
  eZ/Publish/Core/MVC/Symfony/Security/Tests/Authentication/RememberMeRepositoryAuthenticationProviderTest.php
  eZ/Publish/Core/Repository/Helper/RoleDomainMapper.php
  eZ/Publish/Core/Repository/Permission/LimitationService.php
  eZ/Publish/Core/Repository/Permission/PermissionCriterionResolver.php
  eZ/Publish/Core/Repository/Permission/PermissionResolver.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/RoleService.php
  eZ/Publish/Core/Repository/Tests/Permission/PermissionCriterionResolverTest.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/PermissionTest.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/PermissionsCriterionHandlerTest.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/RoleTest.php
  eZ/Publish/Core/settings/containerBuilder.php
  eZ/Publish/Core/settings/repository/inner.yml
Labels: DX, Improvement, QA approved

#2913 EZP-31279: Injected content domain mappers into the Repository
  eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php
  eZ/Publish/Core/Base/Container/ApiLoader/RepositoryFactory.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/ContentTypeService.php
  eZ/Publish/Core/Repository/Helper/NameSchemaService.php
  eZ/Publish/Core/Repository/LocationService.php
  eZ/Publish/Core/Repository/Mapper/ContentDomainMapper.php
  eZ/Publish/Core/Repository/Mapper/ContentTypeDomainMapper.php
  eZ/Publish/Core/Repository/Mapper/ProxyAwareDomainMapper.php
  eZ/Publish/Core/Repository/ProxyFactory/ProxyDomainMapper.php
  eZ/Publish/Core/Repository/ProxyFactory/ProxyDomainMapperFactory.php
  eZ/Publish/Core/Repository/Repository.php
  eZ/Publish/Core/Repository/SearchService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/Base.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/DomainMapperTest.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/SearchTest.php
  eZ/Publish/Core/settings/repository/inner.yml
Labels: DX, Improvement, QA approved

#2950 EZP-31079: Provided a way to inject contextual Twig variables
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/TwigVariablesParser.php
  eZ/Bundle/EzPublishCoreBundle/EzPublishCoreBundle.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/default_settings.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
  eZ/Bundle/EzPublishCoreBundle/Templating/Twig/ContextAwareTwigVariablesExtension.php
  eZ/Publish/Core/MVC/Symfony/EventListener/ContentViewTwigVariablesSubscriber.php
  eZ/Publish/Core/MVC/Symfony/EventListener/Tests/ContentViewTwigVariablesSubscriberTest.php
  eZ/Publish/Core/MVC/Symfony/ExpressionLanguage/ExpressionLanguage.php
  eZ/Publish/Core/MVC/Symfony/ExpressionLanguage/TwigVariableProviderExtension.php
  eZ/Publish/Core/MVC/Symfony/View/GenericVariableProviderRegistry.php
  eZ/Publish/Core/MVC/Symfony/View/Tests/VariableProviderRegistryTest.php
  eZ/Publish/Core/MVC/Symfony/View/VariableProviderRegistry.php
  eZ/Publish/SPI/MVC/View/VariableProvider.php
Labels: QA approved

#2940 EZP-31299: Added language mask to LSE search index
  data/mysql/schema.sql
  data/update/mysql/dbupdate-7.5.6-to-7.5.7.sql
  data/update/postgres/dbupdate-7.5.6-to-7.5.7.sql
  eZ/Bundle/EzPublishCoreBundle/Resources/config/storage/legacy/schema.yaml
  eZ/Publish/API/Repository/Tests/SearchServiceTest.php
  eZ/Publish/API/Repository/Tests/SearchServiceTranslationLanguageFallbackTest.php
  eZ/Publish/Core/Pagination/Pagerfanta/ContentSearchHitAdapter.php
  eZ/Publish/Core/Pagination/Tests/ContentSearchAdapterTest.php
  eZ/Publish/Core/Pagination/Tests/ContentSearchHitAdapterTest.php
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.mysql.sql
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.pgsql.sql
  eZ/Publish/Core/Persistence/Legacy/Tests/_fixtures/schema.sqlite.sql
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/FullText.php
  eZ/Publish/Core/Search/Legacy/Content/FullTextValue.php
  eZ/Publish/Core/Search/Legacy/Content/Mapper/FullTextMapper.php
  eZ/Publish/Core/Search/Legacy/Content/WordIndexer/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Search/Legacy/Content/WordIndexer/Repository/SearchIndex.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerContentSortTest.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerContentTest.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerLocationSortTest.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerLocationTest.php
  eZ/Publish/Core/settings/search_engines/legacy/criterion_handlers_common.yml
  eZ/Publish/Core/settings/search_engines/legacy/indexer.yml
Labels: QA approved
