Repository ezsystems/ezpublish-kernel, pull requests merged in 2020-08, with the labels that each got.

#3052 EZP-31775: Prevent user from downloading trashed File
  eZ/Publish/Core/MVC/Symfony/Controller/Content/DownloadController.php
Labels: Bug, QA approved

#3055 EZP-31776: Provided 'null' as Location in RestExecutedView if unavailable
  eZ/Publish/Core/REST/Server/Output/ValueObjectVisitor/RestExecutedView.php
Labels: Improvement, QA approved

#3056 EZP-30857: Fixed assessment of image removal feasibility
  eZ/Publish/API/Repository/Tests/FieldType/ImageIntegrationTest.php
  eZ/Publish/Core/FieldType/Image/ImageStorage.php
  eZ/Publish/Core/FieldType/Image/ImageStorage/Gateway/DoctrineStorage.php
Labels: Bug, QA approved

#3054 EZP-31511: Fixed validation of custom URL alias entry
  doc/bc/changes-7.5.md
  eZ/Bundle/EzPublishCoreBundle/Resources/translations/repository_exceptions.en.xlf
  eZ/Publish/API/Repository/Tests/BaseTest.php
  eZ/Publish/API/Repository/Tests/URLAliasService/CustomUrlAliasForMultilingualContentTest.php
  eZ/Publish/API/Repository/URLAliasService.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Tests/Content/UrlAlias/UrlAliasHandlerTest.php
  eZ/Publish/Core/REST/Client/URLAliasService.php
  eZ/Publish/Core/Repository/URLAliasService.php
  eZ/Publish/Core/SignalSlot/URLAliasService.php
  phpunit-integration-legacy.xml
Labels: Bug, QA approved, Ready for QA

#3062 EZP-31768: Fixed cache invalidation during url alias reassignment
  eZ/Publish/Core/Persistence/Cache/Tests/UrlAliasHandlerTest.php
  eZ/Publish/Core/Persistence/Cache/UrlAliasHandler.php
Labels: Bug, QA approved
