Repository ezsystems/ezpublish-kernel, pull requests merged in 2020-01, with the labels that each got.

#2909 [Travis] Fixed REST tests failing for PHP < 7.3
  .travis.yml
  eZ/Bundle/EzPublishRestBundle/Tests/Functional/ViewTest.php
Labels: Ready for MERGE

#2915 EZP-31275: Added tests for SearchService findLocations method covering IsEmpty Criterion
  eZ/Publish/API/Repository/Tests/SearchServiceLocationTest.php
  eZ/Publish/API/Repository/Tests/SearchServiceTest.php
Labels: Ready for MERGE, Ready for QA

#2911 EZP-31269: Dropped Symfony container *.class parameters
  doc/bc/8.0/dropped-container-parameters.md
  doc/bc/changes-8.0.md
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/FragmentPass.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/cache.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/helpers.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/locale.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/papi.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/routing.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/security.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/session.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/storage_engines.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/templating.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/translations/repository_exceptions.en.xlf
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/FragmentPassTest.php
  eZ/Bundle/EzPublishDebugBundle/Resources/config/services.yml
  eZ/Bundle/EzPublishIOBundle/Resources/config/io.yml
  eZ/Bundle/EzPublishLegacySearchEngineBundle/Resources/config/services.yml
  eZ/Publish/Core/Base/Exceptions/NotFound/FieldTypeNotFoundException.php
  eZ/Publish/Core/Base/Exceptions/NotFound/LimitationNotFoundException.php
  eZ/Publish/Core/settings/fieldtype_external_storages.yml
  eZ/Publish/Core/settings/fieldtype_services.yml
  eZ/Publish/Core/settings/fieldtypes.yml
  eZ/Publish/Core/settings/indexable_fieldtypes.yml
  eZ/Publish/Core/settings/io.yml
  eZ/Publish/Core/settings/repository/inner.yml
  eZ/Publish/Core/settings/roles.yml
  eZ/Publish/Core/settings/search_engines/common.yml
  eZ/Publish/Core/settings/search_engines/field_value_mappers.yml
  eZ/Publish/Core/settings/search_engines/legacy.yml
  eZ/Publish/Core/settings/search_engines/legacy/criterion_handlers_common.yml
  eZ/Publish/Core/settings/search_engines/legacy/criterion_handlers_content.yml
  eZ/Publish/Core/settings/search_engines/legacy/criterion_handlers_location.yml
  eZ/Publish/Core/settings/search_engines/legacy/indexer.yml
  eZ/Publish/Core/settings/search_engines/legacy/sort_clause_handlers_common.yml
  eZ/Publish/Core/settings/search_engines/legacy/sort_clause_handlers_content.yml
  eZ/Publish/Core/settings/search_engines/legacy/sort_clause_handlers_location.yml
  eZ/Publish/Core/settings/storage_engines/cache.yml
  eZ/Publish/Core/settings/storage_engines/common.yml
  eZ/Publish/Core/settings/storage_engines/legacy.yml
  eZ/Publish/Core/settings/storage_engines/legacy/content.yml
  eZ/Publish/Core/settings/storage_engines/legacy/content_type.yml
  eZ/Publish/Core/settings/storage_engines/legacy/external_storage_gateways.yml
  eZ/Publish/Core/settings/storage_engines/legacy/field_value_converters.yml
  eZ/Publish/Core/settings/storage_engines/legacy/language.yml
  eZ/Publish/Core/settings/storage_engines/legacy/location.yml
  eZ/Publish/Core/settings/storage_engines/legacy/object_state.yml
  eZ/Publish/Core/settings/storage_engines/legacy/section.yml
  eZ/Publish/Core/settings/storage_engines/legacy/trash.yml
  eZ/Publish/Core/settings/storage_engines/legacy/url.yml
  eZ/Publish/Core/settings/storage_engines/legacy/url_alias.yml
  eZ/Publish/Core/settings/storage_engines/legacy/url_criterion_handlers.yml
  eZ/Publish/Core/settings/storage_engines/legacy/url_wildcard.yml
  eZ/Publish/Core/settings/storage_engines/legacy/user.yml
  eZ/Publish/Core/settings/storage_engines/shortcuts.yml
  eZ/Publish/Core/settings/utils.yml
Labels: Improvement, QA approved

#2908 EZP-31203: Fixed wrong connection being used for database creation when SiteAccess option is used
  eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryConfigurationProvider.php
  eZ/Bundle/PlatformInstallerBundle/src/Command/InstallPlatformCommand.php
  eZ/Bundle/PlatformInstallerBundle/src/Resources/config/services.yml
Labels: Bug, QA approved

#2907 EZP-31258: Use "inset" for "scaledown" aliases to avoid undesired image cropping
  eZ/Bundle/EzPublishCoreBundle/Imagine/Filter/Loader/ScaleDownOnlyFilterLoader.php
  eZ/Bundle/EzPublishCoreBundle/Imagine/Filter/Loader/ScaleHeightDownOnlyFilterLoader.php
  eZ/Bundle/EzPublishCoreBundle/Imagine/Filter/Loader/ScaleWidthDownOnlyFilterLoader.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Filter/Loader/ScaleDownOnlyFilterLoaderTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Filter/Loader/ScaleHeightDownOnlyFilterLoaderTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/Filter/Loader/ScaleWidthDownOnlyFilterLoaderTest.php
Labels: Bug, QA approved

#2910 EZP-31267: Added IOConfigResolver to fetch complex IO settings
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/Parser/IO.php
  eZ/Bundle/EzPublishCoreBundle/Imagine/VariationPurger/LegacyStorageImageFileList.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/helpers.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
  eZ/Bundle/EzPublishCoreBundle/SiteAccess/Config/ComplexConfigProcessor.php
  eZ/Bundle/EzPublishCoreBundle/SiteAccess/Config/IOConfigResolver.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/IOTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/VariationPurger/LegacyStorageImageFileListTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/SiteAccess/Config/IOConfigResolverTest.php
  eZ/Bundle/EzPublishIOBundle/DependencyInjection/Factory/LocalAdapterFactory.php
  eZ/Bundle/EzPublishIOBundle/EventListener/StreamFileListener.php
  eZ/Bundle/EzPublishIOBundle/Resources/config/io.yml
  eZ/Bundle/EzPublishIOBundle/Tests/EventListener/StreamFileListenerTest.php
  eZ/Publish/Core/IO/IOConfigProvider.php
  eZ/Publish/Core/IO/Tests/UrlDecorator/AbsolutePrefixTest.php
  eZ/Publish/Core/IO/Tests/UrlDecorator/PrefixTest.php
  eZ/Publish/Core/IO/UrlDecorator/AbsolutePrefix.php
  eZ/Publish/Core/IO/UrlDecorator/Prefix.php
  eZ/Publish/Core/Repository/SiteAccessAware/Config/IOConfigResolver.php
  eZ/Publish/Core/settings/io.yml
  eZ/Publish/Core/settings/repository/siteaccessaware.yml
Labels: Feature, QA approved

#2917 EZP-31292: Fixed generating image variation using ez_image_alias
  eZ/Bundle/EzPublishCoreBundle/Resources/config/fieldtype_services.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
Labels: Bug, QA approved

#2921 EZP-31320: Fixed issue when `default` Site Access is unmatched
  eZ/Publish/Core/MVC/Symfony/SiteAccess.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/SiteAccessService.php
  eZ/Publish/Core/MVC/Symfony/SiteAccess/Tests/SiteAccessServiceTest.php
Labels: Bug, QA approved

#2843 EZP-31123: Fixed strict types-related casting issues
  eZ/Publish/Core/FieldType/Keyword/KeywordStorage/Gateway/DoctrineStorage.php
  eZ/Publish/Core/FieldType/Url/UrlStorage/Gateway/DoctrineStorage.php
  eZ/Publish/Core/Persistence/Legacy/Content/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Location/Handler.php
  eZ/Publish/Core/Persistence/Legacy/Content/Section/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlAlias/Gateway/DoctrineDatabase.php
  eZ/Publish/Core/Persistence/Legacy/Content/UrlWildcard/Gateway/DoctrineDatabase.php
Labels: Bug, QA approved

#2919 [Doc] Updated README
  Readme.md
Labels: Ready for review

#2901 EZP-31046: Improved ChainConfigResolver by extracting code to separate config resolvers
  doc/bc/changes-8.0.md
  eZ/Bundle/EzPublishCoreBundle/Cache/Warmer/ConfigResolverCleanup.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Compiler/ChainConfigResolverPass.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ChainConfigResolver.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver/ContainerConfigResolver.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver/DefaultScopeConfigResolver.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver/GlobalScopeConfigResolver.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver/SiteAccessConfigResolver.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver/SiteAccessGroupConfigResolver.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration/ConfigResolver/StaticSiteAccessConfigResolver.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/EzPublishCoreExtension.php
  eZ/Bundle/EzPublishCoreBundle/EventListener/ConfigScopeListener.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/helpers.yml
  eZ/Bundle/EzPublishCoreBundle/Resources/config/services.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/Cache/Warmer/ConfigResolverCleanupTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Compiler/ChainConfigResolverPassTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/AbstractParserTestCase.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/TemplatesTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/EventListener/ConfigScopeListenerTest.php
  eZ/Publish/Core/MVC/ConfigResolverInterface.php
  eZ/Publish/Core/MVC/Symfony/Configuration/VersatileScopeInterface.php
Labels: Feature, QA approved

#2928 Fixed index name assertion for Solr Cloud 6.X in SearchServiceTranslationLanguageFallbackTest
  eZ/Publish/API/Repository/Tests/SearchServiceTranslationLanguageFallbackTest.php
Labels: Bug

#2927 EZP-31048: Allowed empty Site Access groups
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/AbstractParserTestCase.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/CommonTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/IOTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Configuration/Parser/LanguagesTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/Fixtures/ezpublish_minimal.yml
Labels: Feature, QA approved, Ready for review

#2926 EZP-31297: Narrowed user preferences values to the available list (added additional tags protection for read)
  eZ/Publish/Core/Persistence/Legacy/Tests/UserPreference/MapperTest.php
  eZ/Publish/Core/Persistence/Legacy/UserPreference/Mapper.php
Labels: Bug, QA approved, Ready for QA

#2872 EZP-31127: Skipped non-existing Content Types in ContentTypeIdentifier criterion
  eZ/Publish/API/Repository/Tests/SearchServiceTest.php
  eZ/Publish/Core/Search/Legacy/Content/Common/Gateway/CriterionHandler/ContentTypeIdentifier.php
  eZ/Publish/Core/settings/search_engines/legacy/criterion_handlers_common.yml
Labels: Improvement, QA approved

#2931 Changed assertEquals to assertEqualsCanonicalizing in tests
  eZ/Bundle/EzPublishCoreBundle/Tests/URLChecker/URLCheckerTest.php
  eZ/Publish/API/Repository/Tests/RoleServiceTest.php
  eZ/Publish/Core/MVC/Symfony/View/Tests/ViewManagerTest.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerContentSortTest.php
  eZ/Publish/Core/Search/Legacy/Tests/Content/HandlerLocationSortTest.php
Labels: Improvement, Ready for review

#2932 EZP-29574: Increased token time life to prevent token expired before end test
  eZ/Publish/API/Repository/Tests/UserServiceTest.php
Labels: Bug, Ready for review

#2922 EZP-31226: Added new integration test for embedded content
  eZ/Publish/API/Repository/Tests/SearchService/SearchServiceFullTextEmbedTest.php
  phpunit-integration-legacy-solr.xml
Labels: Bug, QA approved
