Repository ezsystems/ezpublish-kernel, pull requests merged in 2021-07, with the labels that each got.

#3110 IBX-296: Provided new way to handle archived versions
  eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryFactory.php
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
  eZ/Publish/Core/FieldType/Image/ImageStorage.php
  eZ/Publish/Core/FieldType/Image/ImageStorage/Gateway.php
  eZ/Publish/Core/FieldType/Image/ImageStorage/Gateway/DoctrineStorage.php
  eZ/Publish/Core/FieldType/Image/ImageStorage/Gateway/LegacyStorage.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
Labels: Doc needed, QA approved

#3090 EZP-32349: Fixed purging stale data from ezcontentclass_attribute_ml
  eZ/Publish/Core/Persistence/Legacy/Content/Type/Gateway/DoctrineDatabase.php
Labels: Bug, QA approved

#3112 IBX-784: Provided PHP8 compatibility for Selection FieldType
  eZ/Publish/Core/FieldType/Selection/Type.php
  eZ/Publish/Core/FieldType/Tests/SelectionTest.php
Labels: QA approved, Ready for MERGE

#3111 IBX-538: Added Ibexa namespaces for future compatibility
  .php_cs
  composer.json
  src/bundle/Core/.gitkeep
  src/bundle/Debug/.gitkeep
  src/bundle/IO/.gitkeep
  src/bundle/Installer/.gitkeep
  src/bundle/LegacySearchEngine/.gitkeep
  src/contracts/.gitkeep
  src/lib/.gitkeep
  tests/bundle/Core/.gitkeep
  tests/bundle/Debug/.gitkeep
  tests/bundle/IO/.gitkeep
  tests/bundle/Installer/.gitkeep
  tests/bundle/LegacySearchEngine/.gitkeep
  tests/integration/Core/.gitkeep
  tests/integration/Debug/.gitkeep
  tests/integration/IO/.gitkeep
  tests/integration/Installer/.gitkeep
  tests/integration/LegacySearchEngine/.gitkeep
  tests/lib/.gitkeep
Labels: Ready for review

#3113 EZP-31560: Fixed ContentDeleteEvaluatorTest class file path
  eZ/Publish/Core/Limitation/Tests/LanguageLimitation/ContentDeleteEvaluatorTest.php
Labels: Bug, Ready for review
