Repository ezsystems/ezpublish-kernel, pull requests merged in 2021-02, with the labels that each got.

#3084 EZP-32321: Added deleteTranslations target to fix 'content/remove' permission check
  eZ/Publish/API/Repository/Tests/ContentServiceAuthorizationTest.php
  eZ/Publish/API/Repository/Tests/Limitation/PermissionResolver/LanguageLimitationIntegrationTest.php
  eZ/Publish/API/Repository/Tests/LocationServiceAuthorizationTest.php
  eZ/Publish/API/Repository/Tests/TrashServiceAuthorizationTest.php
  eZ/Publish/Core/Limitation/LanguageLimitation/ContentDeleteEvaluator.php
  eZ/Publish/Core/Limitation/Tests/LangugeLimitation/ContentDeleteEvaluatorTest.php
  eZ/Publish/Core/Repository/ContentService.php
  eZ/Publish/Core/Repository/LocationService.php
  eZ/Publish/Core/Repository/Tests/Service/Mock/ContentTest.php
  eZ/Publish/Core/Repository/TrashService.php
  eZ/Publish/SPI/Limitation/Target/Version.php
Labels: Bug, QA approved, Ready for review

#3087 Defined \eZ\Publish\Core\IO\IOService::$settings member explicitly
  eZ/Publish/Core/IO/IOService.php
Labels: Bug

#3085 EZEE-3465: Refactored RepositoryConfigurationProvider
  eZ/Bundle/EzPublishCoreBundle/ApiLoader/RepositoryConfigurationProvider.php
  eZ/Bundle/EzPublishCoreBundle/Tests/ApiLoader/RepositoryConfigurationProviderTest.php
Labels: Improvement, QA approved

#3083 EZP-32308: Fixed evaluating permissions on non prepared targets
  eZ/Publish/API/Repository/Tests/Limitation/PermissionResolver/LocationLimitationIntegrationTest.php
  eZ/Publish/API/Repository/Tests/PermissionResolverTest.php
  eZ/Publish/Core/Limitation/LocationLimitationType.php
  eZ/Publish/Core/Repository/Permission/PermissionResolver.php
Labels: QA approved

#3086 EZP-32320: Fixed image placeholders generation on DFS
  eZ/Bundle/EzPublishCoreBundle/DependencyInjection/Configuration.php
  eZ/Bundle/EzPublishCoreBundle/Imagine/PlaceholderAliasGenerator.php
  eZ/Bundle/EzPublishCoreBundle/Imagine/PlaceholderAliasGeneratorConfigurator.php
  eZ/Bundle/EzPublishCoreBundle/Tests/DependencyInjection/EzPublishCoreExtensionTest.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/PlaceholderAliasGeneratorTest.php
Labels: Bug, QA approved
