Repository ezsystems/ezpublish-kernel, pull requests merged in 2021-06, with the labels that each got.

#3105 IBX-111: Injected RequestStack into ExposedRoutesExtractor
  composer.json
  eZ/Bundle/EzPublishCoreBundle/Resources/config/routing/js_routing.yml
  eZ/Bundle/EzPublishCoreBundle/Routing/JsRouting/ExposedRoutesExtractor.php
  eZ/Bundle/EzPublishCoreBundle/Tests/Routing/JsRouting/ExposedRoutesExtractorTest.php
Labels: Bug, QA approved

#3102 IBX-368: Added image path normalization before storing it into the DB
  eZ/Bundle/EzPublishCoreBundle/Command/NormalizeImagesPathsCommand.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/commands.yml
  eZ/Publish/Core/FieldType/Image/ImageStorage.php
  eZ/Publish/Core/FieldType/Image/ImageStorage/Gateway.php
  eZ/Publish/Core/FieldType/Image/ImageStorage/Gateway/DoctrineStorage.php
  eZ/Publish/Core/FieldType/Image/ImageStorage/Gateway/LegacyStorage.php
  eZ/Publish/Core/IO/FilePathNormalizer/Flysystem.php
  eZ/Publish/Core/IO/FilePathNormalizerInterface.php
  eZ/Publish/Core/settings/fieldtype_external_storages.yml
  eZ/Publish/Core/settings/io.yml
  eZ/Publish/SPI/Tests/FieldType/ImageIntegrationTest.php
Labels: Doc needed, QA approved

#3107 IBX-571: Added missing key in ContentTypeHandler
  eZ/Publish/Core/Persistence/Cache/ContentTypeHandler.php
Labels: Bug, QA approved

#3106 IBX-569: Changed ObjectStateHandler to extend AbstractInMemoryPersistenceHandler
  eZ/Publish/Core/Persistence/Cache/ObjectStateHandler.php
  eZ/Publish/Core/Persistence/Cache/Tests/AbstractBaseHandlerTest.php
  eZ/Publish/Core/settings/storage_engines/cache.yml
Labels: QA approved

#3109 IBX-610: Implemented InMemory cache for remaining LocationHandler methods
  eZ/Publish/Core/Persistence/Cache/LocationHandler.php
Labels: Improvement, QA approved

#3108 IBX-154: Allowed to define if the alternative text for image field is required (2.5)
  eZ/Publish/API/Repository/Tests/FieldType/ImageIntegrationTest.php
  eZ/Publish/Core/FieldType/Image/Type.php
  eZ/Publish/Core/FieldType/Image/Value.php
  eZ/Publish/Core/FieldType/Tests/ImageTest.php
  eZ/Publish/Core/Persistence/Legacy/Content/FieldValue/Converter/ImageConverter.php
  eZ/Publish/Core/Persistence/Tests/FieldValue/Converter/ImageConverterTest.php
  eZ/Publish/SPI/Tests/FieldType/ImageIntegrationTest.php
Labels: QA approved
