Repository ezsystems/ezpublish-kernel, pull requests merged in 2022-01, with the labels that each got.

#3130 IBX-1182: Added cache invalidation to liip:imagine:cache:remove command
  eZ/Bundle/EzPublishCoreBundle/Imagine/Cache/AliasGeneratorDecorator.php
  eZ/Bundle/EzPublishCoreBundle/Imagine/VariationPurger/IOVariationPurger.php
  eZ/Bundle/EzPublishCoreBundle/Resources/config/image.yml
  eZ/Bundle/EzPublishCoreBundle/Tests/Imagine/VariationPurger/IOVariationPurgerTest.php
Labels: QA approved, Ready for MERGE, Bug

#3132 [CI] Pinned lzf to version 1.6.8
  .travis.yml
Labels: Ready for review

#3133 Fixed ImageIntegrationTest to account for hashes
  eZ/Publish/API/Repository/Tests/FieldType/ImageIntegrationTest.php
  eZ/Publish/API/Repository/Tests/FieldType/_fixtures/1234eeee1234-image.jpg
  eZ/Publish/API/Repository/Tests/FieldType/_fixtures/2222eeee1111-image.png
Labels: Ready for MERGE, Bug

#3135 EZP-29574: the time life of the token has been adjusted to the same as in the platform
  eZ/Publish/API/Repository/Tests/UserServiceTest.php
Labels: Ready for review, Bug

#3134 IBX-1977: Changed calculate max file size, and displayed message about exceed file size
  eZ/Publish/Core/FieldType/BinaryBase/Type.php
  eZ/Publish/Core/FieldType/Image/Type.php
  eZ/Publish/Core/FieldType/Tests/BinaryFileTest.php
  eZ/Publish/Core/FieldType/Tests/ImageTest.php
  eZ/Publish/Core/FieldType/Tests/MediaTest.php
  eZ/Publish/Core/MVC/Symfony/Templating/Tests/Twig/Extension/_fixtures/functions/ez_file_size/ez_file_size.test
  eZ/Publish/Core/MVC/Symfony/Templating/Twig/Extension/FileSizeExtension.php
Labels: QA approved, Bug
